// ==========================================
// DEYMFLIX - Chinese Movies & Series Data
// ==========================================
// Add NEW Chinese titles HERE (not in app.js).
// They merge into the main `movies` list automatically and appear in the
// Chinese row, explore filters, search, and the player like any other title.
// IMPORTANT: this file must load BEFORE app.js on every page.
// Series entries: pair with an entry in chinese-series.js (chineseSeriesData)
// for episodes. The `id` must match between the two files.
// ==========================================

const chineseMovieData = [

  // ── 2026 Chinese movies (added 2026-10-03) — CinemaOS embeds ──
  {
    id: "The+Shadow's+Edge",
    imdbId: "tt34610311",
    title: "The Shadow's Edge",
    releaseDate: "2025-08-16",
    rating: 8.3,
    synopsis: "Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/cHKo3m8N1fwvEy2ZEr0xGmmMODV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg",
    manualEmbed: "cos:movie/1419406",
    trailerEmbed: "https://www.youtube.com/watch?v=xvmADAJOoCg",
    isSeries: false
  },
  {
    id: "The+Furious",
    imdbId: "tt33311069",
    title: "The Furious",
    releaseDate: "2026-06-10",
    rating: 8.2,
    synopsis: "After a criminal network kidnaps Wang Wei's daughter and the corrupt police refuse to assist him, Wei sets out on his own to locate her. Navin, a tenacious journalist whose wife has mysteriously vanished, is his only ally. In this explosive martial arts showdown, the unlikely duo fights the kidnappers ruthlessly driven by a furious vengeance.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ivQ1Z3lI1xWvAeGDHBw3CCYZDGJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/i0eR9O1FnCgBm1cH8WwqxGbAXMS.jpg",
    manualEmbed: "cos:movie/1280738",
    trailerEmbed: "https://www.youtube.com/watch?v=Avky8dVaqAI",
    isSeries: false
  },
  {
    id: "Ne+Zha+2",
    imdbId: "tt34956443",
    title: "Ne Zha 2",
    releaseDate: "2025-01-29",
    rating: 8.2,
    synopsis: "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gd9kxeEEONj5SECs4GA8Ddn3czI.jpg",
    manualEmbed: "cos:movie/980477",
    trailerEmbed: "https://www.youtube.com/watch?v=ETlOSBR92Fs",
    isSeries: false
  },
  {
    id: "Blades+of+the+Guardians",
    imdbId: "tt32649961",
    title: "Blades of the Guardians",
    releaseDate: "2026-02-17",
    rating: 8.2,
    synopsis: "Dao Ma, the \"second most wanted fugitive,\" is entrusted by his benefactor, the chief of Mo family clan, to take on a mysterious escort mission-escorting the \"most wanted fugitive\" to Chang'an.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/R84km7PJ0frFSNPmvIjG6LV1kg.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/29pJrsosphUdOMRDm4gCdhSkluI.jpg",
    manualEmbed: "cos:movie/1305781",
    trailerEmbed: "https://www.youtube.com/watch?v=7jkL4-uYriY",
    isSeries: false
  },
  {
    id: "Dear+You",
    imdbId: "tt41791573",
    title: "Dear You",
    releaseDate: "2026-04-30",
    rating: 8.8,
    synopsis: "Xiaowei travels to Thailand to find his \"billionaire grandfather\" who is out of contact due to debt problems, but unexpectedly find the one who has been corresponding with his grandmother for years is not her husband.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/rjmhzdVS3Ia535pFawju857e2Na.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dzWGnIAjUafpmY57F6vnm44FwWB.jpg",
    manualEmbed: "cos:movie/1671548",
    trailerEmbed: "https://www.youtube.com/watch?v=abeSQSbNXSk",
    isSeries: false
  },
  {
    id: "The+Legend+of+Hei+2",
    imdbId: "tt37284198",
    title: "The Legend of Hei 2",
    releaseDate: "2025-07-18",
    rating: 9,
    synopsis: "When an attack shatters the fragile peace between the spirit world and humanity, Hei teams up with Luye, the last disciple of his Shifu Wuxian, to expose a conspiracy that threatens both realms - and the bond they've sworn to protect.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/dRCUBiTKtsmju3fmSS4MK0ywcqR.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5tVZ1W5Pt6YbmJE4wrWcbVEUlAV.jpg",
    manualEmbed: "cos:movie/1144107",
    trailerEmbed: "https://www.youtube.com/watch?v=6t-uv2Vv_vA",
    isSeries: false
  },
  {
    id: "Kung+Fu+Soccer",
    imdbId: "tt36103784",
    title: "Kung Fu Soccer",
    releaseDate: "2026-07-11",
    rating: 6.1,
    synopsis: "The \"Supreme Invincible Cup\" is about to begin, and a host of top teams are about to engage in an unprecedented showdown! But the Kung Fu Women's Soccer Team has been dealt a hellish script right from the start?! Their opponents are all highly skilled, and external pressure is mounting. The schemes on the field are one after another... Can they use their kung fu to turn the tide on the green field?",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/6QgJQrClh9ej357yzLWgCxrjAmJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/J1UgJwRxDQS92kw75KgeVFZMHf.jpg",
    manualEmbed: "cos:movie/1491920",
    trailerEmbed: "https://www.youtube.com/watch?v=hR6I5FaHpyI",
    isSeries: false
  },
  {
    id: "Once+Upon+a+Time+in+the+Middle+East",
    imdbId: "tt34386754",
    title: "Once Upon a Time in the Middle East",
    releaseDate: "2026-08-08",
    rating: 9,
    synopsis: "Seeking a fresh start, chef Xu Fu travels to the Middle East to support his family and repay his debts. Alongside restaurant manager Ma Junsheng, he transforms the struggling Dragon Restaurant into a thriving business. But when war engulfs the city, their hard-won success is shattered and the restaurant becomes a refuge for those caught in the conflict. As danger closes in, Xu Fu must risk everything to protect his newfound community and preserve a small beacon of hope amid the devastation.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/wAuGgXjA7GV8NrKfmUKl2AP8vqG.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/zr7om0GOLOcLo7SXMmNEG5rz6de.jpg",
    manualEmbed: "cos:movie/1391021",
    trailerEmbed: "https://www.youtube.com/watch?v=iHDNxZF7LRw",
    isSeries: false
  },
  {
    id: "Ip+Man:+Kung+Fu+Legend",
    imdbId: "tt38682795",
    title: "Ip Man: Kung Fu Legend",
    releaseDate: "2026-07-22",
    rating: 6.7,
    synopsis: "In 1950s Hong Kong, British merchants and Chinese triads have joined forces to expand their territory, forcibly demolishing factories without regard for public welfare. This move draws fierce opposition from Ip Man, standing up for the workers, he faces pressure from all sides. Framed for murder, he is sent to prison. Within the prison walls, the triads set multiple deadly traps. Can Ip Man overcome these trials, escape the danger, and clear his name?",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/m3Low6jJrKXHSYFpXNkmYsG1Q6I.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6HBbzW5D7StUBRi0yO6ZEq9rNB5.jpg",
    manualEmbed: "cos:movie/1628071",
    trailerEmbed: "https://www.youtube.com/watch?v=cqlZSRvH7BU",
    isSeries: false
  },
  {
    id: "Tom+and+Jerry:+Forbidden+Compass",
    imdbId: "tt37185884",
    title: "Tom and Jerry: Forbidden Compass",
    releaseDate: "2025-08-02",
    rating: 6.6,
    synopsis: "During a chase inside a museum, Tom and Jerry find an ancient magical compass and end up being transported through time. Lost in a distant era, they will need to work together to find a way back home.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5qttWFjsO62k88civZaDMHiBTvy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9VM1KI9sVZETl0d00FK7CnBzxiw.jpg",
    manualEmbed: "cos:movie/1497970",
    trailerEmbed: "https://www.youtube.com/watch?v=4280xkO7x0w",
    isSeries: false
  },

  // ── 2026 Chinese series headers (added 2026-10-03) — episodes in chinese-series.js ──
  {
    id: "Against+the+Current",
    imdbId: "tt32500958",
    title: "Against the Current",
    releaseDate: "2026-09-11",
    rating: 6.8,
    synopsis: "Shen Jialan, once a nobleman's granddaughter, falls from grace after her family is falsely accused of treason. Abandoned by her fiancé Lin Jinqi, she is forced to assume a servant's identity in his household. Despite hardships, she refuses to bow to fate. With resilience and wit, she rises above class barriers, wins Lin Jinqi's heart, earns the family's respect, and ultimately clears her family's name.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/euBlF64efQmsl2y54LeNmLQPNob.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mZSewqVlY4F2F2Axm7hiG6KBOBp.jpg",
    manualEmbed: "cos:tv/282326/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=HXxzKhKBwAM",
    isSeries: true,
    completed: false
  },
  {
    id: "The+Early+Spring",
    imdbId: "tt37884717",
    title: "The Early Spring",
    releaseDate: "2026-08-26",
    rating: 8.5,
    synopsis: "New to Beijing, Shang Zhitao crosses paths with Luan Nian, a true creative genius. Bold and open-hearted, she grows stronger step by step and gradually breaks through the defenses around Luan's guarded heart. Drawn to each other, they find themselves caught in an intense, on-again, off-again relationship in the urban jungle. To love is to summon all your courage and leave no regrets, to heal each other, and to grow together. But when love and her career pull her in different directions, she puts her career first. When she has come into her own and he has learned to soften his sharp edges, they finally stand as equals, ready to write a new ending together...",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/lGFngmJWMO4HTPcI0sUGKBAFqMe.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/oUFUvEMCBP80e4eYsfVfxC8n7ih.jpg",
    manualEmbed: "cos:tv/299952/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=7JsnZ47CTDg",
    isSeries: true,
    completed: true
  },
  {
    id: "When+Destiny+Brings+the+Demon",
    imdbId: "tt33045752",
    title: "When Destiny Brings the Demon",
    releaseDate: "2025-08-16",
    rating: 8.4,
    synopsis: "Modern-day office drone Zou Yan accidentally stumbles into the world of cultivation and wakes up as Liao Tingyan, a disciple of the Qinggutian Sect. She's soon selected to serve the reclusive Grandmaster Sima Jiao, a powerful cultivator who's been secretly sealed inside a mountain for 500 years. Twisted by isolation and rage, he's cold, hot-tempered, and bent on revenge. Liao Tingyan doesn't know that \"her\" original identity is a demonic assassin. But to his surprise, she shows no ill will, no ambition, and no desire at all. Her nature fascinates him. Thus begins an unlikely romance between a villainous immortal and a healing-type \"slacker,\" a connection that defies fate and spans lifetimes.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/15yDwRPWsI75RdJaBVgb4K5m94I.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7VxcQrVD2POXg29q5wIFOGD7AY7.jpg",
    manualEmbed: "cos:tv/254476/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=hNsEPj0I0c4",
    isSeries: true,
    completed: true
  },
  {
    id: "Pursuit+of+Jade",
    imdbId: "tt35316225",
    title: "Pursuit of Jade",
    releaseDate: "2026-03-06",
    rating: 8.1,
    synopsis: "This drama follows Fan Changyu, a butcher’s daughter, and Xie Zheng, a fallen noble seeking revenge. Their fake marriage turns into true love, but war tears them apart. Determined, Fan Changyu wields her butcher’s knife on the battlefield, searching for justice and her husband. Meanwhile, Xie Zheng reclaims his title, fighting to protect his country and love. Reunited in battle, they stand together, defying fate, uncovering the truth, and returning home without forgetting their vows.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/g2CSCJuWm7IcpuRjxySQvZcJYnp.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yiUZ8Ck86FF3obLztVvSQqeBi0Y.jpg",
    manualEmbed: "cos:tv/279388/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=_ftwQZjmgqU",
    isSeries: true,
    completed: true
  },
  {
    id: "The+First+Frost",
    imdbId: "tt31887832",
    title: "The First Frost",
    releaseDate: "2025-02-18",
    rating: 8.4,
    synopsis: "Wen Yifan, by chance, ends up living with her high school classmate Sang Yan, whom she once rejected. They keep their distance until Wen Yifan learns from Sang Yan that she sleepwalks, intertwining their lives once more.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ywkwBd65CMvC33DDVFOQqr4mrVQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lO2CqipALTHkRblLIRDKgtMgwxX.jpg",
    manualEmbed: "cos:tv/250060/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=5CXtkD4ezXI",
    isSeries: true,
    completed: true
  },
  {
    id: "Revenged+Love",
    imdbId: "tt37370861",
    title: "Revenged Love",
    releaseDate: "2025-06-16",
    rating: 8.3,
    synopsis: "After Wu Suo-wei's girlfriend dumps him, he decides to get revenge by seducing her new boyfriend, Chi Cheng! It started as a game, but falling in love was never part of the plan.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kJTSJ6X9zjL4nYM8Oje21sTuoOZ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/aKvbFRFOzbaMB59575O5vUVaFyr.jpg",
    manualEmbed: "cos:tv/292035/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=4qmLHpHAyOA",
    isSeries: true,
    completed: true
  },
  {
    id: "Love+in+the+Clouds",
    imdbId: "tt32750951",
    title: "Love in the Clouds",
    releaseDate: "2025-10-08",
    rating: 9,
    synopsis: "At the annual Qingyun Conference in the Hexu Six Realms, Ji Bozai, a warrior from the Jixing Abyss with a past as a convict, defeated Ming Yi, the cold warrior goddess who had reigned supreme for seven consecutive years. Overnight, Ji Bozai became the hottest new star in Jixing Abyss. Meanwhile, Ming Yi, hiding her true identity, disguised herself as a dancer to get close to Ji Bozai. Under their carefully crafted personas, the two engaged in a thrilling dance of deception and attraction, fighting for justice and fairness, and ultimately found a deep and moving love.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1eOek63acPohNgvXog4uYnJT6fh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lAJCsUD3f6KhwdtbnevSAI1E9EU.jpg",
    manualEmbed: "cos:tv/262928/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=JeoJD8s9nHk",
    isSeries: true,
    completed: true
  },
  {
    id: "Perfect+Match",
    imdbId: "tt30972832",
    title: "Perfect Match",
    releaseDate: "2025-01-25",
    rating: 8.1,
    synopsis: "In the bustling capital of Bianjing during the Northern Song Dynasty, Madam Li moves her family in search of better marriage prospects for her five beautiful but quirky daughters, whose love lives have long been her worry. Each daughter, though famous for her beauty and wit, comes with unique quirks: the eldest, Shou Hua, has no interest in remarrying after early widowhood; the third, Kang Ning, is fierce and headstrong; the fourth, Hao De, is well-meaning but blunt; and the youngest, Le Shan, is spoiled and selective.  Challenges abound as they face unexpected setbacks, including a cold reception from the already-married sister they came to visit. As the family reestablishes their business, they navigate a series of humorous and heartwarming misadventures, ultimately finding love and fulfilling their mother’s hopes in this lively tale of family and romance.",
    isChinese: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/pAPupcfdOmTu1T0IS6cy3cmNYp1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/pg4xOroBDlxIhRK1m5xFyLgXrVD.jpg",
    manualEmbed: "cos:tv/254821/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=ZBGKQqMi7rM",
    isSeries: true,
    completed: true
  },
];
