// ===========================================================================
//  DEYMFLIX -- DlScreen85.java        (drop-in file, v1.4h)
// ===========================================================================
//  WHAT THIS IS
//    The whole "My Downloads" screen -- tabs, poster cards, progress bars,
//    Play / Retry / Resume / Cancel / Delete -- as ONE plain Java file.
//
//  WHY IT EXISTS
//    Every failed build came from pasting ~24 KB of code into the Sketchware
//    Java/Kotlin Injection editor: a hand-selected region arrived with a stray
//    brace and the whole file went unparseable. This file is NOT generated by
//    Sketchware, so nothing ever overwrites it and nothing has to be spliced.
//
//  HOW TO INSTALL (3 steps, no big paste)
//    1. Save this file as:
//         /storage/emulated/0/.sketchware/mysc/608/app/src/main/java/com/deymflix/eu/cc/DlScreen85.java
//       (same folder as MainActivity.java)
//    2. DownloadsActivity -> Logic -> vdots -> Java/Kotlin Injection:
//         clear ALL tabs, then in the onCreate tab type exactly this one line:
//             DlScreen85.show(this);
//    3. Build. downloads.xml stays empty -- this code builds the screen.
//
//  REQUIREMENTS
//    * the player activity must exist. It is launched by class name, so this
//      file compiles even if yours is spelled LocalplayerActivity (lowercase p)
//      or LocalPlayerActivity.
//    * MainActivity writes the download registry into the "deymflix_dl"
//      preferences (SECTION 1). This file only reads / removes those rows.
//
//  100% ASCII, zero pipe characters.
// ===========================================================================
package com.deymflix.eu.cc;

import android.app.Activity;
import android.app.DownloadManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Environment;
import android.os.Handler;
import android.os.StatFs;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Locale;

public class DlScreen85 {

    // Colours shared by the widgets (kept as strings so every widget agrees).
    private static final String C_BG = "#0B0B0F";
    private static final String C_RED = "#E50914";
    private static final String C_DIM = "#8A8A8A";
    private static final String C_SOFT = "#DDDDDD";
    private static final String C_BAD = "#E57373";
    private static final String C_POSTER_BG = "#1E1E24";

    // Poster bitmaps decoded once per download so the 1 second refresh never
    // re-downloads the same art (that was the card flicker).
    private static final HashMap<String, Bitmap> CACHE = new HashMap<String, Bitmap>();

    // -----------------------------------------------------------------------
    // State for one DownloadsActivity instance. Every listener captures this
    // object, so no static activity reference is kept anywhere.
    // -----------------------------------------------------------------------
    private static class State85 {
        Activity act;
        LinearLayout list;
        TextView empty;
        TextView tabDlTxt;
        TextView tabDoneTxt;
        View tabDlLine;
        View tabDoneLine;
        int tab = 0;      // 0 = Downloading (active), 1 = Downloaded (finished)
        float d = 1f;     // density
    }

    // -----------------------------------------------------------------------
    // One click listener for every button on every card.
    // kind: 1 = play, 2 = retry/restart, 4 = cancel, 5 = delete
    // -----------------------------------------------------------------------
    private static class Act85 implements View.OnClickListener {
        private final State85 st;
        private final int kind;
        private final long id;
        private final String title;
        private final String subName;
        private final int status;

        Act85(State85 st, int kind, long id, String title, String subName, int status) {
            this.st = st;
            this.kind = kind;
            this.id = id;
            this.title = title;
            this.subName = subName;
            this.status = status;
        }

        @Override public void onClick(View v) {
            DownloadManager dm = (DownloadManager) st.act.getSystemService(Context.DOWNLOAD_SERVICE);
            if (kind == 1) {
                playDownload(st.act, id, title, subName);
            } else if (kind == 2) {
                try { dm.remove(id); } catch (Exception e) { }
                forgetMeta(st.act, id);
                Toast.makeText(st.act, "Open the movie again and tap download", Toast.LENGTH_SHORT).show();
                render(st);
            } else if (kind == 4) {
                try { dm.remove(id); } catch (Exception e) { }
                forgetMeta(st.act, id);
                Toast.makeText(st.act, "Cancelled", Toast.LENGTH_SHORT).show();
                render(st);
            } else {
                deleteDownload(st.act, id, subName, status);
                render(st);
            }
        }
    }

    // =======================================================================
    //  ENTRY POINT -- call DlScreen85.show(this) from DownloadsActivity onCreate
    // =======================================================================
    public static void show(final Activity act) {
        if (act == null) return;

        final State85 st = new State85();
        st.act = act;
        st.d = act.getResources().getDisplayMetrics().density;
        final float d = st.d;

        LinearLayout root = new LinearLayout(act);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setBackgroundColor(Color.parseColor(C_BG));
        root.setPadding((int) (18 * d), (int) (20 * d), (int) (18 * d), (int) (18 * d));

        // Back header -> closes the activity
        TextView head = new TextView(act);
        head.setText("<  My Downloads");
        head.setTextColor(Color.WHITE);
        head.setTextSize(20);
        head.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        head.setPadding(0, (int) (4 * d), 0, (int) (4 * d));
        head.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { act.finish(); }
        });
        root.addView(head);

        // "Internal storage  x.x GB remaining"
        final TextView storage = new TextView(act);
        storage.setTextSize(13);
        storage.setPadding(0, (int) (10 * d), 0, (int) (2 * d));
        root.addView(storage);

        // Tabs: Downloading / Downloaded with a red underline on the active one
        LinearLayout tabs = new LinearLayout(act);
        tabs.setOrientation(LinearLayout.HORIZONTAL);
        LinearLayout.LayoutParams tlp = new LinearLayout.LayoutParams(-1, -2);
        tlp.topMargin = (int) (12 * d);
        root.addView(tabs, tlp);

        st.tabDlTxt = tabLabel(act, "Downloading");
        st.tabDlLine = tabLine(act);
        LinearLayout tabDl = tabBox(act, st.tabDlTxt, st.tabDlLine);
        tabs.addView(tabDl, new LinearLayout.LayoutParams(0, -2, 1f));

        st.tabDoneTxt = tabLabel(act, "Downloaded");
        st.tabDoneLine = tabLine(act);
        LinearLayout tabDone = tabBox(act, st.tabDoneTxt, st.tabDoneLine);
        tabs.addView(tabDone, new LinearLayout.LayoutParams(0, -2, 1f));

        tabDl.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { st.tab = 0; styleTabs(st); render(st); }
        });
        tabDone.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { st.tab = 1; styleTabs(st); render(st); }
        });

        // The list + the empty state (both created BEFORE render() is used)
        st.list = new LinearLayout(act);
        st.list.setOrientation(LinearLayout.VERTICAL);
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, -2);
        lp.topMargin = (int) (14 * d);
        root.addView(st.list, lp);

        st.empty = new TextView(act);
        st.empty.setTextColor(Color.parseColor(C_DIM));
        st.empty.setTextSize(14);
        st.empty.setGravity(Gravity.CENTER);
        LinearLayout.LayoutParams ep = new LinearLayout.LayoutParams(-1, -2);
        ep.topMargin = (int) (40 * d);
        root.addView(st.empty, ep);

        styleTabs(st);
        act.setContentView(root);

        // Live refresh (1s) while the screen is open: storage line + the cards.
        // Cards are rebuilt in place, posters come from the bitmap cache.
        final Handler h = new Handler();
        h.post(new Runnable() {
            @Override public void run() {
                if (act.isFinishing()) return;
                refreshStorage(act, storage);
                render(st);
                h.postDelayed(this, 1000);
            }
        });
    }

    // =======================================================================
    //  Small widgets
    // =======================================================================
    private static TextView tabLabel(Activity act, String text) {
        float d = act.getResources().getDisplayMetrics().density;
        TextView t = new TextView(act);
        t.setText(text);
        t.setTextSize(15);
        t.setGravity(Gravity.CENTER);
        t.setPadding(0, (int) (6 * d), 0, 0);
        return t;
    }

    private static View tabLine(Activity act) {
        float d = act.getResources().getDisplayMetrics().density;
        View v = new View(act);
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, (int) (3 * d));
        lp.topMargin = (int) (8 * d);
        v.setLayoutParams(lp);
        return v;
    }

    private static LinearLayout tabBox(Activity act, TextView label, View line) {
        LinearLayout box = new LinearLayout(act);
        box.setOrientation(LinearLayout.VERTICAL);
        box.addView(label, new LinearLayout.LayoutParams(-1, -2));
        box.addView(line);
        return box;
    }

    private static Button mkBtn(Activity act, String label, boolean bold, boolean red, float d) {
        Button b = new Button(act);
        b.setText(label);
        b.setAllCaps(false);
        if (red) {
            b.setTextColor(Color.WHITE);
            if (bold) b.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
            b.setBackgroundDrawable(rounded(C_RED, 10f * d));
            b.setPadding((int) (22 * d), 0, (int) (22 * d), 0);
        } else {
            b.setTextColor(Color.parseColor(C_SOFT));
            b.setBackgroundDrawable(rounded("#00000000", 0f));
        }
        return b;
    }

    private static GradientDrawable rounded(String color, float radius) {
        GradientDrawable g = new GradientDrawable();
        g.setColor(Color.parseColor(color));
        g.setCornerRadius(radius);
        return g;
    }

    private static void styleTabs(State85 st) {
        int on = Color.WHITE;
        int off = Color.parseColor(C_DIM);
        int red = Color.parseColor(C_RED);
        boolean first = st.tab == 0;
        st.tabDlTxt.setTextColor(first ? on : off);
        st.tabDlTxt.setTypeface(first ? android.graphics.Typeface.DEFAULT_BOLD : android.graphics.Typeface.DEFAULT);
        st.tabDlLine.setBackgroundColor(first ? red : Color.TRANSPARENT);
        st.tabDoneTxt.setTextColor(first ? off : on);
        st.tabDoneTxt.setTypeface(first ? android.graphics.Typeface.DEFAULT : android.graphics.Typeface.DEFAULT_BOLD);
        st.tabDoneLine.setBackgroundColor(first ? Color.TRANSPARENT : red);
    }

    // =======================================================================
    //  Storage line
    // =======================================================================
    private static void refreshStorage(Activity act, TextView tv) {
        try {
            StatFs stat = new StatFs(Environment.getExternalStorageDirectory().getPath());
            long free = stat.getAvailableBlocksLong() * stat.getBlockSizeLong();
            tv.setText("Internal storage  " + humanSize(free) + " remaining");
            tv.setTextColor(Color.parseColor("#9A9A9A"));
        } catch (Exception e) {
            tv.setText("");
        }
    }

    // =======================================================================
    //  The list
    // =======================================================================
    private static void render(State85 st) {
        if (st.list == null) return;
        st.list.removeAllViews();

        int shown = 0;
        try {
            DownloadManager dm = (DownloadManager) st.act.getSystemService(Context.DOWNLOAD_SERVICE);
            Cursor c = dm.query(new DownloadManager.Query());
            if (c != null) {
                while (c.moveToNext() && shown < 40) {
                    long id = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_ID));
                    int status = c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));
                    boolean finished = status == DownloadManager.STATUS_SUCCESSFUL;
                    if (st.tab == 0 && finished) continue;
                    if (st.tab == 1 && !finished) continue;
                    long done = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));
                    long total = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));
                    String[] meta = readMeta(st.act, id);
                    String title = meta[0] == null ? "" : meta[0];
                    if (title.length() == 0) title = "Download";
                    String poster = meta[1] == null ? "" : meta[1];
                    String subName = meta[2] == null ? "" : meta[2];
                    shown++;
                    addCard(st, id, title, poster, subName, status, done, total);
                }
                c.close();
            }
        } catch (Exception e) {
            // a broken query must never crash the screen -- show what we have
        }

        if (st.empty != null) {
            st.empty.setText(st.tab == 0
                    ? "No downloads in progress.\nStart one from any movie page."
                    : "Nothing downloaded yet.\nOpen any movie and tap the download button.");
            st.empty.setVisibility(shown > 0 ? View.GONE : View.VISIBLE);
        }
    }

    private static void addCard(State85 st, final long id, final String title, final String poster, final String subName, final int status, final long done, final long total) {
        Activity act = st.act;
        final float d = st.d;

        LinearLayout card = new LinearLayout(act);
        card.setOrientation(LinearLayout.HORIZONTAL);
        card.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams cp = new LinearLayout.LayoutParams(-1, -2);
        cp.topMargin = (int) (12 * d);
        st.list.addView(card, cp);

        ImageView thumb = new ImageView(act);
        LinearLayout.LayoutParams tp = new LinearLayout.LayoutParams((int) (104 * d), (int) (150 * d));
        tp.rightMargin = (int) (16 * d);
        thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);
        thumb.setBackgroundDrawable(rounded(C_POSTER_BG, 8f * d));
        card.addView(thumb, tp);
        loadPoster(act, thumb, poster, (int) (104 * d), (int) (150 * d));

        LinearLayout right = new LinearLayout(act);
        right.setOrientation(LinearLayout.VERTICAL);
        card.addView(right, new LinearLayout.LayoutParams(-1, -2, 1f));

        TextView t = new TextView(act);
        t.setText(title);
        t.setTextColor(Color.WHITE);
        t.setTextSize(16);
        t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        t.setSingleLine(true);
        t.setEllipsize(android.text.TextUtils.TruncateAt.END);
        right.addView(t);

        TextView sub = new TextView(act);
        sub.setTextSize(14);
        boolean showBar = false;
        int pct = 0;
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            sub.setText("Downloaded");
            sub.setTextColor(Color.parseColor("#EDEDED"));
        } else if (status == DownloadManager.STATUS_FAILED) {
            sub.setText("Failed");
            sub.setTextColor(Color.parseColor(C_BAD));
        } else if (status == DownloadManager.STATUS_PAUSED) {
            sub.setText("Paused");
            sub.setTextColor(Color.parseColor(C_DIM));
            if (total > 0) { pct = (int) (done * 100 / total); showBar = true; }
        } else if (status == DownloadManager.STATUS_PENDING) {
            sub.setText("Waiting...");
            sub.setTextColor(Color.parseColor(C_DIM));
        } else if (total > 0) {
            pct = (int) (done * 100 / total);
            sub.setText(humanSize(done) + " / " + humanSize(total));
            sub.setTextColor(Color.parseColor(C_DIM));
            showBar = true;
        } else {
            sub.setText("Starting...");
            sub.setTextColor(Color.parseColor(C_DIM));
        }
        LinearLayout.LayoutParams sp = new LinearLayout.LayoutParams(-1, -2);
        sp.topMargin = (int) (8 * d);
        right.addView(sub, sp);

        if (showBar) {
            ProgressBar bar = new ProgressBar(act, null, android.R.attr.progressBarStyleHorizontal);
            bar.setMax(100);
            bar.setProgress(pct);
            try {
                bar.getProgressDrawable().setColorFilter(Color.parseColor(C_RED), android.graphics.PorterDuff.Mode.SRC_IN);
            } catch (Exception e) { }
            LinearLayout.LayoutParams bp = new LinearLayout.LayoutParams(-1, (int) (3 * d));
            bp.topMargin = (int) (8 * d);
            right.addView(bar, bp);
        }

        LinearLayout row = new LinearLayout(act);
        row.setOrientation(LinearLayout.HORIZONTAL);
        // "+" instead of bitwise-or: this file must contain ZERO pipe chars
        row.setGravity(Gravity.RIGHT + Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams rp = new LinearLayout.LayoutParams(-1, -2);
        rp.topMargin = (int) (10 * d);
        right.addView(row, rp);

        LinearLayout.LayoutParams abp = new LinearLayout.LayoutParams(-2, -2);
        abp.leftMargin = (int) (18 * d);

        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            Button play = mkBtn(act, "Play", true, true, d);
            play.setOnClickListener(new Act85(st, 1, id, title, subName, status));
            row.addView(play, abp);
        } else if (status == DownloadManager.STATUS_FAILED) {
            Button retry = mkBtn(act, "Retry", false, true, d);
            retry.setOnClickListener(new Act85(st, 2, id, title, subName, status));
            row.addView(retry, abp);
        } else if (status == DownloadManager.STATUS_PAUSED) {
            // DownloadManager has NO resume() API, so a paused row offers a
            // restart instead (the file is re-fetched from the movie page).
            Button restart = mkBtn(act, "Restart", false, true, d);
            restart.setOnClickListener(new Act85(st, 2, id, title, subName, status));
            row.addView(restart, abp);
        } else {
            Button cancel = mkBtn(act, "Cancel", false, false, d);
            cancel.setOnClickListener(new Act85(st, 4, id, title, subName, status));
            row.addView(cancel, abp);
        }

        Button del = mkBtn(act, "Delete", false, false, d);
        del.setTextColor(Color.parseColor(C_BAD));
        del.setOnClickListener(new Act85(st, 5, id, title, subName, status));
        row.addView(del, abp);
    }

    // =======================================================================
    //  Play a finished download inside the app (offline, landscape player)
    // =======================================================================
    private static void playDownload(Activity act, long id, String title, String subName) {
        try {
            DownloadManager dm = (DownloadManager) act.getSystemService(Context.DOWNLOAD_SERVICE);
            Cursor c = dm.query(new DownloadManager.Query().setFilterById(id));
            String path = "";
            String reason = "";
            if (c != null && c.moveToFirst()) {
                int status = c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));
                reason = c.getString(c.getColumnIndexOrThrow(DownloadManager.COLUMN_REASON));
                if (status == DownloadManager.STATUS_SUCCESSFUL) {
                    android.net.Uri u = dm.getUriForDownloadedFile(id);
                    if (u != null && u.getPath() != null) path = u.getPath();
                }
            }
            if (c != null) c.close();

            if (path.length() == 0) {
                String msg = "File is gone -- delete this row and download again.";
                if (reason != null && reason.length() > 0) msg = "Cannot play (code " + reason + "). Try downloading again.";
                Toast.makeText(act, msg, Toast.LENGTH_LONG).show();
                return;
            }

            Intent it = new Intent();
            it.putExtra("path", path);
            it.putExtra("title", title);
            if (subName != null && subName.length() > 0) it.putExtra("sub", subName);

            // Launched by class NAME so this file compiles no matter how the
            // activity is spelled in your project.
            String[] names = { "com.deymflix.eu.cc.LocalplayerActivity", "com.deymflix.eu.cc.LocalPlayerActivity" };
            for (int i = 0; i < names.length; i++) {
                try {
                    it.setClassName(act, names[i]);
                    act.startActivity(it);
                    return;
                } catch (Exception e) {
                    // try the next spelling
                }
            }
            Toast.makeText(act, "Player activity not found -- check its name in Sketchware", Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            Toast.makeText(act, "Cannot open this download", Toast.LENGTH_SHORT).show();
        }
    }

    // =======================================================================
    //  Delete: the file, the subtitle that traveled with it, the registry row
    // =======================================================================
    private static void deleteDownload(Activity act, long id, String subName, int status) {
        DownloadManager dm = (DownloadManager) act.getSystemService(Context.DOWNLOAD_SERVICE);
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            try {
                String local = dm.getUriForDownloadedFile(id).toString();
                new File(android.net.Uri.parse(local).getPath()).delete();
            } catch (Exception e) { }
            if (subName != null && subName.length() > 0) {
                try {
                    File dir = new File(act.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "Deymflix");
                    new File(dir, subName).delete();
                } catch (Exception e) { }
            }
        }
        try { dm.remove(id); } catch (Exception e) { }
        forgetMeta(act, id);
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            Toast.makeText(act, "Deleted", Toast.LENGTH_SHORT).show();
        }
    }

    // =======================================================================
    //  Registry helpers (same "deymflix_dl" preferences MainActivity writes)
    // =======================================================================
    private static String[] readMeta(Activity act, long id) {
        SharedPreferences p = act.getSharedPreferences("deymflix_dl", 0);
        String raw = p.getString(String.valueOf(id), "");
        if (raw == null) return new String[] { "", "", "" };
        if (raw.length() == 0) return new String[] { "", "", "" };
        String title = raw;
        String poster = "";
        String subName = "";
        int cutSub = raw.indexOf("[SUB]");
        if (cutSub >= 0) {
            subName = raw.substring(cutSub + 5);
            raw = raw.substring(0, cutSub);
        }
        int cutPoster = raw.indexOf("[POSTER]");
        if (cutPoster >= 0) {
            poster = raw.substring(cutPoster + 8);
            title = raw.substring(0, cutPoster);
        }
        return new String[] { title, poster, subName };
    }

    private static void forgetMeta(Activity act, long id) {
        SharedPreferences p = act.getSharedPreferences("deymflix_dl", 0);
        p.edit().remove(String.valueOf(id)).apply();
    }

    // =======================================================================
    //  Poster thumbnails (cached, off the UI thread)
    // =======================================================================
    private static void loadPoster(final Activity act, final ImageView target, final String url, final int w, final int h) {
        if (url == null) return;
        if (url.length() == 0) return;
        Bitmap cached = CACHE.get(url);
        if (cached != null) {
            target.setImageBitmap(cached);
            return;
        }
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                try {
                    URL u = new URL(url);
                    HttpURLConnection c = (HttpURLConnection) u.openConnection();
                    c.setConnectTimeout(8000);
                    c.setReadTimeout(8000);
                    c.setRequestProperty("User-Agent", "DeymflixApp/1.4");
                    InputStream in = new BufferedInputStream(c.getInputStream());
                    final Bitmap bmp = BitmapFactory.decodeStream(in);
                    in.close();
                    c.disconnect();
                    if (bmp == null) return;
                    final Bitmap scaled = Bitmap.createScaledBitmap(bmp, w, h, true);
                    if (CACHE.size() > 60) CACHE.clear();
                    CACHE.put(url, scaled);
                    act.runOnUiThread(new Runnable() {
                        @Override public void run() {
                            try { target.setImageBitmap(scaled); } catch (Exception e) { }
                        }
                    });
                } catch (Exception e) {
                    // no network / bad url: the placeholder background stays
                }
            }
        });
        t.start();
    }

    // =======================================================================
    //  Misc
    // =======================================================================
    private static String humanSize(long bytes) {
        if (bytes <= 0) return "-";
        double b = bytes;
        String[] units = { "B", "KB", "MB", "GB" };
        int i = 0;
        while (b >= 1024 && i < units.length - 1) { b /= 1024; i++; }
        return String.format(Locale.US, "%.1f %s", b, units[i]);
    }
}
