// ===========================================================================
//  DEYMFLIX -- DlScreen85.java        (drop-in file, v1.4h)
// ===========================================================================
//  WHAT THIS IS
//    The whole "My Downloads" screen -- tabs, poster cards, progress bars,
//    Play / Retry / Resume / Cancel / Delete -- as ONE plain Java file.
//
//  WHY IT EXISTS
//    Every failed build came from pasting ~24 KB of code into the Sketchware
//    Java/Kotlin Injection editor: a hand-selected region arrived with a stray
//    brace and the whole file went unparseable. This file is NOT generated by
//    Sketchware, so nothing ever overwrites it and nothing has to be spliced.
//
//  HOW TO INSTALL (3 steps, no big paste)
//    1. Save this file as:
//         /storage/emulated/0/.sketchware/mysc/608/app/src/main/java/com/deymflix/eu/cc/DlScreen85.java
//       (same folder as MainActivity.java)
//    2. DownloadsActivity -> Logic -> vdots -> Java/Kotlin Injection:
//         clear ALL tabs, then in the onCreate tab type exactly this one line:
//             DlScreen85.show(this);
//    3. Build. downloads.xml stays empty -- this code builds the screen.
//
//  REQUIREMENTS
//    * the player activity must exist. It is launched by class name, so this
//      file compiles even if yours is spelled LocalplayerActivity (lowercase p)
//      or LocalPlayerActivity.
//    * MainActivity writes the download registry into the "deymflix_dl"
//      preferences (SECTION 1). This file only reads / removes those rows.
//
//  100% ASCII, zero pipe characters.
// ===========================================================================
package com.deymflix.eu.cc;

import android.app.Activity;
import android.app.DownloadManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Environment;
import android.os.Handler;
import android.os.StatFs;
import android.os.SystemClock;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Locale;

public class DlScreen85 {

    // Colours shared by the widgets (kept as strings so every widget agrees).
    private static final String C_BG = "#0B0B0F";

    // Library build tag: shown in the Downloads settings dialog so the
    // running app build can always be identified (matches the deymflix-
    // screens-1.0 zip that was imported into Sketchware).
    public static final String LIB_BUILD = "screens-2026.09.25-r6";
    private static final String C_RED = "#E50914";
    private static final String C_DIM = "#8A8A8A";
    private static final String C_SOFT = "#DDDDDD";
    private static final String C_BAD = "#E57373";
    private static final String C_POSTER_BG = "#1E1E24";

    // Poster bitmaps decoded once per download so the 1 second refresh never
    // re-downloads the same art (that was the card flicker).
    private static final HashMap<String, Bitmap> CACHE = new HashMap<String, Bitmap>();

    // -----------------------------------------------------------------------
    // State for one DownloadsActivity instance. Every listener captures this
    // object, so no static activity reference is kept anywhere.
    // -----------------------------------------------------------------------
    private static class State85 {
        Activity act;
        LinearLayout list;
        TextView empty;
        TextView tabDlTxt;
        TextView tabDoneTxt;
        View tabDlLine;
        View tabDoneLine;
        android.widget.EditText search;   // filter box under the tabs
        String query = "";                // current lowercase filter
        java.util.HashSet<String> expanded = new java.util.HashSet<String>();
        int tab = 0;      // 0 = Downloading (active), 1 = Downloaded (finished)
        float d = 1f;     // density

        // SELECTION MODE (bulk delete): long-press a card to enter. Keys are
        // engine rowIds ("M...") or DownloadManager ids prefixed "D".
        boolean selectMode = false;
        java.util.HashSet<String> selected = new java.util.HashSet<String>();
        LinearLayout actionBar;   // bottom Delete / Cancel bar
        Button deleteBtn;

        // SERIES PAGE (LokLok style): tapping a series folder opens a
        // dedicated page instead of an inline dropdown. While open,
        // seriesName is the series title and st.list points at the series
        // list host; the 1s refresh renders it until back is pressed.
        View mainRoot;            // main downloads content view
        LinearLayout mainList;    // main list host (st.list swap target)
        String seriesName;        // null = main list, non-null = series page
        TextView seriesStorage;
        TextView seriesEdit;
        LinearLayout seriesBar;
        Button seriesDeleteBtn;
    }

    // "Series Name ep3" -> "Series Name" (null when the title is a movie,
    // i.e. no episode marker). Mirrors the site's series grouping.
    private static String seriesOf(String title) {
        if (title == null) return null;
        int ep = episodeNumOf(title);
        if (ep <= 0) return null;
        String s = title.replaceAll("\\bep?\\.?\\s*\\d{1,2}\\b", " ");
        s = s.replaceAll("\\s+", " ").trim();
        if (s.length() == 0) return null;
        return s;
    }

    // Episode sub-title: the descriptive episode name saved at download
    // time (registry key "st_<rowId>" -> the raw episode title from the
    // site, e.g. "Episode 3 - Testing Her Faith"). Empty when unknown.
    private static String episodeSubTitleOf(String title) {
        if (title == null) return "";
        String raw = STATE_NAME_CACHE.get(title.toLowerCase(java.util.Locale.US));
        return raw == null ? "" : raw;
    }

    // in-memory map title -> episode name for cards rendered this session
    static final java.util.HashMap<String, String> STATE_NAME_CACHE =
            new java.util.HashMap<String, String>();

    // Series key for the ep1 pre-pass: title minus its episode marker.
    private static String seriesKeyOf(String title) {
        if (title == null) return "";
        String s = title.replaceAll("\\bep?\\.?\\s*\\d{1,2}\\b", " ");
        return s.replaceAll("\\s+", " ").trim().toLowerCase(java.util.Locale.US);
    }

    // "Series Name ep3" -> 3 (0 when not an episode)
    private static int episodeNumOf(String t) {
        if (t == null) return 0;
        java.util.regex.Matcher m = java.util.regex.Pattern
                .compile("\\bep?\\.?\\s*(\\d{1,2})\\b")
                .matcher(t.toLowerCase());
        if (m.find()) {
            try { return Integer.parseInt(m.group(1)); } catch (Exception e) { return 0; }
        }
        return 0;
    }

    private static boolean matchesQuery(String title, String q) {
        if (q.length() == 0) return true;
        if (title == null) return false;
        return title.toLowerCase().indexOf(q) >= 0;
    }

    // -----------------------------------------------------------------------
    // One click listener for every button on every card.
    // kind: 1 = play, 2 = retry/restart, 4 = cancel, 5 = delete
    // -----------------------------------------------------------------------
    private static class Act85 implements View.OnClickListener {
        private final State85 st;
        private final int kind;
        private final long id;
        private final boolean eng;   // true = DlSpeed85 engine row
        private final String rowId;  // engine registry key ("M...")
        private final String title;
        private final String subName;
        private final int status;

        Act85(State85 st, int kind, long id, String title, String subName, int status) {
            this(st, kind, id, false, "", title, subName, status);
        }

        Act85(State85 st, int kind, String rowId, String title, String subName, int status) {
            this(st, kind, 0L, true, rowId == null ? "" : rowId, title, subName, status);
        }

        private Act85(State85 st, int kind, long id, boolean eng, String rowId,
                String title, String subName, int status) {
            this.st = st;
            this.kind = kind;
            this.id = id;
            this.eng = eng;
            this.rowId = rowId;
            this.title = title;
            this.subName = subName;
            this.status = status;
        }

        @Override public void onClick(View v) {
            DownloadManager dm = (DownloadManager) st.act.getSystemService(Context.DOWNLOAD_SERVICE);
            if (kind == 1) {
                if (eng) playEngine(st.act, rowId, title, subName);
                else playDownload(st.act, id, title, subName);
            } else if (kind == 2) {
                // Failed DownloadManager row: retry through the fast engine.
                // The url is pulled back out of DownloadManager, the row is
                // removed, and the engine shows "Retrieving files..." while
                // it probes the size, then starts over.
                String[] m = readMeta(st.act, id);
                DlSpeed85.restartFromDm(st.act, id, title, m[1], subName);
                render(st);
            } else if (kind == 4) {
                try { dm.remove(id); } catch (Exception e) { }
                forgetMeta(st.act, id);
                Toast.makeText(st.act, "Cancelled", Toast.LENGTH_SHORT).show();
                render(st);
            } else if (kind == 6) {
                // Engine row retry: wipes the parts, restarts the same url.
                DlSpeed85.restartRow(st.act, rowId);
                render(st);
            } else if (kind == 7) {
                DlSpeed85.cancelRow(st.act, rowId);
                Toast.makeText(st.act, "Cancelled", Toast.LENGTH_SHORT).show();
                render(st);
            } else if (kind == 8) {
                DlSpeed85.deleteRow(st.act, rowId);
                Toast.makeText(st.act, "Deleted", Toast.LENGTH_SHORT).show();
                render(st);
            } else {
                deleteDownload(st.act, id, subName, status);
                render(st);
            }
        }
    }

    // =======================================================================
    //  ENTRY POINT -- call DlScreen85.show(this) from DownloadsActivity onCreate
    // =======================================================================
    public static void show(final Activity act) {
        if (act == null) return;

        final State85 st = new State85();
        st.act = act;
        st.d = act.getResources().getDisplayMetrics().density;
        final float d = st.d;

        LinearLayout root = new LinearLayout(act);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setBackgroundColor(Color.parseColor(C_BG));
        root.setPadding((int) (18 * d), (int) (20 * d), (int) (18 * d), (int) (18 * d));

        // Back header -> closes the activity
        TextView head = new TextView(act);
        head.setText("<  My Downloads");
        head.setTextColor(Color.WHITE);
        head.setTextSize(20);
        head.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        head.setPadding(0, (int) (4 * d), 0, (int) (4 * d));
        head.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { act.finish(); }
        });

        // Header row: back title on the left, Settings on the right.
        LinearLayout headRow = new LinearLayout(act);
        headRow.setOrientation(LinearLayout.HORIZONTAL);
        headRow.setGravity(Gravity.CENTER_VERTICAL);
        headRow.addView(head, new LinearLayout.LayoutParams(0, -2, 1f));
        // GEAR ICON (drawn with Canvas -- no emoji, matches the theme):
        // opens the Downloads settings dialog.
        android.view.View gear = new android.view.View(act) {
            private final android.graphics.Paint gp = new android.graphics.Paint(
                    android.graphics.Paint.ANTI_ALIAS_FLAG);
            private final android.graphics.Path path = new android.graphics.Path();
            @Override protected void onDraw(android.graphics.Canvas c) {
                super.onDraw(c);
                int w = getWidth(); int h = getHeight();
                if (w == 0) return;
                if (h == 0) return;
                float s = Math.min(w, h) / 24f;
                gp.setColor(Color.parseColor("#C9C9CF"));
                gp.setStyle(android.graphics.Paint.Style.FILL);
                try {
                    path.set(androidx.core.graphics.PathParser.createPathFromPathData(
                            "M19.14 12.94c.04-.3.06-.61.06-.94 0-.32-.02-.64-.07-.94l2.03-1.58c.18-.14.23-.41.12-.61l-1.92-3.32c-.12-.22-.37-.29-.59-.22l-2.39.96c-.5-.38-1.03-.7-1.62-.94l-.36-2.54c-.04-.24-.24-.41-.48-.41h-3.84c-.24 0-.43.17-.47.41l-.36 2.54c-.59.24-1.13.57-1.62.94l-2.39-.96c-.22-.08-.47 0-.59.22L2.74 8.87c-.12.21-.08.47.12.61l2.03 1.58c-.05.3-.09.63-.09.94s.02.64.07.94l-2.03 1.58c-.18.14-.23.41-.12.61l1.92 3.32c.12.22.37.29.59.22l2.39-.96c.5.38 1.03.7 1.62.94l.36 2.54c.05.24.24.41.48.41h3.84c.24 0 .44-.17.47-.41l.36-2.54c.59-.24 1.13-.56 1.62-.94l2.39.96c.22.08.47 0 .59-.22l1.92-3.32c.12-.22.07-.47-.12-.61l-2.01-1.58zM12 15.6c-1.98 0-3.6-1.62-3.6-3.6s1.62-3.6 3.6-3.6 3.6 1.62 3.6 3.6-1.62 3.6-3.6 3.6z"));
                } catch (Throwable t) { }
                c.save();
                c.translate((w - 24f * s) / 2f, (h - 24f * s) / 2f);
                c.scale(s, s);
                c.drawPath(path, gp);
                c.restore();
            }
        };
        android.graphics.drawable.GradientDrawable gearBg = new android.graphics.drawable.GradientDrawable();
        gearBg.setColor(Color.parseColor("#16161C"));
        gearBg.setCornerRadius(12 * d);
        gearBg.setStroke(1, Color.parseColor("#2A2A30"));
        gear.setBackgroundDrawable(gearBg);
        int gs = (int) (32 * d);
        gear.setPadding(0, 0, 0, 0);
        gear.setClickable(true);
        gear.setFocusable(true);
        gear.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { showSettingsDialog(st); }
        });
        LinearLayout.LayoutParams gearLp = new LinearLayout.LayoutParams(gs, gs);
        gearLp.leftMargin = (int) (10 * d);
        headRow.addView(gear, gearLp);
        root.addView(headRow);

        // "Internal storage  x.x GB remaining"
        final TextView storage = new TextView(act);
        storage.setTextSize(13);
        storage.setPadding(0, (int) (10 * d), 0, (int) (2 * d));
        root.addView(storage);

        // Tabs: Downloading / Downloaded with a red underline on the active one
        LinearLayout tabs = new LinearLayout(act);
        tabs.setOrientation(LinearLayout.HORIZONTAL);
        LinearLayout.LayoutParams tlp = new LinearLayout.LayoutParams(-1, -2);
        tlp.topMargin = (int) (12 * d);
        root.addView(tabs, tlp);

        st.tabDlTxt = tabLabel(act, "Downloading");
        st.tabDlLine = tabLine(act);
        LinearLayout tabDl = tabBox(act, st.tabDlTxt, st.tabDlLine);
        tabs.addView(tabDl, new LinearLayout.LayoutParams(0, -2, 1f));

        st.tabDoneTxt = tabLabel(act, "Downloaded");
        st.tabDoneLine = tabLine(act);
        LinearLayout tabDone = tabBox(act, st.tabDoneTxt, st.tabDoneLine);
        tabs.addView(tabDone, new LinearLayout.LayoutParams(0, -2, 1f));

        tabDl.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { st.tab = 0; styleTabs(st); render(st); }
        });
        tabDone.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { st.tab = 1; styleTabs(st); render(st); }
        });
        final android.widget.EditText search = new android.widget.EditText(act);
        st.search = search;
        search.setHint("Search downloads...");
        search.setSingleLine(true);
        search.setTextColor(Color.WHITE);
        search.setHintTextColor(Color.parseColor("#6E6E76"));
        search.setTextSize(14);
        search.setBackgroundDrawable(null);
        search.setPadding((int) (12 * d), (int) (9 * d), (int) (12 * d), (int) (9 * d));
        android.graphics.drawable.GradientDrawable sBg =
                new android.graphics.drawable.GradientDrawable();
        sBg.setColor(Color.parseColor("#16161C"));
        sBg.setCornerRadius(12 * d);
        sBg.setStroke(1, Color.parseColor("#2A2A30"));
        search.setBackgroundDrawable(sBg);
        LinearLayout.LayoutParams seLp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT);
        seLp.topMargin = (int) (10 * d);
        root.addView(search, seLp);
        search.addTextChangedListener(new android.text.TextWatcher() {
            @Override public void beforeTextChanged(CharSequence s, int a, int b2, int c2) { }
            @Override public void onTextChanged(CharSequence s, int a, int b2, int c2) { }
            @Override public void afterTextChanged(android.text.Editable s) {
                String q = String.valueOf(s);
                if (q.equals(st.query)) return;
                st.query = q.toLowerCase();
                render(st);
            }
        });

        // The scrollable list + empty state. Everything below the tabs lives
        // in one ScrollView so long lists scroll (they previously fell off
        // the bottom of the screen with no way to reach them).
        final android.widget.ScrollView scroller = new android.widget.ScrollView(act);
        scroller.setVerticalScrollBarEnabled(true);
        scroller.setFillViewport(true);
        LinearLayout listHost = new LinearLayout(act);
        listHost.setOrientation(LinearLayout.VERTICAL);
        scroller.addView(listHost, new android.view.ViewGroup.LayoutParams(
                android.view.ViewGroup.LayoutParams.MATCH_PARENT,
                android.view.ViewGroup.LayoutParams.WRAP_CONTENT));
        LinearLayout.LayoutParams scLp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, 0, 1f);
        scLp.topMargin = (int) (14 * d);
        root.addView(scroller, scLp);

        // SELECTION MODE bottom bar: Delete + Cancel for bulk deleting.
        LinearLayout actionBar = new LinearLayout(act);
        actionBar.setOrientation(LinearLayout.HORIZONTAL);
        actionBar.setGravity(Gravity.CENTER_VERTICAL + Gravity.RIGHT);
        android.graphics.drawable.GradientDrawable abBg = new android.graphics.drawable.GradientDrawable();
        abBg.setColor(Color.parseColor("#14141A"));
        abBg.setCornerRadius(14 * d);
        abBg.setStroke(1, Color.parseColor("#2A2A30"));
        actionBar.setBackgroundDrawable(abBg);
        actionBar.setPadding((int) (14 * d), (int) (10 * d), (int) (14 * d), (int) (10 * d));
        LinearLayout.LayoutParams abLp = new LinearLayout.LayoutParams(-1, -2);
        abLp.topMargin = (int) (10 * d);
        actionBar.setVisibility(View.GONE);
        root.addView(actionBar, abLp);
        st.actionBar = actionBar;

        Button bulkDelete = new Button(act);
        bulkDelete.setAllCaps(false);
        bulkDelete.setTextColor(Color.WHITE);
        bulkDelete.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        bulkDelete.setBackgroundDrawable(rounded(C_RED, 12f * d));
        bulkDelete.setPadding((int) (20 * d), 0, (int) (20 * d), 0);
        bulkDelete.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { bulkDeleteSelected(st); }
        });
        actionBar.addView(bulkDelete, new LinearLayout.LayoutParams(-2, (int) (40 * d)));
        st.deleteBtn = bulkDelete;

        Button bulkCancel = new Button(act);
        bulkCancel.setAllCaps(false);
        bulkCancel.setTextColor(Color.parseColor(C_SOFT));
        bulkCancel.setBackgroundDrawable(rounded("#00000000", 0f));
        bulkCancel.setPadding((int) (14 * d), 0, (int) (4 * d), 0);
        bulkCancel.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                st.selectMode = false;
                st.selected.clear();
                render(st);
            }
        });
        LinearLayout.LayoutParams bcLp = new LinearLayout.LayoutParams(-2, (int) (40 * d));
        bcLp.leftMargin = (int) (8 * d);
        actionBar.addView(bulkCancel, bcLp);

        st.list = listHost;

        st.empty = new TextView(act);
        st.empty.setTextColor(Color.parseColor(C_DIM));
        st.empty.setTextSize(14);
        st.empty.setGravity(Gravity.CENTER);
        LinearLayout.LayoutParams ep = new LinearLayout.LayoutParams(-1, -2);
        ep.topMargin = (int) (40 * d);
        listHost.addView(st.empty, ep);

        styleTabs(st);
        act.setContentView(root);
        st.mainRoot = root;
        st.mainList = listHost;

        // Live refresh (1s) while the screen is open: storage line + the cards.
        // Cards are rebuilt in place, posters come from the bitmap cache.
        final Handler h = new Handler();
        h.post(new Runnable() {
            @Override public void run() {
                if (act.isFinishing()) return;
                // storage line follows the active page (main or series)
                if (st.seriesName == null) {
                    refreshStorage(act, storage);
                } else if (st.seriesStorage != null) {
                    refreshStorage(act, st.seriesStorage);
                }
                render(st);
                h.postDelayed(this, 1000);
            }
        });
    }

    // =======================================================================
    //  Small widgets
    // =======================================================================
    private static TextView tabLabel(Activity act, String text) {
        float d = act.getResources().getDisplayMetrics().density;
        TextView t = new TextView(act);
        t.setText(text);
        t.setTextSize(15);
        t.setGravity(Gravity.CENTER);
        t.setPadding(0, (int) (6 * d), 0, 0);
        return t;
    }

    private static View tabLine(Activity act) {
        float d = act.getResources().getDisplayMetrics().density;
        View v = new View(act);
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, (int) (3 * d));
        lp.topMargin = (int) (8 * d);
        v.setLayoutParams(lp);
        return v;
    }

    private static LinearLayout tabBox(Activity act, TextView label, View line) {
        LinearLayout box = new LinearLayout(act);
        box.setOrientation(LinearLayout.VERTICAL);
        box.addView(label, new LinearLayout.LayoutParams(-1, -2));
        box.addView(line);
        return box;
    }

    private static Button mkBtn(Activity act, String label, boolean bold, boolean red, float d) {
        Button b = new Button(act);
        b.setText(label);
        b.setAllCaps(false);
        if (red) {
            b.setTextColor(Color.WHITE);
            if (bold) b.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
            b.setBackgroundDrawable(rounded(C_RED, 10f * d));
            b.setPadding((int) (22 * d), 0, (int) (22 * d), 0);
        } else {
            b.setTextColor(Color.parseColor(C_SOFT));
            b.setBackgroundDrawable(rounded("#00000000", 0f));
        }
        return b;
    }

    private static GradientDrawable rounded(String color, float radius) {
        GradientDrawable g = new GradientDrawable();
        g.setColor(Color.parseColor(color));
        g.setCornerRadius(radius);
        return g;
    }

    private static void styleTabs(State85 st) {
        int on = Color.WHITE;
        int off = Color.parseColor(C_DIM);
        int red = Color.parseColor(C_RED);
        boolean first = st.tab == 0;
        st.tabDlTxt.setTextColor(first ? on : off);
        st.tabDlTxt.setTypeface(first ? android.graphics.Typeface.DEFAULT_BOLD : android.graphics.Typeface.DEFAULT);
        st.tabDlLine.setBackgroundColor(first ? red : Color.TRANSPARENT);
        st.tabDoneTxt.setTextColor(first ? off : on);
        st.tabDoneTxt.setTypeface(first ? android.graphics.Typeface.DEFAULT : android.graphics.Typeface.DEFAULT_BOLD);
        st.tabDoneLine.setBackgroundColor(first ? Color.TRANSPARENT : red);
        // the searchbar exists only on the Downloaded tab
        if (st.search != null) {
            st.search.setVisibility(first ? View.GONE : View.VISIBLE);
            if (first && st.query.length() > 0) {
                st.query = "";
                st.search.setText("");
            }
        }
    }

    // =======================================================================
    //  Storage line
    // =======================================================================
    private static void refreshStorage(Activity act, TextView tv) {
        try {
            StatFs stat = new StatFs(Environment.getExternalStorageDirectory().getPath());
            long free = stat.getAvailableBlocksLong() * stat.getBlockSizeLong();
            tv.setText("Internal storage  " + humanSize(free) + " remaining");
            tv.setTextColor(Color.parseColor("#9A9A9A"));
        } catch (Exception e) {
            tv.setText("");
        }
    }

    // =======================================================================
    //  The list
    // =======================================================================
    private static class Row85 {
        String kind;     // "dm" or "eng"
        long dmId;
        String rowId;
        String title;
        String poster;
        String subName;
        int status;
        long done;
        long total;
        String reason;
        String msg;
        int est;
        String series;   // series name when the title is "... epN", else null
        int ep;
    }

    private static void render(State85 st) {
        if (st.seriesName != null) { renderSeriesPage(st); return; }
        renderMain(st);
    }

    // All registry rows (DownloadManager legacy + fast engine), newest last.
    private static java.util.ArrayList<Row85> collectRows(State85 st) {
        java.util.ArrayList<Row85> rows = new java.util.ArrayList<Row85>();
        try {
            DownloadManager dm = (DownloadManager) st.act.getSystemService(Context.DOWNLOAD_SERVICE);
            Cursor c = dm.query(new DownloadManager.Query());
            if (c != null) {
                while (c.moveToNext() && rows.size() < 80) {
                    Row85 r = new Row85();
                    r.kind = "dm";
                    r.dmId = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_ID));
                    r.status = c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));
                    r.done = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));
                    r.total = c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));
                    try { r.reason = c.getString(c.getColumnIndexOrThrow(DownloadManager.COLUMN_REASON)); } catch (Exception eR) { }
                    String[] meta = readMeta(st.act, r.dmId);
                    r.title = meta[0] == null ? "" : meta[0];
                    if (r.title.length() == 0) r.title = "Download";
                    r.poster = meta[1] == null ? "" : meta[1];
                    r.subName = meta[2] == null ? "" : meta[2];
                    r.series = seriesOf(r.title);
                    r.ep = episodeNumOf(r.title);
                    rows.add(r);
                }
                c.close();
            }
        } catch (Exception e) { }
        try {
            java.util.ArrayList<String> ids = DlSpeed85.engineRowIds(st.act);
            for (int i = 0; i < ids.size() && rows.size() < 100; i++) {
                Row85 r = new Row85();
                r.kind = "eng";
                r.rowId = ids.get(i);
                r.est = DlSpeed85.statusOf(r.rowId);
                String[] meta = DlSpeed85.readRow(st.act, r.rowId);
                r.title = meta[0].length() == 0 ? "Download" : meta[0];
                r.poster = meta[1];
                r.subName = meta[3];
                // episode sub-title for the card (index 6 = [NAME])
                if (meta.length > 6 && meta[6] != null && meta[6].length() > 0) {
                    STATE_NAME_CACHE.put(r.title.toLowerCase(java.util.Locale.US), meta[6]);
                }
                long[] pg = DlSpeed85.progressOf(r.rowId);
                r.done = pg[0];
                r.total = pg[1];
                r.msg = DlSpeed85.msgOf(r.rowId);
                r.series = seriesOf(r.title);
                r.ep = episodeNumOf(r.title);
                rows.add(r);
            }
        } catch (Exception e2) { }
        return rows;
    }

    private static void renderMain(State85 st) {
        if (st.list == null) return;
        st.list.removeAllViews();
        java.util.ArrayList<Row85> rows = collectRows(st);

        // ---- search filter -------------------------------------------
        java.util.ArrayList<Row85> visible = new java.util.ArrayList<Row85>();
        for (int i = 0; i < rows.size(); i++) {
            Row85 r = rows.get(i);
            boolean finished = (r.kind.equals("dm"))
                    ? r.status == DownloadManager.STATUS_SUCCESSFUL
                    : r.est == DlSpeed85.ST_DONE;
            if (st.tab == 0 && finished) continue;
            if (st.tab == 1 && !finished) continue;
            if (!matchesQuery(r.title, st.query)) continue;
            visible.add(r);
        }

        int shown = 0;
        if (st.tab == 1) {
            // ---- DOWNLOADED tab: group series into folders -------------
            assignImplicitEp1(visible);

            java.util.LinkedHashMap<String, java.util.ArrayList<Row85>> groups =
                    new java.util.LinkedHashMap<String, java.util.ArrayList<Row85>>();
            java.util.ArrayList<Row85> movies = new java.util.ArrayList<Row85>();
            for (int i = 0; i < visible.size(); i++) {
                Row85 r = visible.get(i);
                if (r.series != null) {
                    java.util.ArrayList<Row85> g = groups.get(r.series);
                    if (g == null) {
                        g = new java.util.ArrayList<Row85>();
                        groups.put(r.series, g);
                    }
                    g.add(r);
                } else {
                    movies.add(r);
                }
            }
            // movies first (newest first), then series folders
            for (int i = movies.size() - 1; i >= 0 && shown < 40; i--) {
                shown++;
                addRowCard(st, movies.get(i));
            }
            for (java.util.Map.Entry<String, java.util.ArrayList<Row85>> en : groups.entrySet()) {
                if (shown >= 40) break;
                java.util.ArrayList<Row85> eps = en.getValue();
                // newest episode first inside each group
                java.util.Collections.sort(eps, new java.util.Comparator<Row85>() {
                    @Override public int compare(Row85 a, Row85 b) {
                        return b.ep - a.ep;
                    }
                });
                shown++;
                addSeriesFolder(st, en.getKey(),
                        eps.get(0).poster, eps.size(), eps);
            }
        } else {
            // ---- DOWNLOADING tab: flat list, newest first --------------
            for (int i = visible.size() - 1; i >= 0 && shown < 40; i--) {
                shown++;
                addRowCard(st, visible.get(i));
            }
        }

        // selection bar state: visible only with something selected
        if (st.actionBar != null) {
            boolean barOn = st.selectMode && !st.selected.isEmpty();
            st.actionBar.setVisibility(barOn ? View.VISIBLE : View.GONE);
            if (st.deleteBtn != null) {
                st.deleteBtn.setText("Delete (" + String.valueOf(st.selected.size()) + ")");
            }
        }

        if (st.empty != null) {
            boolean searching = st.query.length() > 0;
            st.empty.setText(searching
                    ? "No downloads match \"" + st.query + "\"."
                    : (st.tab == 0
                        ? "No downloads in progress.\nStart one from any movie page."
                        : "Nothing downloaded yet.\nOpen any movie and tap the download button."));
            st.empty.setVisibility(shown > 0 ? View.GONE : View.VISIBLE);
        }
    }

    // One row (movie card or one episode inside an expanded folder)
    private static void addRowCard(State85 st, Row85 r) {
        if (r.kind.equals("dm")) {
            addCard(st, r.dmId, r.title, r.poster, r.subName, r.status,
                    r.done, r.total, r.reason == null ? "" : r.reason);
        } else {
            addEngineCard(st, r.rowId, r.title, r.poster, r.subName,
                    r.est, r.done, r.total, r.msg == null ? "" : r.msg);
        }
    }

    // A title with NO episode marker ("The Ordinary Jackpot") counts as
    // EPISODE 1 when other rows of the same series exist. The site only
    // stamps "ep1" when you CLICK ep1; the auto-played first episode
    // downloads without the marker, which used to strand it outside the
    // folder. Runs on every list that groups or shows a series.
    private static void assignImplicitEp1(java.util.ArrayList<Row85> rows) {
        java.util.ArrayList<String> presentSeries = new java.util.ArrayList<String>();
        for (int i = 0; i < rows.size(); i++) {
            Row85 r = rows.get(i);
            if (r.series != null && presentSeries.indexOf(r.series) < 0) presentSeries.add(r.series);
        }
        for (int i = 0; i < rows.size(); i++) {
            Row85 r = rows.get(i);
            if (r.series != null) continue;
            if (r.ep > 0) continue;
            for (int k = 0; k < presentSeries.size(); k++) {
                if (seriesKeyOf(r.title).equalsIgnoreCase(presentSeries.get(k))) {
                    r.series = presentSeries.get(k);
                    r.ep = 1;
                    break;
                }
            }
        }
    }

    // =======================================================================
    //  SERIES PAGE (LokLok style): dedicated screen with back arrow +
    //  centered series title + Edit on the right, storage line, a
    //  "Download more" button, and the episode list. Replaces the old
    //  inline dropdown.
    // =======================================================================
    private static void openSeriesPage(final State85 st, final String name) {
        final Activity act = st.act;
        final float d = st.d;

        LinearLayout page = new LinearLayout(act);
        page.setOrientation(LinearLayout.VERTICAL);
        page.setBackgroundColor(Color.parseColor(C_BG));
        page.setPadding((int) (18 * d), (int) (14 * d), (int) (18 * d), (int) (14 * d));

        // -- header: back arrow, centered title, Edit on the right --------
        LinearLayout headRow = new LinearLayout(act);
        headRow.setOrientation(LinearLayout.HORIZONTAL);
        headRow.setGravity(Gravity.CENTER_VERTICAL);
        TextView back = new TextView(act);
        back.setText("<");
        back.setTextColor(Color.WHITE);
        back.setTextSize(20);
        back.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        back.setPadding(0, (int) (6 * d), (int) (12 * d), (int) (6 * d));
        headRow.addView(back, new LinearLayout.LayoutParams(-2, -2));
        TextView title = new TextView(act);
        title.setText(name);
        title.setTextColor(Color.WHITE);
        title.setTextSize(18);
        title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        title.setSingleLine(true);
        title.setEllipsize(android.text.TextUtils.TruncateAt.END);
        title.setGravity(Gravity.CENTER);
        headRow.addView(title, new LinearLayout.LayoutParams(0, -2, 1f));
        TextView edit = new TextView(act);
        edit.setText("Edit");
        edit.setTextColor(Color.WHITE);
        edit.setTextSize(15);
        edit.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        edit.setPadding((int) (12 * d), (int) (6 * d), 0, (int) (6 * d));
        headRow.addView(edit, new LinearLayout.LayoutParams(-2, -2));
        page.addView(headRow, new LinearLayout.LayoutParams(-1, -2));

        // -- storage line --------------------------------------------------
        final TextView storage2 = new TextView(act);
        storage2.setTextSize(13);
        storage2.setPadding(0, (int) (8 * d), 0, (int) (2 * d));
        page.addView(storage2, new LinearLayout.LayoutParams(-1, -2));
        st.seriesStorage = storage2;

        // -- "Download more" button: back to the app browser, where the
        //    series page offers the Download button (episode checklist).
        TextView more = new TextView(act);
        more.setText((char) 0x2295 + "   Download more");
        more.setTextColor(Color.WHITE);
        more.setTextSize(15);
        more.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        more.setGravity(Gravity.CENTER);
        android.graphics.drawable.GradientDrawable moreBg = new android.graphics.drawable.GradientDrawable();
        moreBg.setColor(Color.parseColor("#14141A"));
        moreBg.setCornerRadius(12 * d);
        moreBg.setStroke(1, Color.parseColor("#2A2A30"));
        more.setBackgroundDrawable(moreBg);
        more.setPadding(0, (int) (12 * d), 0, (int) (12 * d));
        more.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { closeSeriesPage(st); act.finish(); }
        });
        LinearLayout.LayoutParams moreLp = new LinearLayout.LayoutParams(-1, -2);
        moreLp.topMargin = (int) (10 * d);
        page.addView(more, moreLp);

        // -- episode list (scrollable) --------------------------------------
        android.widget.ScrollView sc = new android.widget.ScrollView(act);
        sc.setFillViewport(true);
        LinearLayout listHost = new LinearLayout(act);
        listHost.setOrientation(LinearLayout.VERTICAL);
        sc.addView(listHost, new android.view.ViewGroup.LayoutParams(
                android.view.ViewGroup.LayoutParams.MATCH_PARENT,
                android.view.ViewGroup.LayoutParams.WRAP_CONTENT));
        LinearLayout.LayoutParams scLp = new LinearLayout.LayoutParams(
                -1, 0, 1f);
        scLp.topMargin = (int) (6 * d);
        page.addView(sc, scLp);

        // -- selection bottom bar (Delete / Cancel) for this page -----------
        LinearLayout bar = new LinearLayout(act);
        bar.setOrientation(LinearLayout.HORIZONTAL);
        bar.setGravity(Gravity.CENTER_VERTICAL + Gravity.RIGHT);
        android.graphics.drawable.GradientDrawable barBg = new android.graphics.drawable.GradientDrawable();
        barBg.setColor(Color.parseColor("#14141A"));
        barBg.setCornerRadius(14 * d);
        barBg.setStroke(1, Color.parseColor("#2A2A30"));
        bar.setBackgroundDrawable(barBg);
        bar.setPadding((int) (14 * d), (int) (10 * d), (int) (14 * d), (int) (10 * d));
        LinearLayout.LayoutParams barLp = new LinearLayout.LayoutParams(-1, -2);
        barLp.topMargin = (int) (10 * d);
        bar.setVisibility(View.GONE);
        page.addView(bar, barLp);
        st.seriesBar = bar;

        Button sdel = new Button(act);
        sdel.setAllCaps(false);
        sdel.setTextColor(Color.WHITE);
        sdel.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        sdel.setBackgroundDrawable(rounded(C_RED, 12f * d));
        sdel.setPadding((int) (20 * d), 0, (int) (20 * d), 0);
        sdel.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { bulkDeleteSelected(st); }
        });
        bar.addView(sdel, new LinearLayout.LayoutParams(-2, (int) (40 * d)));
        st.seriesDeleteBtn = sdel;

        Button scan = new Button(act);
        scan.setAllCaps(false);
        scan.setTextColor(Color.parseColor(C_SOFT));
        scan.setBackgroundDrawable(rounded("#00000000", 0f));
        scan.setPadding((int) (14 * d), 0, (int) (4 * d), 0);
        scan.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                st.selectMode = false;
                st.selected.clear();
                render(st);
            }
        });
        LinearLayout.LayoutParams scanLp = new LinearLayout.LayoutParams(-2, (int) (40 * d));
        scanLp.leftMargin = (int) (8 * d);
        bar.addView(scan, scanLp);

        // back arrow exits the series page; the hardware BACK key does the
        // same (the focused page view consumes the key so the activity is
        // not finished while a series page is open).
        page.setFocusableInTouchMode(true);
        page.setFocusable(true);
        page.setOnKeyListener(new View.OnKeyListener() {
            @Override public boolean onKey(View v, int keyCode, android.view.KeyEvent ev) {
                if (keyCode == android.view.KeyEvent.KEYCODE_BACK
                        && ev.getAction() == android.view.KeyEvent.ACTION_UP) {
                    closeSeriesPage(st);
                    return true;
                }
                return false;
            }
        });
        back.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { closeSeriesPage(st); }
        });
        // Edit selects every episode of this series at once
        edit.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                st.selectMode = true;
                st.selected.clear();
                java.util.ArrayList<Row85> eps = seriesEpisodes(st, st.seriesName);
                for (int i = 0; i < eps.size(); i++) st.selected.add(keyOf(eps.get(i)));
                render(st);
            }
        });

        st.seriesName = name;
        st.list = listHost;
        act.setContentView(page);
        render(st);
    }

    private static void closeSeriesPage(State85 st) {
        st.seriesName = null;
        st.seriesStorage = null;
        st.seriesBar = null;
        st.seriesDeleteBtn = null;
        st.selectMode = false;
        st.selected.clear();
        st.list = st.mainList;
        st.act.setContentView(st.mainRoot);
        render(st);
    }

    // Every FINISHED row belonging to the given series (ep 1..N order).
    private static java.util.ArrayList<Row85> seriesEpisodes(State85 st, String name) {
        java.util.ArrayList<Row85> out = new java.util.ArrayList<Row85>();
        if (name == null) return out;
        java.util.ArrayList<Row85> rows = collectRows(st);
        assignImplicitEp1(rows);
        for (int i = 0; i < rows.size(); i++) {
            Row85 r = rows.get(i);
            if (r.series == null) continue;
            if (!r.series.equals(name)) continue;
            boolean finished = r.kind.equals("dm")
                    ? r.status == DownloadManager.STATUS_SUCCESSFUL
                    : r.est == DlSpeed85.ST_DONE;
            if (finished) out.add(r);
        }
        java.util.Collections.sort(out, new java.util.Comparator<Row85>() {
            @Override public int compare(Row85 a, Row85 b) { return a.ep - b.ep; }
        });
        return out;
    }

    // The series page list: every episode of st.seriesName (finished or not),
    // Episode 1 first, like the LokLok reference.
    private static void renderSeriesPage(State85 st) {
        if (st.list == null) return;
        st.list.removeAllViews();
        String name = st.seriesName;
        if (name == null) return;
        java.util.ArrayList<Row85> eps = new java.util.ArrayList<Row85>();
        java.util.ArrayList<Row85> rows = collectRows(st);
        assignImplicitEp1(rows);
        for (int i = 0; i < rows.size(); i++) {
            Row85 r = rows.get(i);
            if (r.series != null && r.series.equals(name)) eps.add(r);
        }
        java.util.Collections.sort(eps, new java.util.Comparator<Row85>() {
            @Override public int compare(Row85 a, Row85 b) { return a.ep - b.ep; }
        });
        for (int i = 0; i < eps.size() && i < 40; i++) {
            addRowCard(st, eps.get(i));
        }

        // selection bar on the series page mirrors the main one
        if (st.seriesBar != null) {
            boolean barOn = st.selectMode && !st.selected.isEmpty();
            st.seriesBar.setVisibility(barOn ? View.VISIBLE : View.GONE);
            if (st.seriesDeleteBtn != null) {
                st.seriesDeleteBtn.setText("Delete (" + String.valueOf(st.selected.size()) + ")");
            }
        }
    }

    // A series folder: poster + "Series Name" + "N episodes", tap opens the
    // dedicated series page (LokLok style).
    private static void addSeriesFolder(State85 st, final String name,
            final String poster, final int count, final java.util.ArrayList<Row85> eps) {
        Activity act = st.act;
        final float d = st.d;

        LinearLayout card = new LinearLayout(act);
        card.setOrientation(LinearLayout.HORIZONTAL);
        card.setGravity(Gravity.CENTER_VERTICAL);
        card.setClickable(true);
        card.setFocusable(true);
        android.graphics.drawable.GradientDrawable bg =
                new android.graphics.drawable.GradientDrawable();
        bg.setColor(Color.parseColor("#14141A"));
        bg.setCornerRadius(12 * d);
        card.setBackgroundDrawable(bg);
        int pad = (int) (10 * d);
        card.setPadding(pad, pad, pad, pad);
        LinearLayout.LayoutParams cp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        cp.topMargin = (int) (12 * d);
        st.list.addView(card, cp);

        ImageView thumb = new ImageView(act);
        LinearLayout.LayoutParams tp = new LinearLayout.LayoutParams(
                (int) (64 * d), (int) (92 * d));
        tp.rightMargin = (int) (14 * d);
        thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);
        thumb.setBackgroundDrawable(rounded(C_POSTER_BG, 8f * d));
        card.addView(thumb, tp);
        loadPoster(act, thumb, poster, (int) (64 * d), (int) (92 * d));

        LinearLayout right = new LinearLayout(act);
        right.setOrientation(LinearLayout.VERTICAL);
        card.addView(right, new LinearLayout.LayoutParams(-1, -2, 1f));

        TextView t = new TextView(act);
        t.setText(name);
        t.setTextColor(Color.WHITE);
        t.setTextSize(16);
        t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        t.setSingleLine(true);
        t.setEllipsize(android.text.TextUtils.TruncateAt.END);
        right.addView(t);

        TextView subT = new TextView(act);
        subT.setText(String.valueOf(count) + " episodes downloaded");
        subT.setTextColor(Color.parseColor(C_DIM));
        subT.setTextSize(13);
        right.addView(subT);

        TextView chev = new TextView(act);
        chev.setText(String.valueOf((char) 0x203A));
        chev.setTextColor(Color.parseColor(C_DIM));
        chev.setTextSize(22);
        chev.setPadding(0, 0, (int) (4 * d), 0);
        card.addView(chev, new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT));

        final String seriesTitle = name;
        card.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                openSeriesPage(st, seriesTitle);
            }
        });

        // SELECTION MODE: tapping the folder selects/deselects the WHOLE
        // series; long-press starts selection with everything in it.
        card.setOnLongClickListener(new View.OnLongClickListener() {
            @Override public boolean onLongClick(View v) {
                if (!st.selectMode) { st.selectMode = true; st.selected.clear(); }
                for (int i = 0; i < eps.size(); i++) st.selected.add(keyOf(eps.get(i)));
                render(st);
                return true;
            }
        });
        if (st.selectMode) {
            int selCount = 0;
            for (int i = 0; i < eps.size(); i++) {
                if (st.selected.contains(keyOf(eps.get(i)))) selCount++;
            }
            android.graphics.drawable.GradientDrawable selBg = new android.graphics.drawable.GradientDrawable();
            selBg.setColor(Color.parseColor("#14141A"));
            selBg.setCornerRadius(12 * d);
            if (selCount > 0) selBg.setStroke((int) (2 * d), Color.parseColor(C_RED));
            card.setBackgroundDrawable(selBg);
            card.setOnClickListener(new View.OnClickListener() {
                @Override public void onClick(View v) {
                    boolean anySel = false;
                    for (int i = 0; i < eps.size(); i++) {
                        if (st.selected.contains(keyOf(eps.get(i)))) { anySel = true; break; }
                    }
                    for (int i = 0; i < eps.size(); i++) {
                        String k = keyOf(eps.get(i));
                        if (anySel) st.selected.remove(k);
                        else st.selected.add(k);
                    }
                    render(st);
                }
            });
        }

    }

    private static void addCard(State85 st, final long id, final String title, final String poster, final String subName, final int status, final long done, final long total, final String reason) {
        Activity act = st.act;
        final float d = st.d;

        LinearLayout card = new LinearLayout(act);
        card.setOrientation(LinearLayout.HORIZONTAL);
        card.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams cp = new LinearLayout.LayoutParams(-1, -2);
        cp.topMargin = (int) (12 * d);
        st.list.addView(card, cp);

        ImageView thumb = new ImageView(act);
        LinearLayout.LayoutParams tp = new LinearLayout.LayoutParams((int) (104 * d), (int) (150 * d));
        tp.rightMargin = (int) (16 * d);
        thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);
        thumb.setBackgroundDrawable(rounded(C_POSTER_BG, 8f * d));
        card.addView(thumb, tp);
        loadPoster(act, thumb, poster, (int) (104 * d), (int) (150 * d));

        LinearLayout right = new LinearLayout(act);
        right.setOrientation(LinearLayout.VERTICAL);
        card.addView(right, new LinearLayout.LayoutParams(-1, -2, 1f));

        TextView t = new TextView(act);
        t.setText(title);
        t.setTextColor(Color.WHITE);
        t.setTextSize(16);
        t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        t.setSingleLine(true);
        t.setEllipsize(android.text.TextUtils.TruncateAt.END);
        right.addView(t);

        // EPISODE SUB-TITLE: episodes saved with a descriptive name show it
        // here in small dim text prefixed with "Sub-title" (e.g. under
        // "Crew Girl ep3" -> "Sub-title: The Crew Scandal").
        String subTitle = episodeSubTitleOf(title);
        if (subTitle.length() > 0) {
            TextView stv = new TextView(act);
            stv.setText("Sub-title: " + subTitle);
            stv.setTextColor(Color.parseColor("#8A8A92"));
            stv.setTextSize(11);
            stv.setSingleLine(true);
            stv.setEllipsize(android.text.TextUtils.TruncateAt.END);
            LinearLayout.LayoutParams stLp = new LinearLayout.LayoutParams(-1, -2);
            stLp.topMargin = (int) (2 * d);
            right.addView(stv, stLp);
        }

        TextView sub = new TextView(act);
        sub.setTextSize(14);
        boolean showBar = false;
        int pct = 0;
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            sub.setText("Downloaded");
            sub.setTextColor(Color.parseColor("#EDEDED"));
        } else if (status == DownloadManager.STATUS_FAILED) {
            // ERROR_INSUFFICIENT_SPACE arrives as the reason code "1006"
            boolean noSpace = String.valueOf(DownloadManager.ERROR_INSUFFICIENT_SPACE).equals(reason);
            sub.setText(noSpace ? "Insufficient Storage" : "Failed");
            sub.setTextColor(Color.parseColor(noSpace ? C_RED : C_BAD));
        } else if (status == DownloadManager.STATUS_PAUSED) {
            sub.setText("Paused");
            sub.setTextColor(Color.parseColor(C_DIM));
            if (total > 0) { pct = (int) (done * 100 / total); showBar = true; }
        } else if (status == DownloadManager.STATUS_PENDING) {
            sub.setText("Waiting...");
            sub.setTextColor(Color.parseColor(C_DIM));
        } else if (total > 0) {
            pct = (int) (done * 100 / total);
            sub.setText(humanSize(done) + " / " + humanSize(total) + speedText(String.valueOf(id), done));
            sub.setTextColor(Color.parseColor(C_DIM));
            showBar = true;
        } else {
            sub.setText("Starting..." + speedText(String.valueOf(id), done));
            sub.setTextColor(Color.parseColor(C_DIM));
        }
        LinearLayout.LayoutParams sp = new LinearLayout.LayoutParams(-1, -2);
        sp.topMargin = (int) (8 * d);
        right.addView(sub, sp);

        if (showBar) {
            ProgressBar bar = new ProgressBar(act, null, android.R.attr.progressBarStyleHorizontal);
            bar.setMax(100);
            bar.setProgress(pct);
            try {
                bar.getProgressDrawable().setColorFilter(Color.parseColor(C_RED), android.graphics.PorterDuff.Mode.SRC_IN);
            } catch (Exception e) { }
            LinearLayout.LayoutParams bp = new LinearLayout.LayoutParams(-1, (int) (3 * d));
            bp.topMargin = (int) (8 * d);
            right.addView(bar, bp);
        }

        LinearLayout row = new LinearLayout(act);
        row.setOrientation(LinearLayout.HORIZONTAL);
        // "+" instead of bitwise-or: this file must contain ZERO pipe chars
        row.setGravity(Gravity.RIGHT + Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams rp = new LinearLayout.LayoutParams(-1, -2);
        rp.topMargin = (int) (10 * d);
        right.addView(row, rp);

        LinearLayout.LayoutParams abp = new LinearLayout.LayoutParams(-2, -2);
        abp.leftMargin = (int) (18 * d);

        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            Button play = mkBtn(act, "Play", true, true, d);
            play.setOnClickListener(new Act85(st, 1, id, title, subName, status));
            row.addView(play, abp);
        } else if (status == DownloadManager.STATUS_FAILED) {
            Button retry = mkBtn(act, "Retry", false, true, d);
            retry.setOnClickListener(new Act85(st, 2, id, title, subName, status));
            row.addView(retry, abp);
        } else if (status == DownloadManager.STATUS_PAUSED) {
            // DownloadManager has NO resume() API, so a paused row offers a
            // restart instead (the file is re-fetched from the movie page).
            Button restart = mkBtn(act, "Restart", false, true, d);
            restart.setOnClickListener(new Act85(st, 2, id, title, subName, status));
            row.addView(restart, abp);
        } else {
            Button cancel = mkBtn(act, "Cancel", false, false, d);
            cancel.setOnClickListener(new Act85(st, 4, id, title, subName, status));
            row.addView(cancel, abp);
        }

        Button del = mkBtn(act, "Delete", false, false, d);
        del.setTextColor(Color.parseColor(C_BAD));
        del.setOnClickListener(new Act85(st, 5, id, title, subName, status));
        row.addView(del, abp);

        // SELECTION MODE: long-press enters selection; tap toggles the row.
        final String selKey = "D" + String.valueOf(id);
        card.setOnLongClickListener(new View.OnLongClickListener() {
            @Override public boolean onLongClick(View v) {
                if (!st.selectMode) { st.selectMode = true; st.selected.clear(); }
                st.selected.add(selKey);
                render(st);
                return true;
            }
        });
        if (st.selectMode) {
            card.setClickable(true);
            card.setFocusable(true);
            android.graphics.drawable.GradientDrawable selBg = new android.graphics.drawable.GradientDrawable();
            selBg.setCornerRadius(12 * d);
            if (st.selected.contains(selKey)) {
                selBg.setColor(Color.parseColor("#14141A"));
                selBg.setStroke((int) (2 * d), Color.parseColor(C_RED));
            }
            card.setBackgroundDrawable(selBg);
            card.setOnClickListener(new View.OnClickListener() {
                @Override public void onClick(View v) { toggleSelect(st, selKey); }
            });
        }
    }

    // =======================================================================
    //  Engine cards (fast 4-connection downloads)
    // =======================================================================
    private static void addEngineCard(State85 st, final String rowId, final String title,
            final String poster, final String subName, final int est, final long done,
            final long total, final String msg) {
        Activity act = st.act;
        final float d = st.d;

        LinearLayout card = new LinearLayout(act);
        card.setOrientation(LinearLayout.HORIZONTAL);
        card.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams cp = new LinearLayout.LayoutParams(-1, -2);
        cp.topMargin = (int) (12 * d);
        st.list.addView(card, cp);

        ImageView thumb = new ImageView(act);
        LinearLayout.LayoutParams tp = new LinearLayout.LayoutParams((int) (104 * d), (int) (150 * d));
        tp.rightMargin = (int) (16 * d);
        thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);
        thumb.setBackgroundDrawable(rounded(C_POSTER_BG, 8f * d));
        card.addView(thumb, tp);
        loadPoster(act, thumb, poster, (int) (104 * d), (int) (150 * d));

        LinearLayout right = new LinearLayout(act);
        right.setOrientation(LinearLayout.VERTICAL);
        card.addView(right, new LinearLayout.LayoutParams(-1, -2, 1f));

        TextView t = new TextView(act);
        t.setText(title);
        t.setTextColor(Color.WHITE);
        t.setTextSize(16);
        t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        t.setSingleLine(true);
        t.setEllipsize(android.text.TextUtils.TruncateAt.END);
        right.addView(t);

        // EPISODE SUB-TITLE: episodes saved with a descriptive name show it
        // here in small dim text prefixed with "Sub-title" (e.g. under
        // "Crew Girl ep3" -> "Sub-title: The Crew Scandal").
        String subTitle = episodeSubTitleOf(title);
        if (subTitle.length() > 0) {
            TextView stv = new TextView(act);
            stv.setText("Sub-title: " + subTitle);
            stv.setTextColor(Color.parseColor("#8A8A92"));
            stv.setTextSize(11);
            stv.setSingleLine(true);
            stv.setEllipsize(android.text.TextUtils.TruncateAt.END);
            LinearLayout.LayoutParams stLp = new LinearLayout.LayoutParams(-1, -2);
            stLp.topMargin = (int) (2 * d);
            right.addView(stv, stLp);
        }

        TextView sub = new TextView(act);
        sub.setTextSize(14);
        boolean showBar = false;
        int pct = 0;
        if (est == DlSpeed85.ST_DONE) {
            sub.setText("Downloaded");
            sub.setTextColor(Color.parseColor("#EDEDED"));
        } else if (est == DlSpeed85.ST_FAILED) {
            boolean noSpace = DlSpeed85.MSG_NOSPACE.equals(msg);
            boolean emptyMsg = msg == null;
            if (!emptyMsg) emptyMsg = msg.length() == 0;
            sub.setText(noSpace ? "Insufficient Storage" : (emptyMsg ? "Failed" : msg));
            sub.setTextColor(Color.parseColor(noSpace ? C_RED : C_BAD));
        } else if (est == DlSpeed85.ST_PENDING) {
            // queued behind the concurrency limit (Downloads settings)
            sub.setText("Pending...");
            sub.setTextColor(Color.parseColor(C_DIM));
        } else {
            // running: "Retrieving files..." while probing, then size + speed
            if (msg != null && msg.length() > 0) {
                sub.setText(msg);
            } else if (total > 0) {
                pct = (int) (done * 100 / total);
                sub.setText(humanSize(done) + " / " + humanSize(total) + speedText(rowId, done));
            } else {
                sub.setText(humanSize(done) + speedText(rowId, done));
            }
            sub.setTextColor(Color.parseColor(C_DIM));
            if (total > 0) showBar = true;
        }
        LinearLayout.LayoutParams sp = new LinearLayout.LayoutParams(-1, -2);
        sp.topMargin = (int) (8 * d);
        right.addView(sub, sp);

        if (showBar) {
            ProgressBar bar = new ProgressBar(act, null, android.R.attr.progressBarStyleHorizontal);
            bar.setMax(100);
            bar.setProgress(pct);
            try {
                bar.getProgressDrawable().setColorFilter(Color.parseColor(C_RED), android.graphics.PorterDuff.Mode.SRC_IN);
            } catch (Exception e) { }
            LinearLayout.LayoutParams bp = new LinearLayout.LayoutParams(-1, (int) (3 * d));
            bp.topMargin = (int) (8 * d);
            right.addView(bar, bp);
        }

        LinearLayout row = new LinearLayout(act);
        row.setOrientation(LinearLayout.HORIZONTAL);
        row.setGravity(Gravity.RIGHT + Gravity.CENTER_VERTICAL);
        LinearLayout.LayoutParams rp = new LinearLayout.LayoutParams(-1, -2);
        rp.topMargin = (int) (10 * d);
        right.addView(row, rp);

        LinearLayout.LayoutParams abp = new LinearLayout.LayoutParams(-2, -2);
        abp.leftMargin = (int) (18 * d);

        if (est == DlSpeed85.ST_DONE) {
            Button play = mkBtn(act, "Play", true, true, d);
            play.setOnClickListener(new Act85(st, 1, rowId, title, subName, 0));
            row.addView(play, abp);
        } else if (est == DlSpeed85.ST_FAILED) {
            Button retry = mkBtn(act, "Retry", false, true, d);
            retry.setOnClickListener(new Act85(st, 6, rowId, title, subName, 0));
            row.addView(retry, abp);
        } else {
            Button cancel = mkBtn(act, "Cancel", false, false, d);
            cancel.setOnClickListener(new Act85(st, 7, rowId, title, subName, 0));
            row.addView(cancel, abp);
        }

        Button del = mkBtn(act, "Delete", false, false, d);
        del.setTextColor(Color.parseColor(C_BAD));
        del.setOnClickListener(new Act85(st, 8, rowId, title, subName, 0));
        row.addView(del, abp);

        // SELECTION MODE: long-press enters selection; tap toggles the row.
        final String selKeyE = rowId;
        card.setOnLongClickListener(new View.OnLongClickListener() {
            @Override public boolean onLongClick(View v) {
                if (!st.selectMode) { st.selectMode = true; st.selected.clear(); }
                st.selected.add(selKeyE);
                render(st);
                return true;
            }
        });
        if (st.selectMode) {
            card.setClickable(true);
            card.setFocusable(true);
            android.graphics.drawable.GradientDrawable selBg = new android.graphics.drawable.GradientDrawable();
            selBg.setCornerRadius(12 * d);
            if (st.selected.contains(selKeyE)) {
                selBg.setColor(Color.parseColor("#14141A"));
                selBg.setStroke((int) (2 * d), Color.parseColor(C_RED));
            }
            card.setBackgroundDrawable(selBg);
            card.setOnClickListener(new View.OnClickListener() {
                @Override public void onClick(View v) { toggleSelect(st, selKeyE); }
            });
        }
    }

    // =======================================================================
    //  Live speed: bytes/sec measured between 1s screen refreshes
    // =======================================================================
    private static final HashMap<String, long[]> SPEED = new HashMap<String, long[]>();

    private static String speedText(String key, long done) {
        long now = SystemClock.elapsedRealtime();
        long[] s = SPEED.get(key);
        if (s == null) {
            // slot 0: last bytes, 1: last time, 2: ms stalled so far
            SPEED.put(key, new long[] { done, now, 0L });
            return "";
        }
        long dBytes = done - s[0];
        long dMs = now - s[1];
        s[0] = done;
        s[1] = now;
        if (dMs < 500) return "";  // first tick after (re)build
        if (dBytes < 0) return "";
        if (dBytes == 0) {
            // nothing moved this second: show "stalled" briefly, then nothing
            s[2] = s[2] + dMs;
            if (s[2] > 8000) return "";
            return "  (stalled)";
        }
        s[2] = 0;
        return "  " + humanSize((long) (dBytes * 1000.0 / dMs)) + "/s";
    }

    // =======================================================================
    //  Play an engine download (same landscape player, by class name)
    // =======================================================================
    private static void playEngine(Activity act, String rowId, String title, String subName) {
        try {
            String path = DlSpeed85.finalPath(rowId);
            boolean noFile = path == null;
            if (!noFile) noFile = path.length() == 0;
            if (noFile) {
                Toast.makeText(act, "File is gone -- delete this row and download again.", Toast.LENGTH_LONG).show();
                return;
            }
            Intent it = new Intent();
            it.putExtra("path", path);
            it.putExtra("title", title);
            if (subName != null && subName.length() > 0) it.putExtra("sub", subName);
            String[] names = { "com.deymflix.eu.cc.LocalplayerActivity", "com.deymflix.eu.cc.LocalPlayerActivity" };
            for (int i = 0; i < names.length; i++) {
                try {
                    it.setClassName(act, names[i]);
                    act.startActivity(it);
                    return;
                } catch (Exception e) { }
            }
            Toast.makeText(act, "Player activity not found -- check its name in Sketchware", Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            Toast.makeText(act, "Cannot open this download", Toast.LENGTH_SHORT).show();
        }
    }

    // =======================================================================
    //  Play a finished download inside the app (offline, landscape player)
    // =======================================================================
    private static void playDownload(Activity act, long id, String title, String subName) {
        try {
            DownloadManager dm = (DownloadManager) act.getSystemService(Context.DOWNLOAD_SERVICE);
            Cursor c = dm.query(new DownloadManager.Query().setFilterById(id));
            String path = "";
            String reason = "";
            if (c != null && c.moveToFirst()) {
                int status = c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));
                reason = c.getString(c.getColumnIndexOrThrow(DownloadManager.COLUMN_REASON));
                if (status == DownloadManager.STATUS_SUCCESSFUL) {
                    android.net.Uri u = dm.getUriForDownloadedFile(id);
                    if (u != null && u.getPath() != null) path = u.getPath();
                }
            }
            if (c != null) c.close();

            if (path.length() == 0) {
                String msg = "File is gone -- delete this row and download again.";
                if (reason != null && reason.length() > 0) msg = "Cannot play (code " + reason + "). Try downloading again.";
                Toast.makeText(act, msg, Toast.LENGTH_LONG).show();
                return;
            }

            Intent it = new Intent();
            it.putExtra("path", path);
            it.putExtra("title", title);
            if (subName != null && subName.length() > 0) it.putExtra("sub", subName);

            // Launched by class NAME so this file compiles no matter how the
            // activity is spelled in your project.
            String[] names = { "com.deymflix.eu.cc.LocalplayerActivity", "com.deymflix.eu.cc.LocalPlayerActivity" };
            for (int i = 0; i < names.length; i++) {
                try {
                    it.setClassName(act, names[i]);
                    act.startActivity(it);
                    return;
                } catch (Exception e) {
                    // try the next spelling
                }
            }
            Toast.makeText(act, "Player activity not found -- check its name in Sketchware", Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            Toast.makeText(act, "Cannot open this download", Toast.LENGTH_SHORT).show();
        }
    }

    // =======================================================================
    //  Delete: the file, the subtitle that traveled with it, the registry row
    // =======================================================================
    private static void deleteDownload(Activity act, long id, String subName, int status) {
        DownloadManager dm = (DownloadManager) act.getSystemService(Context.DOWNLOAD_SERVICE);
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            try {
                String local = dm.getUriForDownloadedFile(id).toString();
                new File(android.net.Uri.parse(local).getPath()).delete();
            } catch (Exception e) { }
            if (subName != null && subName.length() > 0) {
                try {
                    File dir = new File(act.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "Deymflix");
                    new File(dir, subName).delete();
                } catch (Exception e) { }
            }
        }
        try { dm.remove(id); } catch (Exception e) { }
        forgetMeta(act, id);
        if (status == DownloadManager.STATUS_SUCCESSFUL) {
            Toast.makeText(act, "Deleted", Toast.LENGTH_SHORT).show();
        }
    }

    // =======================================================================
    //  Registry helpers (same "deymflix_dl" preferences MainActivity writes)
    // =======================================================================
    private static String[] readMeta(Activity act, long id) {
        SharedPreferences p = act.getSharedPreferences("deymflix_dl", 0);
        String raw = p.getString(String.valueOf(id), "");
        if (raw == null) return new String[] { "", "", "" };
        if (raw.length() == 0) return new String[] { "", "", "" };
        String title = raw;
        String poster = "";
        String subName = "";
        int cutSub = raw.indexOf("[SUB]");
        if (cutSub >= 0) {
            subName = raw.substring(cutSub + 5);
            raw = raw.substring(0, cutSub);
        }
        int cutPoster = raw.indexOf("[POSTER]");
        if (cutPoster >= 0) {
            poster = raw.substring(cutPoster + 8);
            title = raw.substring(0, cutPoster);
        }
        return new String[] { title, poster, subName };
    }

    private static void forgetMeta(Activity act, long id) {
        SharedPreferences p = act.getSharedPreferences("deymflix_dl", 0);
        p.edit().remove(String.valueOf(id)).apply();
    }

    // =======================================================================
    //  DOWNLOAD SETTINGS dialog: how many downloads run at once (1 / 2 / 3).
    //  Dark card matching the other DEYMFLIX dialogs. Also carries the
    //  bulk-select tip.
    // =======================================================================
    private static void showSettingsDialog(final State85 st) {
        final Activity act = st.act;
        final float d = st.d;
        final android.app.Dialog dlg = new android.app.Dialog(act);
        dlg.requestWindowFeature(android.view.Window.FEATURE_NO_TITLE);
        dlg.setCanceledOnTouchOutside(true);

        LinearLayout card = new LinearLayout(act);
        card.setOrientation(LinearLayout.VERTICAL);
        android.graphics.drawable.GradientDrawable cbg = new android.graphics.drawable.GradientDrawable();
        cbg.setColor(Color.parseColor("#141418"));
        cbg.setCornerRadius(22 * d);
        cbg.setStroke(1, Color.parseColor("#2A2A30"));
        card.setBackgroundDrawable(cbg);
        int pad = (int) (20 * d);
        card.setPadding(pad, pad, pad, pad);

        TextView title = new TextView(act);
        title.setText("Download settings");
        title.setTextColor(Color.WHITE);
        title.setTextSize(18);
        title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        card.addView(title);

        TextView sub = new TextView(act);
        sub.setText("Max Downloads");
        sub.setTextColor(Color.parseColor(C_DIM));
        sub.setTextSize(13);
        LinearLayout.LayoutParams subLp = new LinearLayout.LayoutParams(-1, -2);
        subLp.topMargin = (int) (14 * d);
        card.addView(sub, subLp);

        final TextView[] optBtns = new TextView[3];
        for (int i = 0; i < 3; i++) {
            final int n = i + 1;
            // checkbox row: [ 1 ]  [ 2 ]  [ 3 ]  -- square boxes, red = on
            LinearLayout row = new LinearLayout(act);
            row.setOrientation(LinearLayout.HORIZONTAL);
            row.setGravity(Gravity.CENTER_VERTICAL);
            row.setClickable(true);
            row.setFocusable(true);
            row.setPadding((int) (6 * d), (int) (7 * d), (int) (6 * d), (int) (7 * d));
            TextView box = new TextView(act);
            box.setTextSize(13);
            box.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
            box.setGravity(Gravity.CENTER);
            LinearLayout.LayoutParams bLp = new LinearLayout.LayoutParams((int) (26 * d), (int) (26 * d));
            bLp.rightMargin = (int) (12 * d);
            row.addView(box, bLp);
            TextView lbl = new TextView(act);
            lbl.setText(String.valueOf(n));
            lbl.setTextColor(Color.WHITE);
            lbl.setTextSize(14);
            lbl.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
            row.addView(lbl, new LinearLayout.LayoutParams(-2, -2));
            LinearLayout.LayoutParams oLp = new LinearLayout.LayoutParams(-1, -2);
            oLp.topMargin = (int) (6 * d);
            card.addView(row, oLp);
            optBtns[i] = box;
            row.setOnClickListener(new View.OnClickListener() {
                @Override public void onClick(View v) {
                    DlSpeed85.setMaxConcurrent(act, n);
                    styleSettingsOptions(st, optBtns);
                    Toast.makeText(act, "Max downloads: " + n, Toast.LENGTH_SHORT).show();
                }
            });
        }
        styleSettingsOptions(st, optBtns);

        TextView tip = new TextView(act);
        tip.setText("Tip: press and hold a download to select several, then delete them all at once.");
        tip.setTextColor(Color.parseColor("#8A8A92"));
        tip.setTextSize(12);
        LinearLayout.LayoutParams tipLp = new LinearLayout.LayoutParams(-1, -2);
        tipLp.topMargin = (int) (14 * d);
        card.addView(tip, tipLp);

        // build tag, bottom corner: which library build the running app has
        TextView ver = new TextView(act);
        ver.setText("build " + LIB_BUILD);
        ver.setTextColor(Color.parseColor("#55555C"));
        ver.setTextSize(10);
        LinearLayout.LayoutParams verLp = new LinearLayout.LayoutParams(-2, -2);
        verLp.topMargin = (int) (8 * d);
        verLp.gravity = Gravity.CENTER_HORIZONTAL;
        card.addView(ver, verLp);

        TextView done = new TextView(act);
        done.setText("DONE");
        done.setTextColor(Color.WHITE);
        done.setTextSize(14);
        done.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        done.setGravity(Gravity.CENTER);
        done.setBackgroundDrawable(rounded(C_RED, 12f * d));
        done.setPadding(0, (int) (11 * d), 0, (int) (11 * d));
        done.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) { dlg.dismiss(); }
        });
        LinearLayout.LayoutParams doneLp = new LinearLayout.LayoutParams(-1, (int) (42 * d));
        doneLp.topMargin = (int) (16 * d);
        card.addView(done, doneLp);

        dlg.setContentView(card, new android.view.ViewGroup.LayoutParams(
                (int) (act.getResources().getDisplayMetrics().widthPixels * 0.84f),
                android.view.ViewGroup.LayoutParams.WRAP_CONTENT));
        dlg.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT));
        dlg.show();
    }

    // Highlights the option matching the current limit (red) and dims the rest.
    // Checkbox squares: the chosen count gets a filled red box with a white
    // check; the others stay dark and empty.
    private static void styleSettingsOptions(State85 st, TextView[] optBtns) {
        int cur = DlSpeed85.getMaxConcurrent(st.act);
        for (int i = 0; i < optBtns.length; i++) {
            TextView box = optBtns[i];
            if (box == null) continue;
            android.graphics.drawable.GradientDrawable g = new android.graphics.drawable.GradientDrawable();
            g.setCornerRadius(6 * st.d);
            if (i + 1 == cur) {
                g.setColor(Color.parseColor(C_RED));
                box.setTextColor(Color.WHITE);
                box.setText(String.valueOf((char) 0x2713));
            } else {
                g.setColor(Color.parseColor("#1E1E24"));
                g.setStroke(1, Color.parseColor("#2A2A30"));
                box.setTextColor(Color.TRANSPARENT);
                box.setText(String.valueOf((char) 0x2713));
            }
            box.setBackgroundDrawable(g);
        }
    }

    // =======================================================================
    //  SELECTION MODE helpers (bulk delete)
    // =======================================================================
    private static void toggleSelect(State85 st, String key) {
        if (st.selected.contains(key)) st.selected.remove(key);
        else st.selected.add(key);
        render(st);
    }

    // Stable identity of a row card for the selection set.
    private static String keyOf(Row85 r) {
        return r.kind.equals("eng") ? r.rowId : ("D" + String.valueOf(r.dmId));
    }

    private static void bulkDeleteSelected(State85 st) {
        int n = st.selected.size();
        for (String key : new java.util.ArrayList<String>(st.selected)) {
            if (key.startsWith("D")) {
                try { deleteDownloadQuiet(st.act, Long.parseLong(key.substring(1))); } catch (Exception e) { }
            } else {
                DlSpeed85.deleteRow(st.act, key);
            }
        }
        st.selected.clear();
        st.selectMode = false;
        Toast.makeText(st.act, "Deleted " + String.valueOf(n)
                + (n == 1 ? " download" : " downloads"), Toast.LENGTH_SHORT).show();
        render(st);
    }

    // Quiet per-row delete for bulk mode (single summary toast instead of one
    // per row). Removes the movie, its sidecar subtitle and the registry row.
    private static void deleteDownloadQuiet(Activity act, long id) {
        DownloadManager dm = (DownloadManager) act.getSystemService(Context.DOWNLOAD_SERVICE);
        String subName = "";
        Cursor c = dm.query(new DownloadManager.Query().setFilterById(id));
        if (c != null && c.moveToFirst()) {
            try {
                int status = c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));
                if (status == DownloadManager.STATUS_SUCCESSFUL) {
                    String[] meta = readMeta(act, id);
                    subName = meta[2] == null ? "" : meta[2];
                    android.net.Uri u = dm.getUriForDownloadedFile(id);
                    if (u != null && u.getPath() != null) new File(u.getPath()).delete();
                }
            } catch (Exception e) { }
        }
        if (c != null) c.close();
        if (subName.length() > 0) {
            try {
                File dir = new File(act.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "Deymflix");
                new File(dir, subName).delete();
            } catch (Exception e) { }
        }
        try { dm.remove(id); } catch (Exception e) { }
        forgetMeta(act, id);
    }

    // =======================================================================
    //  Poster thumbnails (cached, off the UI thread)
    // =======================================================================
    private static void loadPoster(final Activity act, final ImageView target, final String url, final int w, final int h) {
        if (url == null) return;
        if (url.length() == 0) return;
        Bitmap cached = CACHE.get(url);
        if (cached != null) {
            target.setImageBitmap(cached);
            return;
        }
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                try {
                    URL u = new URL(url);
                    HttpURLConnection c = (HttpURLConnection) u.openConnection();
                    c.setConnectTimeout(8000);
                    c.setReadTimeout(8000);
                    c.setRequestProperty("User-Agent", "DeymflixApp/1.4");
                    InputStream in = new BufferedInputStream(c.getInputStream());
                    final Bitmap bmp = BitmapFactory.decodeStream(in);
                    in.close();
                    c.disconnect();
                    if (bmp == null) return;
                    final Bitmap scaled = Bitmap.createScaledBitmap(bmp, w, h, true);
                    if (CACHE.size() > 60) CACHE.clear();
                    CACHE.put(url, scaled);
                    act.runOnUiThread(new Runnable() {
                        @Override public void run() {
                            try { target.setImageBitmap(scaled); } catch (Exception e) { }
                        }
                    });
                } catch (Exception e) {
                    // no network / bad url: the placeholder background stays
                }
            }
        });
        t.start();
    }

    // =======================================================================
    //  Misc
    // =======================================================================
    private static String humanSize(long bytes) {
        if (bytes <= 0) return "-";
        double b = bytes;
        String[] units = { "B", "KB", "MB", "GB" };
        int i = 0;
        while (b >= 1024 && i < units.length - 1) { b /= 1024; i++; }
        return String.format(Locale.US, "%.1f %s", b, units[i]);
    }
}
