// ==========================================
// DEYMFLIX - Filipino Movies & Series Data
// ==========================================
// Add NEW Filipino movies/series HERE (not in app.js).
// They merge into the main `movies` list automatically and appear in
// Tagalog rows, explore filters, search, and the player like any other title.
// IMPORTANT: this file must load BEFORE app.js on every page.
// ==========================================

const filipinoMovieData = [
  { 
    id: "Love, Ngo", 
    imdbId: "tt42111424",
    title: "Love, Ngo", 
    releaseDate: "2026-06-03",
    rating: 9.5,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ix86rEFrhvH3pJtCX7FBpjdKahG.jpg",
    manualEmbed: "https://deymflix-r2-1.b-cdn.net/lovengo.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=nkpTJeSrDd8",
    isSeries: false
  },
  { 
    id: "Filipiñana", 
    imdbId: "tt29512008",
    title: "Filipiñana", 
    releaseDate: "2026-08-26",
    rating: 6,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/paJZyL5uwTJZLlWbEcN6MbFLGYA.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Filipi%C3%B1ana+%E2%80%93+DLPAPS.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=m_HVhPPSeyY",
    isSeries: false
  },
  { 
    id: "Ganito, Ganyan, Ganoon", 
    imdbId: "tt39741670",
    title: "Ganito, Ganyan, Ganoon", 
    releaseDate: "2026-08-13",
    rating: 6.4,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/voT1x4FdnBieu1en3CeKhf7N0n8.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/This%2C+That+and+Everything+in+Between.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=ueGNj0fC8rU",
    isSeries: false
  },
  { 
    id: "Us in the End (Tayo sa Wakas)", 
    imdbId: "tt39554253",
    title: "Us in the End (Tayo sa Wakas)", 
    releaseDate: "2026-05-27",
    rating: 8.5,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/jWK3fep9bswDb6EuarNgoIihDBa.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Us.In.The.End.2026.1080p.WEB-DLH264-TRICKFLIX+(1).mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=E1kcUHGLlnI",
    isSeries: false
  },
  { 
    id: "Wonderful Nightmare", 
    imdbId: "tt39602729",
    title: "Wonderful Nightmare", 
    releaseDate: "2026-04-04",
    rating: 8.1,
    isFilipino: true,
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL77Wnd_A1xbSaSkiIIpZWYPBnhrFZmaK9MEOtnYb78A&s=10",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Wonderful+Nightmare.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=t5ZypDnCq7Q",
    isSeries: false
  },
  { 
    id: "A Special Memory", 
    imdbId: "tt40269077",
    title: "A Special Memory", 
    releaseDate: "2026-03-11",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1ucCvNfCUlhacBZseLik4IWg797.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/A+Special+Memory.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=HT3dagVqPds",
    isSeries: false
  },
  { 
    id: "Until She Remembers", 
    imdbId: "tt39310310",
    title: "Until She Remembers", 
    releaseDate: "2026-02-25",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/xLjqaHCbdX8Rh3vRvR9XQbgGk85.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Until+She+Remembers+%E2%80%93+DLPAPS.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=fRND_au0wXo",
    isSeries: false
  },
  { 
    id: "Call Me Mother", 
    imdbId: "tt37539162",
    title: "Call Me Mother", 
    releaseDate: "2025-12-25",
    rating: 6.1,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kMc1VvhyRdK9w43jaurzfxmnH4x.jpg",
    manualEmbed: "https://deymflix-r2-1.b-cdn.net/Call%20Me%20Mother%202025%201080p%20Filipino%20WEB-DL%20HEVC%20x265%205%201-BONE.mkv",
    trailerEmbed: "https://www.youtube.com/watch?v=cFZmGrP108E",
    isSeries: false
  },
  { 
    id: "Almost Us", 
    imdbId: "tt39734954",
    title: "Almost Us", 
    releaseDate: "2026-05-06",
    rating: 10,
    synopsis: "RR has always been in love with his best friend, Janine. But she's infatuated with Kenzo, the star of her own fan fiction. The film explores the complicated space between love, timing, and the relationships that leave us wondering, 'What if?'",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/gQurSKUKrCFHa90ydVJRtSMyjLB.jpg",
    manualEmbed: "https://deymflix-r2-1.b-cdn.net/Almost%20Us%202026%201080p%20Filipino%20WEB-DL%20HEVC%20x265%205%201-BONE.mkv",
    trailerEmbed: "https://www.youtube.com/watch?v=7Syb_uhtdN0",
    isSeries: false
  },
  { 
    id: "The Lotto Winner", 
    imdbId: "tt39377509",
    title: "The Lotto Winner", 
    releaseDate: "2026-02-18",
    rating: 2,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/sdPxiTp9bf2muVWyxptC5TSsalU.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/The+Lotto+Winner.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=uAtanD32rs8",
    isSeries: false
  },
  { 
    id: "The Loved One", 
    imdbId: "tt39398162",
    title: "The Loved One",
    releaseDate: "2026-02-11",
    rating: 5.6,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/rVZQcphJRWVJgQZtWztrauB6Fwe.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/The+Loved+One.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=zvbs8E667tQ",
    isSeries: true
  },
  { 
    id: "UnMarry", 
    imdbId: "tt38779673",
    title: "UnMarry", 
    releaseDate: "2025-12-25",
    rating: 8,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/tesrfUyiRpiFAaE9OybSoTo12W5.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/UnMarry+%E2%80%93+DLPAPS.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=3bLDu6QxdNE",
    isSeries: false
  },
  { 
    id: "Love You So Bad", 
    imdbId: "tt37982738",
    title: "Love You So Bad", 
    releaseDate: "2025-12-25",
    rating: 4,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/h2VnqqAbO290tQ6QkynsHhgerjC.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Love+You+So+Bad+%E2%80%93+DLPAPS_2.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=HkUHfI4DG1E",
    isSeries: false
  },
  { 
    id: "Bar Boys: After School", 
    imdbId: "tt38779645",
    title: "Bar Boys: After School", 
    releaseDate: "2025-12-25",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/4Gb7BfPyMuVWYoCDC8VQLLKgncl.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Bar+Boys-+After+School.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=K4fQCnApsW8",
    isSeries: false
  },
  { 
    id: "Rekonek", 
    imdbId: "tt38779509",
    title: "Rekonek", 
    releaseDate: "2025-12-25",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/lUcZ7eAzhol9oB3hgfmA8HldPq.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Rekonek+%E2%80%93+DLPAPS.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=n7csBgJqmKQ",
    isSeries: false
  },
  { 
    id: "Salvageland", 
    imdbId: "tt38882902",
    title: "Salvageland", 
    releaseDate: "2025-11-26",
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/3vvQDvrzMPN8sc2n3hLOqrlusDS.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Salvageland.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=Y1ClNzed-g4",
    isSeries: false
  },
  { 
    id: "Meet, Greet & Bye", 
    imdbId: "tt35929110",
    title: "Meet, Greet & Bye", 
    releaseDate: "2025-11-12",
    rating: 7,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/7gEBNzmaTiBVG3g0eUDPU3kPbcc.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Meet%2C+Greet+%26+Bye.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=Mtou4LuxFrg",
    isSeries: false
  },
  { 
    id: "Near Death", 
    imdbId: "tt38797474",
    title: "Near Death", 
    releaseDate: "2025-10-29",
    rating: 4.7,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/4zJVQlCM2onUs3at8tTGEiHdS4D.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Near+Death.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=_WDsgMqFoJw",
    isSeries: false
  },
  { 
    id: "Everyone Knows Every Juan", 
    imdbId: "tt38590407",
    title: "Everyone Knows Every Juan", 
    releaseDate: "2025-10-22",
    rating: 6,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/lCaEmw7wWqzEuolYJSTWHT5uUKq.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/Everyone+Knows+Every+Juan.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=jZv-Up-P7ik",
    isSeries: true
  },
  { 
    id: "The Last Beergin", 
    imdbId: "tt38590754",
    title: "The Last Beergin", 
    releaseDate: "2025-10-01",
    rating: 6,
    isFilipino: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/rdtpEg20TNwu8IOHB2DT7MPbQ9Q.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/The+Last+Beergin+%E2%80%93+DLPAPS.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=C4UMAlD2Khk",
    isSeries: true
  },
  { 
    id: "The Ride", 
    imdbId: "tt38574336",
    title: "The Ride", 
    releaseDate: "2025-09-24",
    isFilipino: true,
    poster: "https://m.media-amazon.com/images/M/MV5BNzRhZDIyYzItYjAxYi00MjUwLTk0MjAtMDcwODMzNWIzYjUzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/Tagalog+Movies/The+Ride.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=P-dnzj_iILY",
    isSeries: true
  },


  // ── 2020–2025 Tagalog catalog (__DFX_NEW_TAGALOG__) ──
  {
    id: "Shake, Rattle & Roll: Evil Origins",
    imdbId: "tt37697399",
    title: "Shake, Rattle & Roll: Evil Origins",
    isFilipino: true,
    releaseDate: "2025-12-25",
    rating: 6,
    synopsis: "In 1775 during the Spanish colonial period in the Philippines, nuns attempts to survive the night after an unknown evil was set free in their cloister. Meanwhile in 2025, a group of friends attend a Halloween masquerade ball which was attacked by a serial killer. Fast forward to the future in 2050, a post-apocalytic Philippines is ruled by the aswang.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/2ayOQIh18qhJRoajoAxxGuZXry2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/90Vx3KpCXR2D9iVdxJpkjeYBq9P.jpg",
    manualEmbed: "cos:movie/1510795",
    trailerEmbed: "https://www.youtube.com/watch?v=A5QQvRaHxDw",
    isSeries: false
  },
  {
    id: "The Woman In The Hole",
    imdbId: "tt38777102",
    title: "The Woman In The Hole",
    isFilipino: true,
    releaseDate: "2025-10-22",
    rating: 3,
    synopsis: "A tricycle driver experiences a passionate encounter with a mysterious woman through a hole in the wall. As he searches for her, hoping she can help him save his crumbling relationship, he discovers that he has actually being deceived by someone close to him.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/zw8FxEI7LXaCERWd9T0RqgM7QSk.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dfs2uFGjD85JvQA4uoqvkV4kdKU.jpg",
    manualEmbed: "cos:movie/1555941",
    isSeries: false
  },
  {
    id: "I'mPerfect",
    imdbId: "tt38779656",
    title: "I'mPerfect",
    isFilipino: true,
    releaseDate: "2025-12-25",
    rating: 0,
    synopsis: "Two people with Down syndrome navigate love, acceptance, and self-discovery in a world that often sees their condition before seeing them.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/x2PObZ8PrlDs5zRrg2HPbs7V2yw.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7AYTbL7ybpAEv0WEQ0T1rohwfG4.jpg",
    manualEmbed: "cos:movie/1560166",
    trailerEmbed: "https://www.youtube.com/watch?v=JjFcvfciGXA",
    isSeries: false
  },
  {
    id: "Outside",
    imdbId: "tt32389619",
    title: "Outside",
    isFilipino: true,
    releaseDate: "2024-10-16",
    rating: 6.1,
    synopsis: "A family retreats to an isolated farm during a zombie outbreak, but years of painful secrets take a toll as they navigate their desolate world.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/a3ej47ztXkeVfHpkwb0TUiA8jQY.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/AeGgtElKvBQY9f9350fztaGLAvH.jpg",
    manualEmbed: "cos:movie/1306764",
    trailerEmbed: "https://www.youtube.com/watch?v=lxzwfbD26Ec",
    isSeries: false
  },
  {
    id: "Your Mother's Son",
    imdbId: "tt28635219",
    title: "Your Mother's Son",
    isFilipino: true,
    releaseDate: "2023-09-10",
    rating: 2.6,
    synopsis: "Sarah, a middle-aged woman who hustles as the sole breadwinner of her family of two, scrambles to teach online courses and meet her food orders to provide for her delinquent son Emman. One day, Sarah brings home Oliver, one of her students, to give him refuge from his violent father. Oliver's presence will have an unimagined impact on Emman.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/k38HWfAA8rI3MyLWisTv0t8gPfV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/o3SUyNs1bgGj4pV7QemkYPHGDJ3.jpg",
    manualEmbed: "cos:movie/1163189",
    trailerEmbed: "https://www.youtube.com/watch?v=NoWRE_w2FUs",
    isSeries: false
  },
  {
    id: "The Garden of Earthly Delights",
    imdbId: "tt15148442",
    title: "The Garden of Earthly Delights",
    isFilipino: true,
    releaseDate: "2025-05-29",
    rating: 8.5,
    synopsis: "In the slums of Manila, 11-year-old Ginto dreams of gang life over scavenging, rejecting his sister Asia’s care as she turns to sex work to survive. As Ginto falls for another boy in the gang, he’s forced to confront his identity and desires amid violence and poverty. Meanwhile, Dutch tourist Michael, consumed by dark impulses, descends into the city’s red-light district. When their paths cross, Ginto faces an impossible choice that will shape both their fates in a world where innocence is currency and survival comes at a cost.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/v3djiiX3wLacamXYjk2ZMUIs2we.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/pdzsaemFuDQ4DMDBZXcoFlUjfd5.jpg",
    manualEmbed: "cos:movie/1309126",
    isSeries: false
  },
  {
    id: "Mang Kanor",
    imdbId: "tt26452066",
    title: "Mang Kanor",
    isFilipino: true,
    releaseDate: "2023-01-28",
    rating: 2,
    synopsis: "Old businessman who finds himself in a scandal after his sex videos with women went viral.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/mbJPWAxs4HzCp7Hcc1VNWccDCYh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/okR4w6G1gxroxSkgH5pSJyEdG9y.jpg",
    manualEmbed: "cos:movie/991511",
    isSeries: false
  },
  {
    id: "The Gap",
    imdbId: "tt39215074",
    title: "The Gap",
    isFilipino: true,
    releaseDate: "2025-11-07",
    rating: 0,
    synopsis: "A lonely barista and a married father slip into a secret romance, where stolen glances turn into passion--and every choice risks breaking their world apart.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/sBJZUs77pxtvj46nnAbZkxOMGBT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/t2rWlhwng27U5cXQtAYdjuKFP5F.jpg",
    manualEmbed: "cos:movie/1603427",
    isSeries: false
  },
  {
    id: "Son of Macho Dancer",
    imdbId: "tt13859274",
    title: "Son of Macho Dancer",
    isFilipino: true,
    releaseDate: "2021-01-30",
    rating: 4.3,
    synopsis: "This is the story of Inno, the son of Pol, the original Macho Dancer.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/4XL0fbF5yW1MAHtlzdHAoyMrpV8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2nO9HahlRMqczAZpoXNmj6tyeIk.jpg",
    manualEmbed: "cos:movie/786875",
    trailerEmbed: "https://www.youtube.com/watch?v=XkdTFNHFl2w",
    isSeries: false
  },
  {
    id: "Kontrabida Academy",
    imdbId: "tt35652650",
    title: "Kontrabida Academy",
    isFilipino: true,
    releaseDate: "2025-09-10",
    rating: 6.8,
    synopsis: "When a mysterious TV transports her to a school for on-screen villains, a restaurant worker finds new purpose — and a way to get back at her enemies.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/uiW2ff73RZzPABKtnjW5wmt43CU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/oYPm2zk8fBxm3UBEiaWMzUGHeFW.jpg",
    manualEmbed: "cos:movie/1428213",
    isSeries: false
  },
  {
    id: "Nothing",
    imdbId: "tt22782308",
    title: "Nothing",
    isFilipino: true,
    releaseDate: "2022-12-06",
    rating: 1,
    synopsis: "Twenty-something June is anxiously awaiting the outcome of her most recent job interview. One day, when her friend goes on a vacation out of town, she is left all alone in their apartment . This overwhelms her as feelings of loneliness, isolation, and envy begin to creep up on her, putting her in an unhealthy state of mind. \"Wala\" is a story of growing pains. It's about the moment of uncertainty in everyone's young life. It's about how the wait can sometimes lead you down completely unexpected paths.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/vfQFlt0fINDYCHGZzz71Bw3sW1j.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gbWElgzZKQ9hSFaZ3ZA5vedoFEN.jpg",
    manualEmbed: "cos:movie/1034496",
    trailerEmbed: "https://www.youtube.com/watch?v=bW7ZvsuYGz8",
    isSeries: false
  },
  {
    id: "The Time That Remains",
    imdbId: "tt38366532",
    title: "The Time That Remains",
    isFilipino: true,
    releaseDate: "2025-10-15",
    rating: 6.6,
    synopsis: "Surrounded by a string of deaths, an older woman relives her romance with a mysterious, ageless lover as an inspector closes in on their dark secret.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/pjtrhgskggN2uD3lF2A9QxHO2Wd.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/OCNoxTB6sqZXmiazkZYyUA6Iz7.jpg",
    manualEmbed: "cos:movie/1550223",
    isSeries: false
  },
  {
    id: "Lolo and the Kid",
    imdbId: "tt32921458",
    title: "Lolo and the Kid",
    isFilipino: true,
    releaseDate: "2024-08-07",
    rating: 7.8,
    synopsis: "A hustler and the child he took in routinely con the wealthy — but a life-changing opportunity could end their inseparable bond.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/a1Eubtd5zCISRsGxpd3CiAYkBao.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fzj8QCwi9zZBO7pi81bfbTa5fak.jpg",
    manualEmbed: "cos:movie/1317887",
    trailerEmbed: "https://www.youtube.com/watch?v=tILXTdgE47E",
    isSeries: false
  },
  {
    id: "I Wish You Had Told Me",
    imdbId: "tt38884553",
    title: "I Wish You Had Told Me",
    isFilipino: true,
    releaseDate: "2025-12-04",
    rating: 5.1,
    synopsis: "When a young missionary uncovers his late father's long-held secret, he travels from the Philippines to Spain in search of his dad's forbidden love.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/AgcxVitzCNFA9DSGaw2oR8O0TVC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/vexA4DDCcs4Wi26IaUEEK9bU8z.jpg",
    manualEmbed: "cos:movie/1576166",
    isSeries: false
  },
  {
    id: "A Girl and A Guy",
    imdbId: "tt14992902",
    title: "A Girl and A Guy",
    isFilipino: true,
    releaseDate: "2021-06-24",
    rating: 4.5,
    synopsis: "A Girl and A Guy is a modern tale of young adults navigating the tricky world of relationships, connection, and intimacy in today’s society. The film tells the story of a girl, the story of a guy, and the story of a girl and a guy.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/8ttjKmGW1Y3Ro2IgPIh7qdY56S1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n2tHqUCbkqAL1KCNnipMrJ6vg5n.jpg",
    manualEmbed: "cos:movie/832913",
    trailerEmbed: "https://www.youtube.com/watch?v=YvoA-hpSieE",
    isSeries: false
  },
  {
    id: "Alter Me",
    imdbId: "tt13329082",
    title: "Alter Me",
    isFilipino: true,
    releaseDate: "2020-11-15",
    rating: 3.7,
    synopsis: "To better connect with other people - and her own emotions - Aimee, an HR manager, seeks the mentorship of Uno, a coveted escort, who soon opens her heart.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/85oK3FewdimpoRGthioTMd8qlpN.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9SQ0x4pXTuUd80mzrA5W54li4Ix.jpg",
    manualEmbed: "cos:movie/703980",
    trailerEmbed: "https://www.youtube.com/watch?v=G041OQyIMPc",
    isSeries: false
  },
  {
    id: "Keys to the Heart",
    imdbId: "tt29025883",
    title: "Keys to the Heart",
    isFilipino: true,
    releaseDate: "2023-10-04",
    rating: 7.1,
    synopsis: "Troubled and alone, a boxer moves in with his long-lost mother and autistic pianist brother — but must fit in with a family he hasn't known for years.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/44oUwH7mn46IaOxIv8t9t5ckwW3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9iBIvsLYxDc2YSSYpoYojC80vcS.jpg",
    manualEmbed: "cos:movie/778277",
    trailerEmbed: "https://www.youtube.com/watch?v=vZt3uHYfXHA",
    isSeries: false
  },
  {
    id: "May-December-January",
    imdbId: "tt22600514",
    title: "May-December-January",
    isFilipino: true,
    releaseDate: "2022-10-12",
    rating: 4.8,
    synopsis: "A story about Claire a single mom and a career woman.  She is aware that her son is gay and accepts this wholeheartedly.  What breaks her heart, though, is finding out that they are both in love with the same man.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nPcDoHyLTGtyQzvInHTpekFl8xT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yneHTIT0fC9UBykOV3gtFHz8AIb.jpg",
    manualEmbed: "cos:movie/1024774",
    trailerEmbed: "https://www.youtube.com/watch?v=i1MtNP9Qcgw",
    isSeries: false
  },
  {
    id: "GomBurZa",
    imdbId: "tt27203116",
    title: "GomBurZa",
    isFilipino: true,
    releaseDate: "2023-12-25",
    rating: 7.4,
    synopsis: "A powerful and moving historical drama that tells the courageous story of three Filipino Catholic priests: Mariano Gomez, José Burgos, and Jacinto Zamora.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/2EG9dLNxHKyT5DEJxsprp0f4O9T.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uWosIXBEdoo2QaSHYHHriSH9fOc.jpg",
    manualEmbed: "cos:movie/1187743",
    trailerEmbed: "https://www.youtube.com/watch?v=KYGvnrPRj4c",
    isSeries: false
  },
  {
    id: "And the Breadwinner Is...",
    imdbId: "tt32206574",
    title: "And the Breadwinner Is...",
    isFilipino: true,
    releaseDate: "2025-01-02",
    rating: 7.1,
    synopsis: "When Bambi discovers that her family has squandered their savings, they devise a plan to cover their debts — but first, she must fake her death.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/fELjp7LpQv8g5JENmRk6SMI7nFj.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/22zGPrn4oD2ZUOqNvfBngxGWh9S.jpg",
    manualEmbed: "cos:movie/1276644",
    trailerEmbed: "https://www.youtube.com/watch?v=l1OiWrv5gFY",
    isSeries: false
  },
  {
    id: "Bingwit",
    imdbId: "tt21653910",
    title: "Bingwit",
    isFilipino: true,
    releaseDate: "2022-08-08",
    rating: 5.6,
    synopsis: "Salem is an ambitious woman who uses her body to attract three men - her politician husband Domingo, the hunk servant Medel/Arnel, and her boy toy Aldon - until Medel/Arnel and Aldon fall in love with each other!",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/40mwVoQw2ERm5AAhUZ34aII37b7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cj5WLeZe98GlkkAif1PlHZIp5rJ.jpg",
    manualEmbed: "cos:movie/992784",
    trailerEmbed: "https://www.youtube.com/watch?v=Ie_TzMrbT80",
    isSeries: false
  },
  {
    id: "Fan Girl",
    imdbId: "tt11091664",
    title: "Fan Girl",
    isFilipino: true,
    releaseDate: "2020-10-31",
    rating: 6.5,
    synopsis: "A starstruck girl sneaks into an actor’s house and discovers a horrifying truth about her idol.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1y8O69OzCdJYaYrwzs41IEaTQgr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5EZoWY15ihVew9KDQayxw5QjU48.jpg",
    manualEmbed: "cos:movie/625658",
    trailerEmbed: "https://www.youtube.com/watch?v=QGowyD_EenI",
    isSeries: false
  },
  {
    id: "You Animal! The Nimfa Dimaano Story",
    imdbId: "tt11102242",
    title: "You Animal! The Nimfa Dimaano Story",
    isFilipino: true,
    releaseDate: "2020-10-28",
    rating: 7.1,
    synopsis: "Follow an attractive feline saleslady at a department store as she figures in a love triangle between her mongrel janitor boyfriend and her high society businessdog.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/pP6mmhuaNmfpGAn1qNd4ZjSWpbY.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cBLnDmmk3Lrfvjg2NZOnC8sQaZR.jpg",
    manualEmbed: "cos:movie/622841",
    trailerEmbed: "https://www.youtube.com/watch?v=k2EDRB7U6_I",
    isSeries: false
  },
  {
    id: "Upuan",
    imdbId: "tt27078515",
    title: "Upuan",
    isFilipino: true,
    releaseDate: "2023-03-03",
    rating: 4,
    synopsis: "Christina and Nessie are childhood friends who fell in love with each other, but they drifted apart because Christina's parents refused to accept her identity. After two years, the two were reunited. However, it was not the reunion they were hoping for.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5haMVGBDcFO96xF7a91ZnSLM1Qm.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/3Xg4oFm8lkGHdD1JbeqkqUkTKal.jpg",
    manualEmbed: "cos:movie/992787",
    trailerEmbed: "https://www.youtube.com/watch?v=l_beUMNuHwo",
    isSeries: false
  },
  {
    id: "My Amanda",
    imdbId: "tt13136084",
    title: "My Amanda",
    isFilipino: true,
    releaseDate: "2021-07-15",
    rating: 5.7,
    synopsis: "Two unusually close friends share every aspect of their lives together. As their lives evolve, their bond remains the only constant.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/v8ffx5ildKQv2i0PDuQ2SVYSnIE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ogbZSb0d3eElgDuQHVgMSnrdpvU.jpg",
    manualEmbed: "cos:movie/843808",
    trailerEmbed: "https://www.youtube.com/watch?v=wcY5f6c6Ldw",
    isSeries: false
  },
  {
    id: "Mallari",
    imdbId: "tt29544868",
    title: "Mallari",
    isFilipino: true,
    releaseDate: "2023-12-25",
    rating: 7.1,
    synopsis: "As Father Severino Mallari, a 19th century priest during the Spanish occupation, descends into madness, his life and work as a parish priest in Pampanga is recounted, where he reportedly murdered 57 people to aid his ailing mother.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/k11utHsPpfYdC5cr53TYe82ddV7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/zz2y87tbNPCw1XYkoZElBcn1WXL.jpg",
    manualEmbed: "cos:movie/1118824",
    trailerEmbed: "https://www.youtube.com/watch?v=JMpbW64ntN0",
    isSeries: false
  },
  {
    id: "Sosyal Climbers",
    imdbId: "tt35624097",
    title: "Sosyal Climbers",
    isFilipino: true,
    releaseDate: "2025-02-26",
    rating: 6.4,
    synopsis: "Stuck with a massive debt after falling for a scam, two wannabe socialites create elaborate fake identities to swindle the rich out of their money.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/cr6y0nWdfPb3yZT9Iz63zTE1dQE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jHbSVuahqx0FVbAhgtf6SUnJ1Vf.jpg",
    manualEmbed: "cos:movie/1426142",
    isSeries: false
  },
  {
    id: "Sunshine",
    imdbId: "tt31711171",
    title: "Sunshine",
    isFilipino: true,
    releaseDate: "2025-07-23",
    rating: 8.7,
    synopsis: "Just days before her team's tryouts for the Olympics, dedicated young gymnast Sunshine discovers she is pregnant. Now she must embark on a desperate and risky journey to fight for her dream.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/vhYUTXbmMQYoqmGW1spTfbHCA7Y.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fN0SoNGGXF615wZD0U8f4btvdSL.jpg",
    manualEmbed: "cos:movie/1269838",
    trailerEmbed: "https://www.youtube.com/watch?v=BxWHDgUs20c",
    isSeries: false
  },
  {
    id: "One Hit Wonder",
    imdbId: "tt35657531",
    title: "One Hit Wonder",
    isFilipino: true,
    releaseDate: "2025-08-21",
    rating: 6.4,
    synopsis: "When big dreams meet second chances, two dreamers Entoy and Lorina chase fame in the world of '90s OPM. Will they make it?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kdHEtyOoB8cyFDwqFMMGK1q0RlM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/99yYnWssK8v67jbin9vosSysnhT.jpg",
    manualEmbed: "cos:movie/1428210",
    isSeries: false
  },
  {
    id: "Adonis X",
    imdbId: "tt21740468",
    title: "Adonis X",
    isFilipino: true,
    releaseDate: "2022-08-08",
    rating: 3.6,
    synopsis: "At the height of finishing a commissioned art piece Dan, a struggling visual artist discovers that his creation named Adonis X, can magically come to life. Forming a strong bond between them, Adonis X became Dan's confidante. But what if this friendship blooms into something more than meets the eye? Can both of them resist the growing \"bromance \" between them?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/gloRMpvFTY431emN7fP0VeTHSP6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dKq0UyNndtKfbG61lkZKftkSkzp.jpg",
    manualEmbed: "cos:movie/991503",
    isSeries: false
  },
  {
    id: "A Journey",
    imdbId: "tt31805808",
    title: "A Journey",
    isFilipino: true,
    releaseDate: "2024-04-13",
    rating: 7.2,
    synopsis: "Refusing treatment for her cancer, a woman goes on a road trip across Tasmania to check off items on her bucket list with her husband and best friend.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/8LbrDogBCM7BxUl5igUrY1CLUfO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5P9b4Ehb1rYqyGCoykFDEjEdBX2.jpg",
    manualEmbed: "cos:movie/1260916",
    isSeries: false
  },
  {
    id: "Leonor Will Never Die",
    imdbId: "tt16377714",
    title: "Leonor Will Never Die",
    isFilipino: true,
    releaseDate: "2022-11-25",
    rating: 6.9,
    synopsis: "Fiction and reality blur when Leonor, a retired filmmaker, falls into a coma after a television lands on her head, compelling her to become the action hero of her unfinished screenplay.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1RhMTthNne58E2P0moPWZcJjpkC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/z2uev1XKsWAKoPNmJ2mKRLiMCua.jpg",
    manualEmbed: "cos:movie/913689",
    trailerEmbed: "https://www.youtube.com/watch?v=ro6xty9NWe0",
    isSeries: false
  },
  {
    id: "Scarecrow",
    imdbId: "tt34830387",
    title: "Scarecrow",
    isFilipino: true,
    releaseDate: "2025-02-07",
    rating: 6.3,
    synopsis: "As a family clashes over their late father's land, an eerie painting appears and releases something sinister during the nine-day funeral ritual.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/itRDwuQxbtmgaxyrHI4rGiIrxxX.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/t0krAUn3odB8H2KC60dJzKIWPyz.jpg",
    manualEmbed: "cos:movie/1355983",
    trailerEmbed: "https://www.youtube.com/watch?v=ZJ84Aug0pok",
    isSeries: false
  },
  {
    id: "A Very Good Girl",
    imdbId: "tt27327494",
    title: "A Very Good Girl",
    isFilipino: true,
    releaseDate: "2023-09-27",
    rating: 6.1,
    synopsis: "After a heartless firing triggers a chain of unfortunate events, Philo plots a meticulous revenge against retail mogul, Mother Molly, aiming to dismantle her empire and seize the ultimate payback. This time, there is no mercy.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ezfxB7Kd2l6keH9xBCX4599zuuL.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iHLEbZabTsHdf15fW4E5EV57eMa.jpg",
    manualEmbed: "cos:movie/1105324",
    trailerEmbed: "https://www.youtube.com/watch?v=jFfzQYNY0AE",
    isSeries: false
  },
  {
    id: "Mama Susan's Friends",
    imdbId: "tt27510021",
    title: "Mama Susan's Friends",
    isFilipino: true,
    releaseDate: "2023-05-18",
    rating: 5.8,
    synopsis: "Galo is a university student who writes on his journal the string of unsettling and mysterious experiences he has while living with his grandmother, Mama Susan.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/gtgltT1u4kVUJBocfRb1Xf2v1gu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uNhPZcGXwLtxQz1NgRJOSc0km3e.jpg",
    manualEmbed: "cos:movie/673836",
    trailerEmbed: "https://www.youtube.com/watch?v=HLkUFUKgpj8",
    isSeries: false
  },
  {
    id: "Hello, Love, Again",
    imdbId: "tt32401874",
    title: "Hello, Love, Again",
    isFilipino: true,
    releaseDate: "2024-11-13",
    rating: 6.4,
    synopsis: "Five years on from when Joy said goodbye to Ethan and Hong Kong to pursue her dreams in Canada. After fighting for their love to conquer the time, distance and a global shutdown that kept them apart, Joy and Ethan meet again in Canada but realize that they have also changed a lot, individually.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/7R940b9RNNKLDrAI1GmCjOd5ta.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7HD80No4QO71recMEgmkwuZWl99.jpg",
    manualEmbed: "cos:movie/1292359",
    trailerEmbed: "https://www.youtube.com/watch?v=uRBHJPic9zc",
    isSeries: false
  },
  {
    id: "Sampung Utos Kay Josh",
    imdbId: "tt35559284",
    title: "Sampung Utos Kay Josh",
    isFilipino: true,
    releaseDate: "2025-01-29",
    rating: 9,
    synopsis: "Josh, a devout loan executive who believes his faith and adherence to the Ten Commandments have brought him a good life. However, when a series of misfortunes strike. Josh begins to feel abandoned by his faith. In his frustration, he decides to rebel by breaking each commandment.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/3fSfR0hI5p9aOFtlg6GXGnwNnHS.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/vVr6UI8FXTfVkIk3Px93fVOWPZB.jpg",
    manualEmbed: "cos:movie/1424649",
    trailerEmbed: "https://www.youtube.com/watch?v=aN3mg1h9iZc",
    isSeries: false
  },
  {
    id: "Hello, Stranger: The Movie",
    imdbId: "tt12951932",
    title: "Hello, Stranger: The Movie",
    isFilipino: true,
    releaseDate: "2021-02-12",
    rating: 6.7,
    synopsis: "Xavier and Mico join a writing camp, where they get to know each other more. But with their friends and other people around them twist and turn them in different directions, will they be strangers no more or strangers again?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nrGnrf869TOi0GiBiS3YTqR8HWd.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4NAfKI2Gy4erh1NKeKDXIUo0FzE.jpg",
    manualEmbed: "cos:movie/736774",
    trailerEmbed: "https://www.youtube.com/watch?v=ZeUOPBuSyug",
    isSeries: false
  },
  {
    id: "Whether the Weather Is Fine",
    imdbId: "tt14962622",
    title: "Whether the Weather Is Fine",
    isFilipino: true,
    releaseDate: "2021-08-09",
    rating: 7,
    synopsis: "Against the backdrop of the Typhoon Yolanda, a mother and her son struggle for survival and deal with absurdity of fate, sustained by the hope that they carry, and what is lost and gained.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/xTF8cZlaOIKTaTEDmL3Bv3ujEIm.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/sbV6RiNdZ0sZbSrKDTfyDojF4bs.jpg",
    manualEmbed: "cos:movie/645575",
    trailerEmbed: "https://www.youtube.com/watch?v=SKuQ_m_tS_M",
    isSeries: false
  },
  {
    id: "Doll House",
    imdbId: "tt22038236",
    title: "Doll House",
    isFilipino: true,
    releaseDate: "2022-10-07",
    rating: 5.8,
    synopsis: "A troubled lead singer of a rock band sets out to rekindle the relationship he never had with his long-lost daughter.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/hYGADLbf0I7VLe5i8pwjJ9dRYh4.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/x3Wc3zEMvP5YELl3xTPlxc0SJE4.jpg",
    manualEmbed: "cos:movie/1025880",
    trailerEmbed: "https://www.youtube.com/watch?v=Ws9jDMZqkJo",
    isSeries: false
  },
  {
    id: "Strange Frequencies: Taiwan Killer Hospital",
    imdbId: "tt34630546",
    title: "Strange Frequencies: Taiwan Killer Hospital",
    isFilipino: true,
    releaseDate: "2024-12-25",
    rating: 5.4,
    synopsis: "A team of adventurous celebrities filming in Taiwan’s infamous Xinglin Hospital, one of Southeast Asia’s most haunted locations, quickly descends into terror as they encounter escalating paranormal phenomena. As tensions rise and personalities clash, they become pawns of a malevolent entity, forcing them to make difficult choices and sacrifices to survive the horrifying ordeal.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/wvPcnbmnsD8cMqPPJgGHWeCJ9L0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/1KFFxdxOaER42G4RGZZU0t1tzFY.jpg",
    manualEmbed: "cos:movie/1381534",
    trailerEmbed: "https://www.youtube.com/watch?v=9alAvn2eXM4",
    isSeries: false
  },
  {
    id: "When the Waves Are Gone",
    imdbId: "tt12824896",
    title: "When the Waves Are Gone",
    isFilipino: true,
    releaseDate: "2023-08-16",
    rating: 7,
    synopsis: "One of the Philippines' top investigators, Lieutenant Hermes Papauran, faces a deep moral crossroads. As a firsthand witness of the murderous anti-drug campaign conducted by his force, his anxiety and guilt triggers a severe skin disease, and his healing process is fraught by his dark past.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/fXoQlfN3iEXsZxycQl3e2R6Y2Wl.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/h0AIRxHGlTUruCEYE6ehVTxJWbr.jpg",
    manualEmbed: "cos:movie/643736",
    trailerEmbed: "https://www.youtube.com/watch?v=U-jVayarEBU",
    isSeries: false
  },
  {
    id: "Vagrant",
    imdbId: "tt28564048",
    title: "Vagrant",
    isFilipino: true,
    releaseDate: "2023-06-30",
    rating: 2.6,
    synopsis: "A couple’s struggling marriage due to the husband’s sexual incapacity takes an unexpected turn when they save a homeless man from a violent assault. As they offer him shelter, the three develop a complicated and tangled relationship, leading to life-altering consequences.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/51o0xa2N2f2RsiYsqudqVGKWFXp.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/oB4T3Md6teq3YOK5d6lpOObYA2I.jpg",
    manualEmbed: "cos:movie/1134713",
    isSeries: false
  },
  {
    id: "Men Are From QC, Women Are From Alabang",
    imdbId: "tt32034823",
    title: "Men Are From QC, Women Are From Alabang",
    isFilipino: true,
    releaseDate: "2024-05-01",
    rating: 5.2,
    synopsis: "Two lovers navigate post-graduation life, facing challenges of long-distance relationship and career demands. Their perspectives on shared experiences diverge as physical and emotional distance grows, straining their bond over time.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/sziLF3lbukv5f8mEbbG3sV0Cheh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8HFb52gohuQGu0zK6bkMtD1RJKw.jpg",
    manualEmbed: "cos:movie/1277838",
    isSeries: false
  },
  {
    id: "The Entitled",
    imdbId: "tt21030232",
    title: "The Entitled",
    isFilipino: true,
    releaseDate: "2022-07-29",
    rating: 4.9,
    synopsis: "Suddenly catapulted into high society, a young woman who lacks a bit of finesse tries to integrate into her new surroundings.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/plv85l002BHwPq7zvjceGt4h3nz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nyl5ERVPNMElUICsTmY98zZ5iqp.jpg",
    manualEmbed: "cos:movie/994006",
    trailerEmbed: "https://www.youtube.com/watch?v=gim0k37sfO8",
    isSeries: false
  },
  {
    id: "Rewind",
    imdbId: "tt28152455",
    title: "Rewind",
    isFilipino: true,
    releaseDate: "2023-12-25",
    rating: 6.9,
    synopsis: "Mary loves John for as long as she can remember. But after years of marriage, John's priorities shift, leading to a strained relationship with Mary, which causes a tragic accident that takes away Mary's life. Until one day, John gets an extraordinary proposition - to rewind time and save the life of the woman he loves.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/i8UjdAwezeFHHR4opNb3LxDCQWC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gr7N3zCtXeUNCDnXa0DPKCq2bRQ.jpg",
    manualEmbed: "cos:movie/1143183",
    trailerEmbed: "https://www.youtube.com/watch?v=_31Tod1VvLM",
    isSeries: false
  },
  {
    id: "Triggered",
    imdbId: "tt23182472",
    title: "Triggered",
    isFilipino: true,
    releaseDate: "2024-12-25",
    rating: 5.4,
    synopsis: "In a bid for redemption, an Ex-Special Forces security guard attempts to save the life of a woman who is being hunted by a corrupt police death squad working for a drug cartel.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/50g702Thykuc49lhVpz4zMSpPtL.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lC6l36m9M9343mqC9coouVbNwGe.jpg",
    manualEmbed: "cos:movie/1132491",
    trailerEmbed: "https://www.youtube.com/watch?v=YkGnZ66xN10",
    isSeries: false
  },
  {
    id: "Missed Connections",
    imdbId: "tt27703325",
    title: "Missed Connections",
    isFilipino: true,
    releaseDate: "2023-06-02",
    rating: 5.3,
    synopsis: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met — but is he really what she's looking for?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/Au0HeQRyMpNCIUI6rUeYVkcsjAw.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/pw2NKCaDfBLx6VnjEhR42YMb09X.jpg",
    manualEmbed: "cos:movie/1123342",
    trailerEmbed: "https://www.youtube.com/watch?v=Rwoe1BKrME4",
    isSeries: false
  },
  {
    id: "Day Zero",
    imdbId: "tt21254710",
    title: "Day Zero",
    isFilipino: true,
    releaseDate: "2022-07-03",
    rating: 6.9,
    synopsis: "A former elite soldier is released from jail only to discover that the outside world has been taken over by a dangerous virus. Chased by hordes of the undead, he fights tooth and nail in a desperate attempt to reach his estranged family.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/3ja9jRtrEhe7eF5Db4zpgsg1El5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yaYXIPJhqlZLSiixDwAOu7A6X02.jpg",
    manualEmbed: "cos:movie/988253",
    trailerEmbed: "https://www.youtube.com/watch?v=d9ndpn4LaKs",
    isSeries: false
  },
  {
    id: "My Future You",
    imdbId: "tt32241752",
    title: "My Future You",
    isFilipino: true,
    releaseDate: "2024-12-25",
    rating: 6.3,
    synopsis: "Karen and Lex meet on a dating app, only to discover they're living fifteen years apart, connected by a comet. As they unravel the mystery of their unique situation, they work together to change the past and alter their fates.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/qXzKWdQchfcAWqZahH3BM6DvT6t.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jbvGnnQE4YuHcPwQoiTglDbybTO.jpg",
    manualEmbed: "cos:movie/1381548",
    trailerEmbed: "https://www.youtube.com/watch?v=geZVIDif2Vc",
    isSeries: false
  },
  {
    id: "Deleter",
    imdbId: "tt21237578",
    title: "Deleter",
    isFilipino: true,
    releaseDate: "2022-12-25",
    rating: 4.2,
    synopsis: "An online content moderator deletes a suicide video made by her co-worker. But the otherwise desensitized woman cannot escape from either her own troubled past or from a mysterious vengeful presence.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5RmF0Hbotq206ofgb4ZgEBnQkC1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/AdhumsAfIM65DWGh4QF7vo0CxUI.jpg",
    manualEmbed: "cos:movie/998558",
    trailerEmbed: "https://www.youtube.com/watch?v=nw27H5IKJLk",
    isSeries: false
  },
  {
    id: "Isolated",
    imdbId: "tt35682221",
    title: "Isolated",
    isFilipino: true,
    releaseDate: "2025-04-30",
    rating: 7.2,
    synopsis: "A nurse and her patient are trying to escape when a violent intruder starts hunting them.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/qzgqskA5lLE2W9pXNyu12GkNSeU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/t30MYo21Zf3vtVTh8p8m2JUGouX.jpg",
    manualEmbed: "cos:movie/1463205",
    trailerEmbed: "https://www.youtube.com/watch?v=BME458-N8n4",
    isSeries: false
  },
  {
    id: "Green Bones",
    imdbId: "tt34140719",
    title: "Green Bones",
    isFilipino: true,
    releaseDate: "2024-12-25",
    rating: 7.5,
    synopsis: "A soon-to-be released criminal and a corrections officer is still grieving over the death of his sister opposing the prisoner's release.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/xchGm7FwMNZZ7Ret8ZknYKWcZeL.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/k1QUKQsqRwvp332zPwfKVx9dTrB.jpg",
    manualEmbed: "cos:movie/1377080",
    trailerEmbed: "https://www.youtube.com/watch?v=5-kt92ciGfk",
    isSeries: false
  },
  {
    id: "Seasons",
    imdbId: "tt28022861",
    title: "Seasons",
    isFilipino: true,
    releaseDate: "2023-07-07",
    rating: 6.8,
    synopsis: "After a string of failed relationships, two best friends make a deal to take risks and look for love again — but they might just find it in each other.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kz0jM9Uw15ElDXQSpfNQupZuLPI.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/zCZPNfMZFF1PQ1qEk11cmkaidJY.jpg",
    manualEmbed: "cos:movie/849177",
    isSeries: false
  },
  {
    id: "Izla",
    imdbId: "tt16161362",
    title: "Izla",
    isFilipino: true,
    releaseDate: "2021-10-22",
    rating: 4.2,
    synopsis: "Two brothers accompany a group of vloggers on their search for a mythical island. But when they find it, they uncover one sinister secret after another.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/yvTLGmsML3igYAkgkEYuEBO7z6C.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ZoEwxLRwDVoSPeJMfFTWbbgpsC.jpg",
    manualEmbed: "cos:movie/892866",
    trailerEmbed: "https://www.youtube.com/watch?v=U6_bJwIHqrs",
    isSeries: false
  },
  {
    id: "A Hard Day",
    imdbId: "tt16024152",
    title: "A Hard Day",
    isFilipino: true,
    releaseDate: "2021-12-25",
    rating: 5.8,
    synopsis: "After trying to cover up a car accident that left a man dead, a crooked homicide detective is stalked by a mysterious man claiming to have witnessed the event.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/bJWSi20OXHPgcw8FWBwOi0tXbXk.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bRBes2yej5IzMX1RU5RIzgT2yCW.jpg",
    manualEmbed: "cos:movie/667711",
    isSeries: false
  },
  {
    id: "He Who Is Without Sin",
    imdbId: "tt12257158",
    title: "He Who Is Without Sin",
    isFilipino: true,
    releaseDate: "2020-11-21",
    rating: 6.6,
    synopsis: "One evening, Martin, a broadcasting student, is invited for coffee by Lawrence, the TV reporter he idolizes. During the days that follow, Martin shares with his friends separately three versions of what transpired during his meeting with Lawrence: what happened, what really happened, and what might have actually happened. Through conversations with friends, Martin comes to terms with the idea that his idol – a dignified newsman who is supposed to be a paragon of virtue – is not who he appears to be on television.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/bbdT422ohTk1WuX7ysdRFtQSQDu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lJv4GJCTONVXkNWQmeQaGWWcRUC.jpg",
    manualEmbed: "cos:movie/643883",
    trailerEmbed: "https://www.youtube.com/watch?v=GdjO5wUSfX8",
    isSeries: false
  },
  {
    id: "Love Is Color Blind",
    imdbId: "tt15979132",
    title: "Love Is Color Blind",
    isFilipino: true,
    releaseDate: "2021-12-09",
    rating: 6.6,
    synopsis: "After an accident left a budding artist color blind, his best friend takes it upon herself to bring back the colors in his life and make him realize her unwavering love. But this proves to be no easy task when a potential rival enters the picture.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ytkyDqKklYM5eIIeyiBCEweG4cD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6rZr3K5NKEljhvio3xL36Du23go.jpg",
    manualEmbed: "cos:movie/778278",
    trailerEmbed: "https://www.youtube.com/watch?v=rdCBU4DQByI",
    isSeries: false
  },
  {
    id: "Posthouse",
    imdbId: "tt36461758",
    title: "Posthouse",
    isFilipino: true,
    releaseDate: "2025-08-20",
    rating: 5,
    synopsis: "An editor and his daughter work to restore a family heirloom — an old silent horror film — unaware that each frame inches them closer to a dark spirit.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/3fKDnw1i2Or7qHgB5gmT0wWZNtw.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dB1kkUlKgxWngMPbcv3jmU1QeY4.jpg",
    manualEmbed: "cos:movie/1460778",
    trailerEmbed: "https://www.youtube.com/watch?v=nKce-y5DLSU",
    isSeries: false
  },
  {
    id: "In My Mother's Skin",
    imdbId: "tt20413870",
    title: "In My Mother's Skin",
    isFilipino: true,
    releaseDate: "2023-01-20",
    rating: 5.8,
    synopsis: "Stranded in the Philippines during World War II, a young girl finds that her duty to protect her dying mother is complicated by her misplaced trust in a beguiling, flesh-eating fairy.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/wBdNfKCjZYyDVZa8vlD47VlcLKA.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cUBLbs8ZWyaBb2RedEbYQLkCJUs.jpg",
    manualEmbed: "cos:movie/1058662",
    trailerEmbed: "https://www.youtube.com/watch?v=GQclHcpbKdA",
    isSeries: false
  },
  {
    id: "Arisaka",
    imdbId: "tt11443276",
    title: "Arisaka",
    isFilipino: true,
    releaseDate: "2021-10-15",
    rating: 5.6,
    synopsis: "A witness under police escort is attacked. A policewoman, the only one who survives, is sheltered by indigenous people, but assailants hunt her down... An action thriller set in Bataan.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/otj6cxt1ho0KG6nmpQaBxjL6Ocz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/l7ExztasIBBoAjpmu4piPRm11v8.jpg",
    manualEmbed: "cos:movie/645585",
    trailerEmbed: "https://www.youtube.com/watch?v=29_DR0aAk0o",
    isSeries: false
  },
  {
    id: "The Boy Foretold By the Stars",
    imdbId: "tt13397632",
    title: "The Boy Foretold By the Stars",
    isFilipino: true,
    releaseDate: "2020-12-25",
    rating: 6.8,
    synopsis: "The Boy Foretold By The Stars is a romantic comedy movie about two senior high school boys who, through the help of a fortune-teller, find each other at an optional school retreat called Journey with the Lord.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/c0W7arPyWUDL76pZc3WnjW2nvAH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s0l03xCI2pzW6aRwh1LepA4ahcI.jpg",
    manualEmbed: "cos:movie/673816",
    trailerEmbed: "https://www.youtube.com/watch?v=j4FHwXqSkr8",
    isSeries: false
  },
  {
    id: "Expensive Candy",
    imdbId: "tt21968374",
    title: "Expensive Candy",
    isFilipino: true,
    releaseDate: "2022-09-14",
    rating: 2.8,
    synopsis: "Candy is a sex worker. A poor teacher, Toto, falls in love with her and she becomes his motivation to work hard.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/xqqSujBOob4zkHwuWsSTUQWAmfh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/1mTtTniYmMRQ33Nvfx635zWm5v7.jpg",
    manualEmbed: "cos:movie/1014887",
    isSeries: false
  },
  {
    id: "About Us But Not About Us",
    imdbId: "tt23622578",
    title: "About Us But Not About Us",
    isFilipino: true,
    releaseDate: "2023-04-08",
    rating: 5.6,
    synopsis: "A literature professor meets his student at a restaurant and, over the course of one meal, secrets and lies will be unearthed and the sinister connection to a tragedy will be revealed.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/afrQ09BPQwxmCnl1uhpkECUtTSK.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dHfA82DK7u7meq3KtNBnCAC6glj.jpg",
    manualEmbed: "cos:movie/1047001",
    trailerEmbed: "https://www.youtube.com/watch?v=wO8LrhyMudk",
    isSeries: false
  },
  {
    id: "Death of Nintendo",
    imdbId: "tt10642250",
    title: "Death of Nintendo",
    isFilipino: true,
    releaseDate: "2020-02-22",
    rating: 6.4,
    synopsis: "The story takes us into the colorful pop-culture world of these four 13-year old friends, back in the days when video games were still a novelty. Mimaw and her friends Paolo, Kachi and Gilligan go on a journey of self-discovery together as they play games and wrestle with new dilemmas – puppy love, circumcision and other horror stories.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/j7agkgWKynzLiAV7km2gWnVmugS.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iPTt3scnDDPmEmRzhHAwH4W0Kam.jpg",
    manualEmbed: "cos:movie/655174",
    trailerEmbed: "https://www.youtube.com/watch?v=DMKQTKtvnDc",
    isSeries: false
  },
  {
    id: "How to Die Young in Manila",
    imdbId: "tt13230864",
    title: "How to Die Young in Manila",
    isFilipino: true,
    releaseDate: "2020-10-28",
    rating: 5.1,
    synopsis: "An introverted teenage boy lies to his parents that he'd sleep over at his friends'. However, he made an appointment with a random guy found on a dating app. The street is filled with dead hustlers, but nobody seems to notice these strange occurrences.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/44NfplO8CZZUONfP8fTxkQhH4nh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/aAj6G4zTspnHF15v6oeGLIH5bnb.jpg",
    manualEmbed: "cos:movie/746413",
    trailerEmbed: "https://www.youtube.com/watch?v=SnRllsPamh4",
    isSeries: false
  },
  {
    id: "Ballot",
    imdbId: "tt33059549",
    title: "Ballot",
    isFilipino: true,
    releaseDate: "2024-10-16",
    rating: 8.4,
    synopsis: "A land-grabbing tycoon and a former sexy male actor are in a tight race for mayor in a small town. When violence erupts, Emmy, a teacher, runs into the wilderness with a ballot box, the last copy of the election result.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5ZWJpXQdQYPiBO3CbFtVvuDGvhl.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/AcFNFVWWs7vFpUbvzBlo7dZF7v6.jpg",
    manualEmbed: "cos:movie/1164488",
    trailerEmbed: "https://www.youtube.com/watch?v=QJLNWsa38Xw",
    isSeries: false
  },
  {
    id: "Maid in Malacañang",
    imdbId: "tt21279138",
    title: "Maid in Malacañang",
    isFilipino: true,
    releaseDate: "2022-08-03",
    rating: 3.9,
    synopsis: "The untold story of the last 72 hours of the Marcoses inside Malacañang Palace before fleeing to Hawaii, during the 1986 People Power Revolution.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/8ukeEdnTaS74CgRiRsV146uZCDA.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4gyu2DQKeSMAvqckvcQMZs3Ah7O.jpg",
    manualEmbed: "cos:movie/983783",
    trailerEmbed: "https://www.youtube.com/watch?v=cWeVNyEcQSM",
    isSeries: false
  },
  {
    id: "Gameboys: The Movie",
    imdbId: "tt14813878",
    title: "Gameboys: The Movie",
    isFilipino: true,
    releaseDate: "2021-06-30",
    rating: 8.2,
    synopsis: "The story of gamers turned lovers Cairo and Gavreel, to spend time together in Gavreel's house, a few weeks before Cairo returns to his province. What starts out as a romantic holiday for the young couple turns into a relationship test that they have to overcome. Cairo is faced with the reality of his imminent departure while Gavreel is compelled to make a life-changing decision. After defying distance and even the pandemic, will Cairo and Gavreel be able to prove once again that their love for each other is strong enough to withstand fate and circumstance?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/2e7yNIMQuAGm1zjdF8Wpa1yHUxs.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qxkpaG2b5DGZDaRPMJJhLADWMzw.jpg",
    manualEmbed: "cos:movie/728816",
    trailerEmbed: "https://www.youtube.com/watch?v=BTd3PCntHcI",
    isSeries: false
  },
  {
    id: "Run",
    imdbId: "tt14585564",
    title: "Run",
    isFilipino: true,
    releaseDate: "2021-01-22",
    rating: 4.4,
    synopsis: "Gene is running away from the wrath of his own father while Mark is running away from his past. Gene is from Mariveles, Bataan while Mark is from Leyte. Destiny plays cupid on them as they meet in a far-away and picturesque town of Arayat, Pampanga. The need for somebody to hold and their mutual attraction seal their encounter. Can Gene and Mark start a happy life of togetherness in their new-found paradise or will their past continue to haunt them?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/dVPAtQ1bVyzsgD4Cm0DVyikBzfX.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lMrptzVBqXIJCrBfE9mGI7pne7Y.jpg",
    manualEmbed: "cos:movie/787816",
    isSeries: false
  },
  {
    id: "Big Night!",
    imdbId: "tt16024312",
    title: "Big Night!",
    isFilipino: true,
    releaseDate: "2021-11-25",
    rating: 5.6,
    synopsis: "A gay beautician is determined to clear his name after learning he's included in a drug watchlist.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/bv8druvu1QHKVzgZvboelZnbiGg.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cICzSGtmmFihO9xxUOjm2UAJlck.jpg",
    manualEmbed: "cos:movie/670159",
    trailerEmbed: "https://www.youtube.com/watch?v=TeyApgeB2Mg",
    isSeries: false
  },
  {
    id: "Love Lockdown",
    imdbId: "tt12275096",
    title: "Love Lockdown",
    isFilipino: true,
    releaseDate: "2020-05-15",
    rating: 3.3,
    synopsis: "A triptych of interconnected tales of love, lust, and betrayal. Can they escape from their shattered fates as they get entangled in a web of lies?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/fSpsnaYZydcpBwMDkgpWRhwlNC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ktkPCidFx6uY0ctBilspcHdMVsw.jpg",
    manualEmbed: "cos:movie/701264",
    trailerEmbed: "https://www.youtube.com/watch?v=YrhIs0z-4X0",
    isSeries: false
  },
  {
    id: "Here and There",
    imdbId: "tt14766058",
    title: "Here and There",
    isFilipino: true,
    releaseDate: "2021-03-05",
    rating: 4.8,
    synopsis: "As the community quarantine puts the nation on hold, a political science major and a student working part time as a delivery driver butt heads online – but soon find themselves falling for each other. Will their love survive once it’s taken offline?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/cc05MbgA0pSIy1Qwcn9BfWJJgl7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rfEJH0aRrPhrnlsVLr8VcGOJhdA.jpg",
    manualEmbed: "cos:movie/793706",
    trailerEmbed: "https://www.youtube.com/watch?v=RLsvyTm8p3I",
    isSeries: false
  },
  {
    id: "P77",
    imdbId: "tt37179746",
    title: "P77",
    isFilipino: true,
    releaseDate: "2025-07-30",
    rating: 4.7,
    synopsis: "A cruise ship chambermaid has to quit her job to attend to her sick brother. Only to find out their mother's gone missing and her brother's condition is getting progressively worse. The siblings desperately sneak into an empty condo unit but soon discover that Penthouse 77 is not what it seems...",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5pM7B1ZQZqo7kgyGlygEwk3gAR1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/96Jp6Bqm3dLIog1OCuTHrImt7yR.jpg",
    manualEmbed: "cos:movie/1164495",
    trailerEmbed: "https://www.youtube.com/watch?v=bVeOi_YNhd8",
    isSeries: false
  },
  {
    id: "Nightshift",
    imdbId: "tt10794406",
    title: "Nightshift",
    isFilipino: true,
    releaseDate: "2020-01-22",
    rating: 4.8,
    synopsis: "A young woman is stuck in the morgue - on her first day - working as an assistant to a pathologist when the dead begin to manifest signs of resurrection.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/k4brHfRBKw3lw3uHo6NTx88J4vB.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/asCfpGcxWwmJeVsy0Oy1IaxU7H4.jpg",
    manualEmbed: "cos:movie/661664",
    trailerEmbed: "https://www.youtube.com/watch?v=2pEUKEU2xpM",
    isSeries: false
  },
  {
    id: "Block Z",
    imdbId: "tt10044182",
    title: "Block Z",
    isFilipino: true,
    releaseDate: "2020-01-29",
    rating: 6.8,
    synopsis: "A pre-med student and her friends encounter the death of a patient that exhibited symptoms of rabies. They are soon faced with an even bigger problem as their patient comes back from the dead and infects the people on campus, causing a lockdown and trapping the students inside.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/n6jAasaOFvg0LNEpx7tLr5gVAEP.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wOlpDG2R6CIBq8CnWYST2WTa8Df.jpg",
    manualEmbed: "cos:movie/531900",
    trailerEmbed: "https://www.youtube.com/watch?v=kYb9eAu27Vo",
    isSeries: false
  },
  {
    id: "Masalimuot ya Tiyagew ed Dayat",
    imdbId: "tt21137926",
    title: "Masalimuot ya Tiyagew ed Dayat",
    isFilipino: true,
    releaseDate: "2021-08-25",
    rating: 5.7,
    synopsis: "Two lads, best friends since childhood reunite at the beach but as their bond gets stronger they are reminded of their fears to a mythical creature inherent in the place.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/d6BVHIchZwcteZmDlAGMJIMQARs.jpg",
    manualEmbed: "cos:movie/859374",
    trailerEmbed: "https://www.youtube.com/watch?v=RjFY5YVmJbI",
    isSeries: false
  },
  {
    id: "Ten Little Mistresses",
    imdbId: "tt24787466",
    title: "Ten Little Mistresses",
    isFilipino: true,
    releaseDate: "2023-02-15",
    rating: 6.4,
    synopsis: "A widowed billionaire's ten mistresses fight tooth and nail to become his new legal wife. But when he suddenly turns up dead, all ten women end up being prime suspects.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kogK99QugddnSIMe3Wy8fWCLL60.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rOXBI0WOpfUuFpobFAOvnv2T1HT.jpg",
    manualEmbed: "cos:movie/1063540",
    trailerEmbed: "https://www.youtube.com/watch?v=It120HSWer4",
    isSeries: false
  },
  {
    id: "Under Parallel Skies",
    imdbId: "tt28443413",
    title: "Under Parallel Skies",
    isFilipino: true,
    releaseDate: "2024-04-17",
    rating: 6.1,
    synopsis: "Tells the story of a Thai bachelor named Parin who travels to Hong Kong in search of his missing mother. He encounters a Filipino hotel employee named Iris who helps him navigate love, heartbreak, and healing in the foreign city amid their differences in culture and identity.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/7XOwbJSM36zWGGaJCJgj0SytvkE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2KY3rb2WpR86kDlZzvTjS4mJjNj.jpg",
    manualEmbed: "cos:movie/1254037",
    trailerEmbed: "https://www.youtube.com/watch?v=9mw26bDbbjA",
    isSeries: false
  },
  {
    id: "The ExorSIS",
    imdbId: "tt16729508",
    title: "The ExorSIS",
    isFilipino: true,
    releaseDate: "2021-12-25",
    rating: 4.8,
    synopsis: "The film follows Gina, who must find an exorcist after her younger sister gets possessed by a dead woman’s spirit.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/9FE7LHY4E3s9nHmgeU7cpmMuvTU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6JB4hJdCrBMnd84U7ODnnEyjpOi.jpg",
    manualEmbed: "cos:movie/737676",
    trailerEmbed: "https://www.youtube.com/watch?v=ILw0ccN3Wpg",
    isSeries: false
  },
  {
    id: "Untold",
    imdbId: "tt36203672",
    title: "Untold",
    isFilipino: true,
    releaseDate: "2025-04-30",
    rating: 5.4,
    synopsis: "Vivian Vera is a multi-awarded journalist with a dark past. She sensationalized some of her breaking news for her ambition. Her distortion of the truth ruined lives, and these lives have begun to haunt Vivian – they want her to join them... or else they will kill everyone around her who helped her in the lie.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/noqqpt8269lY0ghru8eSGC2nHT2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/74ZXmVoV915tkBzSYztU4NOIbia.jpg",
    manualEmbed: "cos:movie/1407050",
    trailerEmbed: "https://www.youtube.com/watch?v=sCp1ZlNf3GY",
    isSeries: false
  },
  {
    id: "Once Before",
    imdbId: "tt11924560",
    title: "Once Before",
    isFilipino: true,
    releaseDate: "2020-03-04",
    rating: 5.8,
    synopsis: "After a tragic car crash, Gabby finds herself in a love triangle with the ghost of her fiancé and a friend seeking more than a platonic relationship.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/f0lkDzdBxaW9nVJgAZq53Rz1Gmt.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8nSSCCjqiTdfuc2e19NDEo7EQGS.jpg",
    manualEmbed: "cos:movie/667694",
    isSeries: false
  },
  {
    id: "U-Turn",
    imdbId: "tt11638656",
    title: "U-Turn",
    isFilipino: true,
    releaseDate: "2020-10-30",
    rating: 5.5,
    synopsis: "A young reporter's investigation into a string of grisly suicides takes a dangerous detour when she follows the clues to a cursed stretch of road.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/niRbJiZWkiP8U4IBMnMeDZjjJ05.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dy86RZeiYlr7798lRqprHBc4Xtd.jpg",
    manualEmbed: "cos:movie/661655",
    trailerEmbed: "https://www.youtube.com/watch?v=RSdqbekQDDs",
    isSeries: false
  },
  {
    id: "Holy Emy",
    imdbId: "tt7172590",
    title: "Holy Emy",
    isFilipino: true,
    releaseDate: "2022-04-07",
    rating: 6.5,
    synopsis: "A young Filipina searches for the missing links between her strange bleeding condition and her faraway mother's healing powers.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/m255sOqX4xqVmhEH8kWeFlGWx9f.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5o2L96eCvBHooJmN6OAPzdPFUrI.jpg",
    manualEmbed: "cos:movie/846796",
    trailerEmbed: "https://www.youtube.com/watch?v=-CcA2KC_Q_c",
    isSeries: false
  },
  {
    id: "Rookie",
    imdbId: "tt28517914",
    title: "Rookie",
    isFilipino: true,
    releaseDate: "2023-08-04",
    rating: 6.5,
    synopsis: "An awkward 6-footer teen is forced to learn and play volleyball half-heartedly when the Catholic school she transferred to did not have a basketball team. Everything changes when she meets their star player.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/9SNc6K4E7RpMzaMZKZVs6PTuEqr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/33rPG4Jptob6La2TTID0VjQtSLn.jpg",
    manualEmbed: "cos:movie/1144708",
    trailerEmbed: "https://www.youtube.com/watch?v=VSTcOkT72J0",
    isSeries: false
  },
  {
    id: "Lockdown",
    imdbId: "tt15113504",
    title: "Lockdown",
    isFilipino: true,
    releaseDate: "2021-07-23",
    rating: 4.5,
    synopsis: "The struggles of a young man to survive the pandemic and the naked truth about the life he chose to live in.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nHa58uS38qTBxD1AY3YIBReElzr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Hyt3K14QED3viSlQamsLaonahk.jpg",
    manualEmbed: "cos:movie/819018",
    trailerEmbed: "https://www.youtube.com/watch?v=XlOHDd3sTrc",
    isSeries: false
  },
  {
    id: "A Faraway Land",
    imdbId: "tt15260940",
    title: "A Faraway Land",
    isFilipino: true,
    releaseDate: "2021-08-19",
    rating: 4.4,
    synopsis: "In the Faroe Islands, a married woman meets a reporter filming a documentary on overseas Filipino workers, which soon sparks a complicated love story.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/pd6ZRr7nQrRlgLFRWE2wyycdBr2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7eU1F9MaTHKWIZnTgeL4Dt2nH3G.jpg",
    manualEmbed: "cos:movie/863103",
    trailerEmbed: "https://www.youtube.com/watch?v=L43NMRArnWQ",
    isSeries: false
  },
  {
    id: "An Inconvenient Love",
    imdbId: "tt21801648",
    title: "An Inconvenient Love",
    isFilipino: true,
    releaseDate: "2022-11-23",
    rating: 5.4,
    synopsis: "Two young lovers agree to a casual relationship, but this convenient arrangement grows complicated as their romance reaches an expiration date.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/tebE0Buh9kH2xuPF9kjwf074LBJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/1QdJUF3j7s7pdG7bxOMlBjDluQN.jpg",
    manualEmbed: "cos:movie/1012906",
    trailerEmbed: "https://www.youtube.com/watch?v=Y28cTOW4coU",
    isSeries: false
  },
  {
    id: "The Missing",
    imdbId: "tt28288396",
    title: "The Missing",
    isFilipino: true,
    releaseDate: "2023-08-04",
    rating: 7.2,
    synopsis: "When an alien comes back to take him, a mouthless young man's life twists and turns as his memories untangle.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/25imGxPgIzLixlQ4XViDdzdcwGI.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/1GUKcU0U1Mxejn2uyJLgnERRcJA.jpg",
    manualEmbed: "cos:movie/1146277",
    trailerEmbed: "https://www.youtube.com/watch?v=SjWeTdhQrrg",
    isSeries: false
  },
  {
    id: "The Delivery Rider",
    imdbId: "tt38628374",
    title: "The Delivery Rider",
    isFilipino: true,
    releaseDate: "2025-10-23",
    rating: 7.1,
    synopsis: "A delivery driver accidentally witnesses a crime on the job with his eight-year-old surrogate son. Now, he must protect the child from violent forces.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/j0R5yjKebPTgxqvqTkq5zuumT7e.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/loh2zQrxrpGDs1IG74oGQR4dVal.jpg",
    manualEmbed: "cos:movie/1558981",
    isSeries: false
  },
  {
    id: "Delikado",
    imdbId: "tt19269218",
    title: "Delikado",
    isFilipino: true,
    releaseDate: "2022-04-29",
    rating: 7.2,
    synopsis: "In the majestic tropical island of Palawan, three environmental crusaders confront murder, betrayal and political corruption in this thrilling documentary about land defenders battling to save and preserve paradise in the Philippines.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ykFjQbXGY2V5yXx7SdOOgQioXKs.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/eOMYPEgSN94IkP5noVWTbJ6yOn.jpg",
    manualEmbed: "cos:movie/956442",
    trailerEmbed: "https://www.youtube.com/watch?v=VBukNEVFy4c",
    isSeries: false
  },
  {
    id: "Malaya",
    imdbId: "tt11602548",
    title: "Malaya",
    isFilipino: true,
    releaseDate: "2020-05-28",
    rating: 4.2,
    synopsis: "Stuck at a crossroad, will Malaya fight for the love she found, or will she choose to set her heart free?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/mKmNyiEtO3wDPEoAu7Z690QT0Qz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mlR19Pbr2n4C0AVaSdciEAjNM7X.jpg",
    manualEmbed: "cos:movie/700502",
    trailerEmbed: "https://www.youtube.com/watch?v=lMfCE0A06RQ",
    isSeries: false
  },
  {
    id: "My Lockdown Romance",
    imdbId: "tt13380864",
    title: "My Lockdown Romance",
    isFilipino: true,
    releaseDate: "2020-11-13",
    rating: 4.8,
    synopsis: "Two male buddies are reunited amidst the pandemic lockdown.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/8jUUq9aiXMYLbJHHHMTq7xzfs8G.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bGj2WTHuPpuVaP3oK5xYIpK6vqH.jpg",
    manualEmbed: "cos:movie/759469",
    trailerEmbed: "https://www.youtube.com/watch?v=-a324yqvn7A",
    isSeries: false
  },
  {
    id: "Genus Pan",
    imdbId: "tt12792586",
    title: "Genus Pan",
    isFilipino: true,
    releaseDate: "2020-09-11",
    rating: 5.7,
    synopsis: "Three illegal miners journey back to their island after months of toiling in hellish conditions. With their hard-earned money, they traversed the sea, the mountains and the forest until they reached their destination. Or did they really reach their cursed place?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/wcSRdb7vmwZGPGahDyHC6Hc4Lyu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nw7gvKdP0xdk7Gxk9zk4CjtM0uZ.jpg",
    manualEmbed: "cos:movie/728148",
    trailerEmbed: "https://www.youtube.com/watch?v=D2lKsbG4crU",
    isSeries: false
  },
];

// Merge into the main movies array (runs when app.js loads; guarded so a missing file can never break the site)
if (typeof window !== "undefined") {
  window.__deymflixMergeFilipino = function (moviesArray) {
    filipinoMovieData.forEach(function (m) {
      if (!moviesArray.some(function (x) { return x.id === m.id; })) moviesArray.push(m);
    });
  };
}
