// ==========================================
// DEYMFLIX - K-Drama (Korean) Series Data
// ==========================================
// Add NEW K-Dramas HERE (not in app.js).
// They merge into the main `movies` list automatically and appear in
// the K-Drama row, explore filters, search, and the player like any other title.
// IMPORTANT: this file must load BEFORE app.js on every page.
// Series entries: pair with an entry in kdrama-episode.js (kdramaSeriesData)
// for episodes. The `id` must match between the two files.
// ==========================================

const kdramaData = [
  
  { 
    id: "The+Scandal", 
    imdbId: "tt36347588",
    title: "The Scandal", 
    releaseDate: "2026-09-18",
    rating: 7.2,
    synopsis: "In Joseon, a secret proposal ignites hidden desires in a gifted noblewoman, a famed lover and an unsuspecting lady caught in their dangerous game.",
    isKdrama: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/4TU0PcHBIl0wPW5B6aVRGExOnHE.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/The+Scandal/Episode+1.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=FeISX5E1uJc",
    isSeries: true,
    completed: true
  },
  { 
    id: "The+Ordinary+Jackpot", 
    imdbId: "tt44072314",
    title: "The Ordinary Jackpot", 
    releaseDate: "2026-09-10",
    rating: 10,
    synopsis: "An ordinary office worker wins the lottery – the amount isn't enough for him to quit his job, but it's enough to give him a new outlook on life.",
    isKdrama: true,
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/3jLoiPorNssIfLlEuw8Om7ujca6.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/The+Ordinary+Jackpot+720p/Watch+The+Ordinary+Jackpot+-+S1-E1+Free.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=vAtzkLX_8no",
    isSeries: true,
    completed: false
  },
  { 
    id: "My+Bias,+My+Boss", 
    imdbId: "tt43648966",
    title: "My Bias, My Boss", 
    releaseDate: "2026-08-03",
    rating: 7.8,
    synopsis: "A dedicated fangirl lands a job at a fashion company, only to discover it was co-founded by her ultimate idol. Determined to remain professional, she hides her identity, but is quickly thrown off course by the company's workaholic CEO. As secret unrequited feelings and hidden personal struggles entangle the trio, she finds herself torn between her lifelong obsession and an unexpected new connection.",
    isKdrama: true,
    poster: "https://i.mydramalist.com/mOwKm1_4c.jpg?v=1",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/My+Bias%2C+My+Boss/Episode+1.mkv",
    trailerEmbed: "https://www.youtube.com/watch?v=kiHQZvDHDa0",
    isSeries: true,
    completed: true
  },
  { 
    id: "Mousetrap", 
    imdbId: "tt36996011",
    title: "Mousetrap", 
    releaseDate: "2026-08-28",
    rating: 8.1,
    synopsis: "A reclusive writer wakes to find his identity stolen — and must ally with a ruthless loan shark to reclaim his life from a man known as \"The Rat.\"",
    isKdrama: true,
    poster: "https://m.media-amazon.com/images/M/MV5BNWIwMWVhNTQtOGQ4Ny00MGFkLThjNzktZWVhNzI4YzFlMGE1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/Mousetrap/Mousetrap.S01E01.NF.x264.720p.Korean.mkv",
    trailerEmbed: "https://www.youtube.com/watch?v=UCTSqqHeMHw",
    isSeries: true,
    completed: true
  },
  { 
    id: "Spooky+in+Love", 
    imdbId: "tt40247521",
    title: "Spooky in Love", 
    releaseDate: "2026-07-18",
    rating: 8.7,
    synopsis: "When a ghost-seeing heir and an ace prosecutor learn that a single touch makes them a strangely effective duo, they team up to crack unsolved murders.",
    isKdrama: true,
    poster: "https://m.media-amazon.com/images/M/MV5BZGM4MDI4ODYtOTc3ZS00ZDc1LTkzYjgtMjc0OWUyMjFhN2E2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/Spooky+in+Love+720p/Spooky.in.Love.S01E01.NF.x264.720p.mkv",
    trailerEmbed: "https://www.youtube.com/watch?v=gFvycajlifg",
    isSeries: true,
    completed: true
  },
  { 
    id: "Dream+to+You", 
    imdbId: "tt39028251",
    title: "Dream to You", 
    releaseDate: "2026-07-13",
    rating: 9.1,
    synopsis: "Two high school classmates bond over a shared love of filmmaking, turning a deep friendship into first love before an unexpected separation tears them apart. Years later, they reunite with their lives completely transformed—she’s lost her passion, while he’s become a celebrated director. Determined to reignite her dreams, he must first confront the hurt he left behind.",
    isKdrama: true,
    poster: "https://m.media-amazon.com/images/M/MV5BZGU5ZTE1ZDEtMWI5Ny00ZDgxLTkyN2UtZjg0OWIzNmMwOWE0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/The+Scandal/Episode+1.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=CrW2onTvp7s&t=1s",
    isSeries: true,
    completed: true
  },
  { 
    id: "The+Apartment+Job", 
    imdbId: "tt43357366",
    title: "The Apartment Job", 
    releaseDate: "2026-07-11",
    rating: 8.7,
    synopsis: "Desperate for cash, a former gang boss teams up with an aspiring lawyer to steal an apartment complex's reserve fund — only to uncover deep corruption.",
    isKdrama: true,
    poster: "https://m.media-amazon.com/images/M/MV5BZTFiYzExMWMtNzQxOC00YjRjLTgwOWQtYjczZmMxZmQ0Y2UwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/The+Scandal/Episode+1.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=aovCC9XFVew",
    isSeries: true,
    completed: true
  },
  { 
    id: "See+You+at+Work+Tomorrow!", 
    imdbId: "tt38960812",
    title: "See You at Work Tomorrow!", 
    releaseDate: "2026-06-22",
    rating: 8.8,
    synopsis: "Cha Ji-yoon is a 7th-year corporate worker who's tired of both work and dating. She crosses paths with Kang Si-woo, the cynical boss with a terrifying reputation. Unexpectedly, she regains spark in her life as she gets to know the kindness behind his stern words. Amid repeated commutes, accidents at work, and failed relationships, the two become each other's irreplaceable anchor.",
    isKdrama: true,
    poster: "https://m.media-amazon.com/images/M/MV5BMzFlOTNiMzItNWNiZS00ODIzLWIxODMtYjc4ZjI2N2I4MjI2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    manualEmbed: "https://deymflix-media.b-cdn.net/K-DRAMA/The+Scandal/Episode+1.mp4",
    trailerEmbed: "https://www.youtube.com/watch?v=kBGgK8F3CSU",
    isSeries: true,
    completed: true
  },

  // ── 2026 Korean series (added 2026-09-29) — episode links pending ──
  {
    id: "Teach+You+a+Lesson",
    imdbId: "tt34809853",
    title: "Teach You a Lesson",
    releaseDate: "2026-06-05",
    rating: 9.4,
    isKdrama: true,
    synopsis: "An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/fMECSPrTmRClSViMsXFYmiYIcWP.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg",
    manualEmbed: "cos:tv/276161/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=LdezlX84py0",
    isSeries: true,
    completed: true
  },
  {
    id: "Our+Sticky+Love",
    imdbId: "tt36955608",
    title: "Our Sticky Love",
    releaseDate: "2026-08-07",
    rating: 8.8,
    isKdrama: true,
    synopsis: "An ambitious prosecutor loses her memory and moves in with a boxing coach who claims to be her boyfriend. Can this sticky situation turn into real love?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/tSZ4aFpTGc8Oj52SuzPUUZ7WKL0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mp2AFsWsuyxCzenJh3DTKw7z4jG.jpg",
    manualEmbed: "cos:tv/291496/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=Wndx_3B0lgc",
    isSeries: true,
    completed: true
  },
  {
    id: "Four+Hands,+Two+Sonatas",
    imdbId: "tt39368345",
    title: "Four Hands, Two Sonatas",
    releaseDate: "2026-08-29",
    rating: 9.2,
    isKdrama: true,
    synopsis: "When two young pianists from completely different worlds meet at an elite music high school, the melodies of their lives become intimately intertwined.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/a7p6htiJKx68USDAcilJ5rzKAWB.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fYL4I6cezb06BHhQlrNjNhy7jhf.jpg",
    manualEmbed: "cos:tv/305644/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=KapADxhCvvM",
    isSeries: true,
    completed: false
  },
  {
    id: "A+Love+Other+Than+Yours",
    imdbId: "tt43736405",
    title: "A Love Other Than Yours",
    releaseDate: "2026-09-12",
    rating: 9,
    isKdrama: true,
    synopsis: "A realistic, emotionally resonant romance about a couple in their tenth year together whose comfortable relationship is tested by unexpected feelings.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/iKgdhgBPi1cCRRqsUgaxUDRuFP6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/moUjiEzpJVNZc7hyNRBbLPt0CPX.jpg",
    manualEmbed: "cos:tv/314939/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=zp62ID0bbQM",
    isSeries: true,
    completed: false
  },
  {
    id: "Agent+Kim+Reactivated",
    imdbId: "tt42127457",
    title: "Agent Kim Reactivated",
    releaseDate: "2026-06-26",
    rating: 8.5,
    isKdrama: true,
    synopsis: "When an unassuming dad's daughter goes missing, he dusts off his old black-ops skills to track her down — only to attract the wrong kind of attention.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/mxa7YxVln3Rwnd2Va82PoclTznj.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/g1LJLlmWP74zv9yXKEXm7g9p10O.jpg",
    manualEmbed: "cos:tv/296206/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=k5IDEniQNEk",
    isSeries: true,
    completed: true
  },
  {
    id: "Perfect+Crown",
    imdbId: "tt39333617",
    title: "Perfect Crown",
    releaseDate: "2026-04-10",
    rating: 9.1,
    isKdrama: true,
    synopsis: "In 21st-century Korea under a constitutional monarchy, a chaebol heiress with everything but status tries to take control of her future after crossing paths with a lonely prince with nothing but his title. Together, bound by a contract marriage, they begin a class-defying romance to rewrite destiny.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/ocXkHSslrSWMz2ZJGl5MjF6dQr3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6ekykPwvAywJRjFEnUoCFWTO9O3.jpg",
    manualEmbed: "cos:tv/278573/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=MOXFNE9x1G4",
    isSeries: true,
    completed: true
  },
  {
    id: "The+WONDERfools",
    imdbId: "tt34440854",
    title: "The WONDERfools",
    releaseDate: "2026-05-15",
    rating: 8.8,
    isKdrama: true,
    synopsis: "A goofy group of townies stumbles into superpowers and fights rising evil as doomsday panic grows in this wild, turn-of-the-century action comedy.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg",
    manualEmbed: "cos:tv/259837/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=rVoc4WQVMCc",
    isSeries: true,
    completed: true
  },
  {
    id: "A+Bona+Fide+Killer",
    imdbId: "tt43616775",
    title: "A Bona Fide Killer",
    releaseDate: "2026-07-31",
    rating: 8.1,
    isKdrama: true,
    synopsis: "A seemingly ordinary working mother secretly lives as a legendary sniper who delivers justice where the law fails. After returning from a three-year hiatus, she must balance protecting her family with eliminating dangerous criminals, all while a determined journalist and a relentless detective close in on her hidden identity.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/e9ziA4Y6md4Ytr62r5y9vRdv4ll.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/j9AqsMJxuq7NEYJX4Q1vSfKb5CG.jpg",
    manualEmbed: "cos:tv/294095/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=bqBRG54y3X0",
    isSeries: true,
    completed: true
  },
  {
    id: "Dive+into+You",
    imdbId: "tt43088191",
    title: "Dive into You",
    releaseDate: "2026-09-26",
    rating: 8,
    isKdrama: true,
    synopsis: "An actress and her twin brother slip through time – and swap bodies – to save their friend's life.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/6OAuQOGqjYY1JXbkTlWz4Mm2Kmi.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jseW3HucgNjN2CwJa3MiOlF4xMO.jpg",
    manualEmbed: "cos:tv/316197/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=VZDtO0cXoPQ",
    isSeries: true,
    completed: false
  },
  {
    id: "My+Royal+Nemesis",
    imdbId: "tt38828946",
    title: "My Royal Nemesis",
    releaseDate: "2026-05-08",
    rating: 8.8,
    isKdrama: true,
    synopsis: "A Joseon-era villain doomed to die opens her eyes in modern-day Seoul — where a ruthless chaebol heir may be her last chance to rewrite her fate.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/rYLQbyIvbEd0lF84iXrx7CbPcBB.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/p1ntnKJwn1URGv1xpU6NN33Y11O.jpg",
    manualEmbed: "cos:tv/303143/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=efj9rk9mCeo",
    isSeries: true,
    completed: true
  },
  {
    id: "Filing+for+Love",
    imdbId: "tt39010903",
    title: "Filing for Love",
    releaseDate: "2026-04-25",
    rating: 8.1,
    isKdrama: true,
    synopsis: "A romantic comedy about Joo In-ah, a charismatic audit department head with a secret, and Noh Ki-joon, the department's ace who is suddenly demoted to deal with the company's scandals.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/5dgTRxtP5g07RSH5LEOl367Fuwi.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xrzle63zw2MduVGmTFeKNXKqUla.jpg",
    manualEmbed: "cos:tv/297640/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=CyhwlmMkktc",
    isSeries: true,
    completed: true
  },
  {
    id: "If+Wishes+Could+Kill",
    imdbId: "tt36104233",
    title: "If Wishes Could Kill",
    releaseDate: "2026-04-24",
    rating: 8,
    isKdrama: true,
    synopsis: "A mysterious app promises wishes — then starts a countdown to death. As a group of teens becomes entangled, they must break the deadly chain to survive.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/2CfTNVaR8kZQkWtWWE3Cntaiq33.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5BzfcAW5ZI2m7QypeJBbYNjBuR0.jpg",
    manualEmbed: "cos:tv/285838/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=OJsERPNI3D0",
    isSeries: true,
    completed: true
  },

  // ── 2025 Korean series (added 2026-09-30) — episode links pending ──
  {
    id: "Made+in+Korea",
    imdbId: "tt33298903",
    title: "Made in Korea",
    releaseDate: "2025-12-24",
    rating: 8.1,
    isKdrama: true,
    synopsis: "In 1970s South Korea, follow two men on opposite sides of power — one driven by ambition, the other by justice. As their worlds collide, greed, loyalty, and survival intertwine in a battle that will shape a nation.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/2yEXTvaCPUe9In5MZJBLFwiq0NL.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/3GmRS3efCTp6jumogKOxYBrV5mO.jpg",
    manualEmbed: "cos:tv/246473/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=GRlEArXazfM",
    isSeries: true,
    completed: false
  },
  {
    id: "When+Life+Gives+You+Tangerines",
    imdbId: "tt26471411",
    title: "When Life Gives You Tangerines",
    releaseDate: "2025-03-07",
    rating: 8.8,
    isKdrama: true,
    synopsis: "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/a9qlroMOHewiDsUR93PYMVfpbF5.jpg",
    manualEmbed: "cos:tv/219246/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=4ECAaQkNAbc",
    isSeries: true,
    completed: true
  },
  {
    id: "Genie,+Make+a+Wish",
    imdbId: "tt32409807",
    title: "Genie, Make a Wish",
    releaseDate: "2025-10-03",
    rating: 7.9,
    isKdrama: true,
    synopsis: "After a thousand years, a quirky genie returns to grant wishes to a woman born without feelings. Can his magic bring love and wonder to her world?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/opop2u7Jav6lMNL8fSBTzOeFBDz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2ds9EWX7cwGfZiRjYqhyw7SbzsW.jpg",
    manualEmbed: "cos:tv/228689/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=PaZIDBqhVSk",
    isSeries: true,
    completed: true
  },
  {
    id: "Study+Group",
    imdbId: "tt35304338",
    title: "Study Group",
    releaseDate: "2025-01-23",
    rating: 8.6,
    isKdrama: true,
    synopsis: "A struggling student at Korea's worst high school forms a study group while protecting his classmates with his fighting skills, hoping to overcome academic challenges and secure a spot in college.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nZDeIfKCzp0qhu4N3HxrcKWN59J.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/A32KgHacV0pCJNYIH4JrQb5djGu.jpg",
    manualEmbed: "cos:tv/233347/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=Bx0piV_Uf4E",
    isSeries: true,
    completed: false
  },
  {
    id: "Kian's+Bizarre+B&B",
    imdbId: "tt33047061",
    title: "Kian's Bizarre B&B",
    releaseDate: "2025-04-08",
    rating: 8,
    isKdrama: true,
    synopsis: "On a remote island, Kian84 hosts a quirky B&B escape, where BTS' Jin and Ji Ye-eun lead guests through playful exploits and delightful chaos.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/1iLD4qd9hbCjiBIyu64F9OImK4I.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cHBRJc2ON9WfL71fuvnsWDHRCFN.jpg",
    manualEmbed: "cos:tv/256355/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=qcgMhDIFOc8",
    isSeries: true,
    completed: false
  },
  {
    id: "Good+Boy",
    imdbId: "tt32361930",
    title: "Good Boy",
    releaseDate: "2025-05-31",
    rating: 8.6,
    isKdrama: true,
    synopsis: "Olympic medalists join the police force through a special recruitment program, trading medals for badges as they tackle violent crimes and injustices with their athletic skills.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/59MAdHaHepsz3uDCU1LyoNQcLlT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8l1BN0IIjHmRyW0oDfUfs3F6F4N.jpg",
    manualEmbed: "cos:tv/231280/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=kWT5jZrXxhg",
    isSeries: true,
    completed: true
  },
  {
    id: "The+Manipulated",
    imdbId: "tt36188448",
    title: "The Manipulated",
    releaseDate: "2025-11-05",
    rating: 8.4,
    isKdrama: true,
    synopsis: "Taejoong's life is torn apart when he's framed for a heinous crime and imprisoned. Discovering it was all orchestrated by someone on the outside, he embarks on a rage-fueled quest for revenge.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nOj4nsomFyAVJgpp68L0xq3cREc.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ngP3rIU1KY7ek0r6hSJFnVsrh9g.jpg",
    manualEmbed: "cos:tv/239385/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=cXPDFkuLfhs",
    isSeries: true,
    completed: true
  },
  {
    id: "Dear+X",
    imdbId: "tt37890201",
    title: "Dear X",
    releaseDate: "2025-11-06",
    rating: 8.6,
    isKdrama: true,
    synopsis: "Behind a beautiful face hides a cruel nature—Baek Ah-jin, who sees through and manipulates others' hearts. After stepping on the sacrifices of many to reach the top, everything begins to change the moment she arrives there. A woman wearing a mask to escape hell and climb to the highest place. And the story of the Xs being brutally crushed by her.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/j2w2PZ5JHEv0HUXwrhsToYiTP4r.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iDnZoZvv220H6pigUWt3BlfPdxQ.jpg",
    manualEmbed: "cos:tv/256226/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=4_s3l_jrEmM",
    isSeries: true,
    completed: true
  },
  {
    id: "Aema",
    imdbId: "tt29059394",
    title: "Aema",
    releaseDate: "2025-08-22",
    rating: 7.4,
    isKdrama: true,
    synopsis: "In 1980s Korea, a movie star and a starlet defy male-dominated industry rules and backstage corruption while filming the provocative \"Madame Aema.\"",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/jD8uwm1fvt6y2yxjSO6R9IOFwQQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Kl07j8DsHfAwkODBblg81mjcGc.jpg",
    manualEmbed: "cos:tv/229958/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=pHTADS1Ve9I",
    isSeries: true,
    completed: true
  },
  {
    id: "Trigger",
    imdbId: "tt27898511",
    title: "Trigger",
    releaseDate: "2025-07-25",
    rating: 8.1,
    isKdrama: true,
    synopsis: "As illegal firearms flood into a gun-free South Korea, a resolute cop and a mysterious partner join forces to stop the chaos from sweeping the nation.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/9eDF8Z4iFFCmQROiuej54rSK9LT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2jiEkTXR7oiQNDfdday8AM9J5qF.jpg",
    manualEmbed: "cos:tv/238084/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=2JUx8MqpRuM",
    isSeries: true,
    completed: true
  },
  {
    id: "Beyond+the+Bar",
    imdbId: "tt37660730",
    title: "Beyond the Bar",
    releaseDate: "2025-08-02",
    rating: 8.1,
    isKdrama: true,
    synopsis: "A young, rookie lawyer with a strong sense of justice joins a top law firm — navigating the complex legal world under a cold, demanding mentor.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nN6mZZxJBPZXBjLxnjgpnoRvswk.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9MEzfTNfnTvCLHXfRu7a5TSJCsx.jpg",
    manualEmbed: "cos:tv/281004/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=8o8uHnAFwcA",
    isSeries: true,
    completed: true
  },
  {
    id: "Bon+Appétit,+Your+Majesty",
    imdbId: "tt37600136",
    title: "Bon Appétit, Your Majesty",
    releaseDate: "2025-08-23",
    rating: 8.6,
    isKdrama: true,
    synopsis: "After time traveling to the Joseon era, a talented chef meets a tyrant king. Her modern dishes captivate his palate, but royal challenges await her.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/exUXEOierAwZ597010TLQka9TFy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ttbmzTZHTzqDK4JniKonMrsQath.jpg",
    manualEmbed: "cos:tv/280945/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=rkB623sLOiM",
    isSeries: true,
    completed: true
  },
  {
    id: "Unmasked",
    imdbId: "tt31390522",
    title: "Unmasked",
    releaseDate: "2025-01-15",
    rating: 8,
    isKdrama: true,
    synopsis: "In modern-day Seoul, a crack team of investigative journalists fight for their careers after broadcasting a controversial story. With time running out, the team are given an impossible task if they want to save their jobs – solve a twenty-year-old cold case involving a famous actor who disappeared without a trace.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/piSUZXvzOw7GxwrtRuTmimW8YJE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xI4sbzJPNorYgTkfYs4ycMombVc.jpg",
    manualEmbed: "cos:tv/239006/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=uvcv3p7rlvE",
    isSeries: true,
    completed: true
  },
  {
    id: "When+the+Stars+Gossip",
    imdbId: "tt26215550",
    title: "When the Stars Gossip",
    releaseDate: "2025-01-04",
    rating: 7.4,
    isKdrama: true,
    synopsis: "From two different worlds and with separate missions, an astronaut and a space tourist entangle in space — only to start falling for each other.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/pdOiUbJ0vEJfh5OGFG8y1e4InQ7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/sP0R5F8fkVM0eHcRFXr012rzNAM.jpg",
    manualEmbed: "cos:tv/154822/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=ASd_GLr3ZFY",
    isSeries: true,
    completed: true
  },
  {
    id: "Mercy+for+None",
    imdbId: "tt29650530",
    title: "Mercy for None",
    releaseDate: "2025-06-06",
    rating: 7.8,
    isKdrama: true,
    synopsis: "After severing ties with his gang, a former gangster returns to uncover the truth behind his brother's death — embarking on a relentless path of revenge.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/AjL335mFBe7LgCqo3w0RNBSbbZU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fWJjsS2Tr2dlpYuw3o7Lifvgkru.jpg",
    manualEmbed: "cos:tv/232766/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=ZG5oMij_26s",
    isSeries: true,
    completed: true
  },
  {
    id: "Friendly+Rivalry",
    imdbId: "tt35683421",
    title: "Friendly Rivalry",
    releaseDate: "2025-02-10",
    rating: 8.7,
    isKdrama: true,
    synopsis: "A high-teen mystery thriller about a close relationship between teenage girls in a harsher survival competition than entrance examinations.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/qBQl7x6qSqeuYdgq7rkctm1L4gW.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/z1MKvQJVVMbt1svoV3zjh6cRUTv.jpg",
    manualEmbed: "cos:tv/259288/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=0ZMv78yd4V8",
    isSeries: true,
    completed: true
  },
  {
    id: "Resident+Playbook",
    imdbId: "tt31171500",
    title: "Resident Playbook",
    releaseDate: "2025-04-12",
    rating: 8.1,
    isKdrama: true,
    synopsis: "First-year OBGYN residents at Yulje Medical Center navigate the chaos of their work and personal lives, all in their quest to become exceptional doctors.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/bB5Tu1Rzq6guKsMhV59aszN9c0a.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/A4X2JVnABZeZpMAWcI0eBHvLYAl.jpg",
    manualEmbed: "cos:tv/235355/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=NWqm_D9wEhM",
    isSeries: true,
    completed: true
  },
  {
    id: "The+Trauma+Code:+Heroes+on+Call",
    imdbId: "tt28106730",
    title: "The Trauma Code: Heroes on Call",
    releaseDate: "2025-01-24",
    rating: 8.5,
    isKdrama: true,
    synopsis: "To create a top-tier trauma center, a war-seasoned doctor arrives — bringing his blunt but skilled ways to transform his team into life-saving mavericks.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/y8h2RwUZM5chv9tuaKVwSPoo3KE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/58XBnfKhP569SuZuXks3fNYpLBm.jpg",
    manualEmbed: "cos:tv/217553/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=pdDXO-dMjAc",
    isSeries: true,
    completed: false
  },
  {
    id: "Nine+Puzzles",
    imdbId: "tt29927351",
    title: "Nine Puzzles",
    releaseDate: "2025-05-21",
    rating: 7.9,
    isKdrama: true,
    synopsis: "Ten years after discovering her murdered uncle, Ena and Detective Hansaem must cooperate to stop a series of similar murders - each linked by strange puzzle pieces.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/eQWEWCOg5LZLu2AihfMueiHGw1Y.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6OfitF3ifOJmlglcixB3ixnNydW.jpg",
    manualEmbed: "cos:tv/227191/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=-UKrjg6RrjI",
    isSeries: true,
    completed: true
  },
  {
    id: "Hyper+Knife",
    imdbId: "tt35378081",
    title: "Hyper Knife",
    releaseDate: "2025-03-19",
    rating: 7.8,
    isKdrama: true,
    synopsis: "Seok, an eager yet genius neurosurgeon is reunited with Deokhee, the professor who ruined her life long ago. Once, the two surgeons cared for each other more than anyone else. But now with nothing but hatred toward each other, Seok is furious that he is back in her life and vows to take revenge.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/hHkiSxa7O8kPjyyTJ9ue2mqYJVx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gd6er39HiIfVQIDKhZdMz7FVIw.jpg",
    manualEmbed: "cos:tv/245079/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=JY73T7jgex8",
    isSeries: true,
    completed: true
  },
  {
    id: "My+Dearest+Nemesis",
    imdbId: "tt33320428",
    title: "My Dearest Nemesis",
    releaseDate: "2025-02-17",
    rating: 8.1,
    isKdrama: true,
    synopsis: "Baek Su-jeong leads a planning team at a renowned department store. She meets her new boss, Ban Ju-yeon, her first love from an online game 16 years ago, stirring up memories of when he confessed his feelings but she rejected him.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/84ZP2lykuGBwG13wgtLzVKtfBS.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4Xer0oaXautbLRfJQOrlmPSCfN1.jpg",
    manualEmbed: "cos:tv/259015/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=ZxP6GHIolkI",
    isSeries: true,
    completed: true
  },
  {
    id: "Head+Over+Heels",
    imdbId: "tt37146661",
    title: "Head Over Heels",
    releaseDate: "2025-06-23",
    rating: 8.7,
    isKdrama: true,
    synopsis: "A teenage shaman determined to change fate sets out to save a mysterious boy destined to die. As danger looms, their fated encounter sparks a powerful first love that defies darkness and reclaims hope.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/kL42DhVhqjO3NxlB0oNg2Z4TAWP.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jpxN1QHRSG660Ql62EHZvZzeaCA.jpg",
    manualEmbed: "cos:tv/258025/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=BCN3rBLSJQk",
    isSeries: true,
    completed: true
  },
  {
    id: "Surely+Tomorrow",
    imdbId: "tt38221085",
    title: "Surely Tomorrow",
    releaseDate: "2025-12-06",
    rating: 7.7,
    isKdrama: true,
    synopsis: "In their twenties, Lee Kyeong-do and Seo Ji-woo part ways after two passionate relationships. A decade later, they meet again as a reporter who covers an adultery scandal and the wife of the man at the center of that scandal. Reuniting in their late thirties, their youth has passed, but their love remains vivid. Kyeong-do now strives to prove to her and to himself that he still loves her.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/k9xPcIsxXbc1Xuf45K0FU8yM2m5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/duXUA6kzqCa56MNfUqoJQa6c6Gg.jpg",
    manualEmbed: "cos:tv/281005/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=dVoO8wLcAB8",
    isSeries: true,
    completed: true
  },
  {
    id: "Dynamite+Kiss",
    imdbId: "tt38353551",
    title: "Dynamite Kiss",
    releaseDate: "2025-11-12",
    rating: 8.2,
    isKdrama: true,
    synopsis: "A passionate fling in Jeju ends abruptly — until fate reunites an heir and a young woman when she joins his company, disguised as a married mother.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/qY3ltlWUB7u3ENocrMOkbGCGYnt.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cTFQKu8CLftXHUCIBGksfL8uhf3.jpg",
    manualEmbed: "cos:tv/281013/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=PukVwohE-Vk",
    isSeries: true,
    completed: true
  },
  {
    id: "Newtopia",
    imdbId: "tt32199328",
    title: "Newtopia",
    releaseDate: "2025-02-07",
    rating: 8,
    isKdrama: true,
    synopsis: "Jae-yoon, a late military enlistee, and his girlfriend, Young-joo, break up over the phone over growing misunderstandings. But a zombie outbreak rocks the world. A national emergency is declared, a plane crashes in the city center, and Jae-yoon and his unit get trapped on top of a Seoul skyscraper. Young-joo risks the zombie-filled streets to find him. Can their love survive the apocalypse?",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/cIC36RA59lg9ruYtPc7UA3f72yy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/olRPEYjyjzoMAODjOMjF2K1VlzO.jpg",
    manualEmbed: "cos:tv/233742/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=HtaaO9D9ZcU",
    isSeries: true,
    completed: true
  },
  {
    id: "S+Line",
    imdbId: "tt36056620",
    title: "S Line",
    releaseDate: "2025-07-11",
    rating: 7.5,
    isKdrama: true,
    synopsis: "A young woman with the ability to see mysterious red connections between lovers discovers her secret gift is no longer unique when special glasses granting similar powers appear on the black market.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/7TGolwcia6AI6uvInBOoedAi9Il.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/buA9gM0cEcBmIcQX79o6QpTYUPT.jpg",
    manualEmbed: "cos:tv/232402/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=ozeChwYWHhY",
    isSeries: true,
    completed: true
  },
  {
    id: "Karma",
    imdbId: "tt29921070",
    title: "Karma",
    releaseDate: "2025-04-04",
    rating: 7.5,
    isKdrama: true,
    synopsis: "A fateful accident intertwines six lives in a thrilling tale of karma and crime, where each must face their own dark truths and connections.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/nZ7SFBgEhgSCaQFFActjcBQeIV1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/66X23qG4RPk7XPDQCFFHHCage3M.jpg",
    manualEmbed: "cos:tv/233686/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=E_e9cpN994s",
    isSeries: true,
    completed: true
  },
  {
    id: "The+First+Night+with+the+Duke",
    imdbId: "tt37266905",
    title: "The First Night with the Duke",
    releaseDate: "2025-06-11",
    rating: 8,
    isKdrama: true,
    synopsis: "Reincarnated as a minor character in a novel, Cha Seon-taek unexpectedly spends a night with Prince Kyungsung, sparking an intense and unexpected romance.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/dlR9GzrDjioALN9W4RMFfjYyIXF.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xPFmxUuZnmYAlpoO5QI9AdYegxt.jpg",
    manualEmbed: "cos:tv/278331/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=aV4Y4Bav_eE",
    isSeries: true,
    completed: true
  },
  {
    id: "Undercover+High+School",
    imdbId: "tt33364760",
    title: "Undercover High School",
    releaseDate: "2025-02-21",
    rating: 8,
    isKdrama: true,
    synopsis: "Ace NIS agent Jung Hae-seong is demoted after a mission failure. He goes undercover at a high school to locate King Gojong's missing gold, meeting his teacher Oh Soo-ah, who sees him as her lost first love, stirring old heartbreak.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/vXAWUI1pYrBvZoUarGxWj1mtlXp.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lAOiaHI5OoY1t4L5rcmwaf1HkLs.jpg",
    manualEmbed: "cos:tv/248244/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=lUxhuwhczn8",
    isSeries: true,
    completed: true
  },
  {
    id: "Tempest",
    imdbId: "tt27368147",
    title: "Tempest",
    releaseDate: "2025-09-10",
    rating: 7.6,
    isKdrama: true,
    synopsis: "Seo Munju, a highly accomplished diplomat and former ambassador to the United Nations, and Sanho, an international special agent shrouded in a veil of secrets, race to uncover the truth behind an attack that threatens the future stability of the Korean peninsula.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/cCSOw482P0el3ioDnZEDhggrQoj.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wyCQovekJ10HnmqCE3lPNaoGDde.jpg",
    manualEmbed: "cos:tv/223326/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=YEz4SuMI1-Q",
    isSeries: true,
    completed: true
  },
  {
    id: "Love+Scout",
    imdbId: "tt34730468",
    title: "Love Scout",
    releaseDate: "2025-01-03",
    rating: 8,
    isKdrama: true,
    synopsis: "Yoo Eun-ho, a single dad armed with perfection, becomes the secretary of Kang Ji-yun, the CEO of a popular headhunter company, who doesn't do anything except work.",
    poster: "https://media.themoviedb.org/t/p/w600_and_h900_face/sp7OIpJl6uLiPqTgsc2wwrO9P8c.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lzidnBhiOCJdtKkUBD2TOfYLE8d.jpg",
    manualEmbed: "cos:tv/233100/1/1",
    trailerEmbed: "https://www.youtube.com/watch?v=UXkEEL4MatE",
    isSeries: true,
    completed: true
  },
];

// Merge into the main movies array (runs when app.js loads; guarded so a missing file can never break the site)
if (typeof window !== "undefined") {
  window.__deymflixMergeKdrama = function (moviesArray) {
    kdramaData.forEach(function (m) {
      if (!moviesArray.some(function (x) { return x.id === m.id; })) moviesArray.push(m);
    });
  };
}
